### ISSUE TITLE
Will not find tabs 

### ISSUE THREAD

**Issue by Steavenseagull** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#100]
if i have it set out 0,1 for some reason it picks up my 12th tab instead of the first 2

**Comment by kosace** [comment]
do you have remove only tabs?

**Comment by Steavenseagull** [comment]
Not in the new league just standard does that even effect it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
