### ISSUE TITLE
Forbidden Error

### ISSUE THREAD

**Issue by Herrm2291** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#101]
Hi there,

I installed the previous version a day before the launch of the new PoE league (Ritual) went live and it was working fine.  It was also working fine until a few hours into the league launch, then I just kept getting a "Forbidden" error when I would try to fetch.  I installed the latest version a few minutes ago but still, I get the same error.

Please help, thanks in advance!

**Comment by Herrm2291** [comment]
If you're having this issue, you HAVE to uninstall the old version first, THEN install the new version, you can't simply install over the old version.

**Comment by pkunztc** [comment]
@Herrm2291 Thanks dude!

> If you're having this issue, you HAVE to uninstall the old version first, THEN install the new version, you can't simply install over the old version.

**Comment by Herrm2291** [comment]
> @Herrm2291 Thanks dude!
> 
> > If you're having this issue, you HAVE to uninstall the old version first, THEN install the new version, you can't simply install over the old version.

@pkunztc You're welcome!  This was driving me crazy and when I finally tried this and it worked, I knew I had to go update my post in case anyone else came here looking for answers like I was.  😅
