### ISSUE TITLE
Item Threshold and Set Count

### ISSUE THREAD

**Issue by UltraReality2** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#102]
Having this with versions 1.13, 1.14, 1.16, 1.18

Item Threshold continue to pick the items and doesn't stop
Sets are always 0, so i just can't start picking from stash. Only manually. Threshold is 10
![Screenshot_1](https://user-images.githubusercontent.com/15912574/105131314-be3da680-5af9-11eb-9c48-45090e050a39.png)

**Comment by 9999n** [comment]
I have the same problem, in the same versions. For me - chestpieces are the only that register when they hit whatever maximum set limit I set. All other items collect seemingly infinitely and so it never registers any full sets and never prompts me to sell sets off.

**Comment by UltraReality2** [comment]
Yeah, chestpieces are the only, confirm

**Comment by kosace** [comment]
did you activate fill greedy?

**Comment by 9999n** [comment]
> did you activate fill greedy?

Oh my god, yeah that was it. I understood what that option meant when I read it the first time, that I could continue to chaos rec once i'm outside the level range for it buy downgrading a regal recipe and not over use. But it didn't click that it would of course keep that approach when I was only inside level range.

Thanks mate

**Comment by kosace** [comment]
Reopen if it doesnt work for you @UltraReality2
