### ISSUE TITLE
Autofilter not working for everything, doesn't recognise sets

### ISSUE THREAD

**Issue by panicwhale** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#105]
Hi - thanks for your work on this app.  It's great and super efficient :)

Mine is currently only turning off body armors once I reach the Full Set Threshold.  It also doesn't recognise when I have a full set in my stash, so doesn't allow the stash tab overlay to function.

Any suggestions?

![image](https://user-images.githubusercontent.com/73860827/105230585-4763e480-5bb1-11eb-8914-6511fbbc88a4.png)

**Comment by jibby1445** [comment]
Nevermind I fixed this issue by updating the filter. (download a brand new one)

**Comment by Emixamus** [comment]
Well I updated the chaos recipe enhancer and nothing... I got the same problem as you... 10+of each item, all 70-72. No sets shown.

**Comment by kosace** [comment]
activate fill greedy

**Comment by panicwhale** [comment]
thanks this fixed it for me!
