### ISSUE TITLE
My whole filter got deleted.

### ISSUE THREAD

**Issue by AlphaRage** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#106]
Not sure what happened but the tool deleted my filter. I have been using it for a few days without problems but after some time today the tool deleted the content of my filter. I didn't do anything differently.

Of course I don't have a backup but that's on me.

Anyway this is what it looks like right now:
[AlphaRage_Filter_Rework.filter.txt](https://github.com/kosace/EnhancePoEApp/files/5845564/AlphaRage_Filter_Rework.filter.txt)

**Comment by kosace** [comment]
do you have newest version`? and did you use the version before?

**Comment by AlphaRage** [comment]
I started using the program with 1.14 at league start. Updated to 1.17 right after release. While doing that I deleted all the lines the tool adds to the top of the filter. I kept using the tool. It updated my filter a few times as well throughout the day. I didn't touch the filter file or the program but suddenly everything was gone.

**Comment by kosace** [comment]
try the newest version please and report if it happens again. thats not good if the tool deletes those filters

**Comment by AlphaRage** [comment]
I will. Just updating my filter again now. Spent a few hours on it yesterday. Stupid of me to not have a backup but maybe you can put a big warning somewhere for people to make backups.

Other than that I will keep using the tool because it's just so good. I will keep an eye out for this problem.

There's just one more bit of information I can share with you: I know that the filter that got deleted has an empty new line at the top and the next few lines were comments. Don't know if that helps you in any way but that's all I remember.
