### ISSUE TITLE
Not considering chests for some reason?

### ISSUE THREAD

**Issue by henriquesaboya** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#107]
it does counts items fine, but for some reason, its not considering these chests.

help pls. chests are good and ilvl 70-72

![image](https://user-images.githubusercontent.com/19479283/105366395-0c2bda80-5bde-11eb-9cab-a857368b8c86.png)

**Comment by jrettsch** [comment]
The greyed out icon means, that it's not included in the item filter - probably because you have enough in your stash tab. What is your setting for "Full Set Threshold"?

**Comment by kosace** [comment]
I dont get what the problem is... How do you know its not working? Is it not hidden by lootfilter?
