### ISSUE TITLE
Program doesn't find a chaos set eventhough it's there

### ISSUE THREAD

**Issue by POE-Addon-Launcher** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#11]
Hey, wanted to try out the program on my overfilled quadstash tab, but the program doesn't seem to be able to identify any set in my stash tab:

![image](https://user-images.githubusercontent.com/42203962/102811483-ade4bf80-43c5-11eb-827a-1edf0bf3b61f.png)

![image](https://user-images.githubusercontent.com/42203962/102811461-a6bdb180-43c5-11eb-9f4e-3b713129b401.png)

Eventhough there was at least one set:
![image](https://user-images.githubusercontent.com/42203962/102811662-fe5c1d00-43c5-11eb-9658-ac04567b9be6.png)

Any ideas what's wrong?

**Comment by kosace** [comment]
Hello, 

can you check if you have remove-only tabs? in the top right corner on the gear icon you can show them if you have some.

**Comment by POE-Addon-Launcher** [comment]
No this is in the active temp league, it doesn't have remove-only tabs that is only in standard.

**Comment by kosace** [comment]
nope, there are event remove-only tabs sometimes. 

if you paste this link in your browser, it shows you all your stashtabs:

https://www.pathofexile.com/character-window/get-stash-items?accountName=YOURACCOUNTNAME&league=YOURLEAGUE&tabIndex=0

pls confirm if there are remove-only tabs

**Comment by POE-Addon-Launcher** [comment]
I have 18 tabs in the JSON, just like I have ingame, Tab index: 8 is the tab I wanted it to check so API Call wise it all seems to be in order.

**Comment by kosace** [comment]
can you try with stashtab mode: prefix pls?

**Comment by kosace** [comment]
also make sure there are no spaces in your account name and league name. in the next update i will delete those automatically

**Comment by POE-Addon-Launcher** [comment]
Prefix also does not seem to change anything, don't really know what's weird then, my Account Name has no Spaces in it, however, the league does have a space, in the API call I replaced the space with a %20 to make it work, so maybe you can do that in your request if you're not doing that?

**Comment by kosace** [comment]
the space in the league is no problem, only at the beginning or the end (fixed in next update).
i think the problem is, it only consideres unidentified items. the screenshot shows no full unidentified set (just saw it).

maybe i will add support for identfied items in next patch

**Comment by POE-Addon-Launcher** [comment]
Aha, that explains it then

**Comment by zombodotcom** [comment]
can't seem to get it to work for me either followed the steps and it shows my tab. but doesn't show any sets or highlights with a chaos set in my tab
