### ISSUE TITLE
Reload Item Filter

### ISSUE THREAD

**Issue by JJoooee** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#110]
So does the item filter reload itself after I found enough items from one categorie to hide the next ones or do I have to do this manually everytime I found enough of one?

**Comment by Barragek0** [comment]
If you link your filter in the lootfilter tab and tick lootfilter manipulation, it will automatically update your filter to show the items you want to pickup.

**Comment by Natahh** [comment]
Mine isn't working right either. When I get enough of a set, the loot still shows and the overlay icon doesn't grey out

**Comment by JJoooee** [comment]
yes I did this but what I mean is that if you have enough chest armor that the chests which are dropped are hidden on the floor. Do you know what I mean?

**Comment by Davst** [comment]
@JJoooee There is no way to reload an item filter via any other method than pressing the reload button. That being said, you only have to reload your filter when a a icon in the overlay changes from colored to "greyed out" or back.

The notification sound setting will play a chime when you need to reload (far from every map)
