### ISSUE TITLE
Fetch says Full and Stash is giving error

### ISSUE THREAD

**Issue by xShingox** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#113]
First time user.

When i press Fetch it says i have FULL Sets but 0 in all equipment
When i Press STASH i get an error 
"No StashTabs Available! Fetch before opening Overlay"

**Comment by xShingox** [comment]
![image](https://user-images.githubusercontent.com/77858332/105540944-e5d47080-5cab-11eb-827c-de4b34aa25eb.png)

**Comment by kosace** [comment]
yeah that is a bug when it cant find stashtabs. that will be fixed in the next update. but that also means something in your settings is worng.

**Comment by xShingox** [comment]
@kosace could you elaborate? What settings? 
The only unsure part i had was "Log File Location" is it supposed to be the client.txt?

**Comment by kosace** [comment]
post a screen of your settings. it cant find your stashtab

**Comment by kosace** [comment]
and yes it is client.txt

**Comment by xShingox** [comment]
![image](https://user-images.githubusercontent.com/77858332/105551647-ca6f6280-5cb7-11eb-9df2-9fb71dc49cc9.png)

**Comment by xShingox** [comment]
![image](https://user-images.githubusercontent.com/77858332/105551708-d4916100-5cb7-11eb-8226-a93caf9b7899.png)

**Comment by xShingox** [comment]
![image](https://user-images.githubusercontent.com/77858332/105551770-e115b980-5cb7-11eb-9f0b-7fb17efcbff7.png)

**Comment by Rovec** [comment]
I have the same issus and i have the same settings as " xShingox " .

**Comment by kosace** [comment]
can you test with prefix mode instead?

**Comment by xShingox** [comment]
Ive tried it both ways.

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
