### ISSUE TITLE
How do you find the Log File location

### ISSUE THREAD

**Issue by Deadandlivin** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#114]
In the newest version 1.2.0 You're supposed to specify the log file location.
I'm no tech wizard and have no clue what type of file this is or where the location is. I tried to search through my PoE map but couldn't find anything.

Where can I find this file and more specifically, what's the name of the file where supposed to locate?

**Comment by Natahh** [comment]
its the client.txt in the log folder in your main game location

**Comment by Davst** [comment]
A suggestion to help this would be to read the uninstall information or similar to fetch the path of Path of Exile so people wouldn't have to search for it themselves.

**Comment by kosace** [comment]
If you hover over the label you can See a tooltip where the Standard location is specified. 

Most settings have those tooltips although i sometimes forget to update them

**Comment by kosace** [comment]
@Davst i will See what i can Do about this. It would have to work even if someone installed it to custom paths though

**Comment by Davst** [comment]
@kosace that's why fetching the install location from the add remove programs uninstall location in the registry should cover those cases as well. Would also be a good feature to default the file dialogue to filter on the file type. In this case .txt just for completionism.
