### ISSUE TITLE
Forbidden Error

### ISSUE THREAD

**Issue by GonkGonkCyclone** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#115]
Running app as admin and poe as admin, having a forbidden error, do i need to have the path of exile website whenever im using the application?
![CRA](https://user-images.githubusercontent.com/77868297/105566702-6f9f3080-5ce2-11eb-9254-2489d2875803.png)

**Comment by kosace** [comment]
login to the website -> get your session id -> close website

if you had version before 1.1.4 you should uninstall -> delete settings -> install new one

**Comment by c2ho2** [comment]
Where are these settings?

**Comment by kosace** [comment]
appdata/local/enhancepoe

**Comment by c2ho2** [comment]
Thanks!

**Comment by j-loriault** [comment]
I've done all this and also getting forbidden when trying to hit the refresh.

**Comment by bigb3204** [comment]
i've followed these steps as well and still getting the forbidden error

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
