### ISSUE TITLE
Rewrite using legal api?

### ISSUE THREAD

**Issue by TEXHIK** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#116]
Current version of the app getting information about your stash tabs via _website request_, and by doing this you are breaching 7.c and 7.f terms of use:
7. Restrictions: Under no circumstances, without the prior written approval of Grinding Gear Games, may you:
....
    c. Utilise **any automated software** or ‘bots’ in relation to your **access or use of the Website**, Materials or Services.
....
   f. Use any data gathering and extraction **tools or software to extract information from the Website** or utilize framing techniques to enclose any of the contents of the Website.

**Comment by kosace** [comment]
f.: the tool is not extracting information at all. the users are doing that themselves.

c.: if that counts for the APIs aswell it is not possible to legally use the APIs at all.

**Comment by kosace** [comment]
I mean, look, it says "Website, Materials or Service". That means ANY 3rd party tool is illegal from GGGs standpoint.

**Comment by TEXHIK** [comment]
> users are doing that themselves.
    Nope, it does. User get information is when you open the your stash on the site. Manually, via browser. This app is sending automated to the site, not to the api.

> c.: if that counts for the APIs aswell it is not possible to legally use the APIs at all.
   I think, it's made for trade at first, but yes, there is no change in terms for the api. At least this is oficcially done for programmed usage. And using the api, there is no longer need for website cookie, which is of course not secure at all.

P.S. App is cool, of course, great work!

**Comment by kosace** [comment]
well, i would say it is still an API though. paste this one in your browser:

https://www.pathofexile.com/character-window/get-stash-items?accountName=kosace&tabIndex=0&league=Standard

there is no difference from what you describe as API:

http://www.pathofexile.com/api/public-stash-tabs

in both cases you get JSON back. users that use that manually cannot do anything with that. in both cases you use the same domain. in both cases you send get requests.
