### ISSUE TITLE
After setting full set threshold to 99, due to trying to troubleshoot my previous issue with set detecting

### ISSUE THREAD

**Issue by Ranmaz** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#118]
![image](https://user-images.githubusercontent.com/77890976/105606602-a8c5b800-5d57-11eb-87c9-4309422f00d8.png)

_Originally posted by @Ranmaz in https://github.com/kosace/EnhancePoEApp/issues/66#issuecomment-766100186_

**Comment by Ranmaz** [comment]
did not correct when i reset my settings.

But fixed when I restarted the app.

**Comment by Ranmaz** [comment]
My issue with the sets not detecting still not working:

![image](https://user-images.githubusercontent.com/77890976/105606652-e62a4580-5d57-11eb-9ae3-f550be97b56c.png)

Full Set Threshold is set to 4

Even set to 1, doesn't work.

**Comment by kosace** [comment]
Hello okay the 99 tabs thing is interesting gonna Test that.

For the counting: acrivate fill greedy and fetch new

**Comment by kosace** [comment]
i could not replicate the error.

could you post a screen of your settings?
