### ISSUE TITLE
Incorrect Count numbers. 

### ISSUE THREAD

**Issue by Davst** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#119]
Running the Overlay, with 5 rings, all over 60 ilvl, the overlay displays 2 rings found. For some reason it isn't finding the other 3 rings.

Itemlevels are: 68, 69, 70, 70, 70

could this be due to that 3 of the rings are ilvl 70?

**Comment by kosace** [comment]
Activate fill greedy

**Comment by Davst** [comment]
have it active. now it works... just was staying that way through 3-4 maps which was odd.. might have been a issue on GGGs side of things.
