### ISSUE TITLE
Suggestion: Support for 20% Quality Recipes

### ISSUE THREAD

**Issue by WhiteFang5** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#12]
As per title, it would be nice if the tool could support 20% quality recipes.  
  
_**What/How would I expect it to work?**_  
When the "quality option" would be enabled, I'd expect it to work along side the non-quality option.  
Whenever a full set is complete, it would still work as-is.  
When a full set of quality gear (the minimum quality being a setting ranging from 1~20) is available, I'd expect a combination of the highest quality pieces being selected/highlighted.  
  
When creating a combination, it should take into account that 2 one-handers require 40 Whetstone's, where as 1 two-hander only requires 20; with this knowledge, combination of one-handers might prove to be cheaper than adding quality to a two-hander.  
It should also take into account that rings, amulets and belts don't require quality.  
  
Some nice to have would be the option to set how many non-quality armour pieces (or checkbox for non-quality weapons on/off) can be used, e.g. if it's set to 2, then 2 out of 4 pieces can be zero quality (i.e. you'd use the full 20 scraps on it to make it 20%)

_**Reasons/thoughts behind this suggestion**_  
I've been using a personalized chaos recipe filter for some leagues now, and I have specific filter options for quality items, with 15%+ showing up quite large and for any odd items you'd usually ignore for normal chaos recipes.  
I dump all quality items into their own tab. Once I get a full set, I sell it to the shop for 3 chaos (instead of the usual 2 for the unid recipe)

**Comment by kosace** [comment]
Hello,

never heard that someone is doing the quality recipe... Do you really think it is worth it? You could use your stash space for normal recipe also?

**Comment by WhiteFang5** [comment]
> Do you really think it is worth it?  

Early league the quality recipe is probably worth it, given that you pickup the scraps/whetstones. It's only a minor amount of effort (for me at least) to make them 20% quality and get that one extra chaos.  
  
> You could use your stash space for normal recipe also?  

Yeah, I sure could. I just have so many tabs available that I dedicate 3 quad-tabs to chaos recipes, two for normal ones, one for quality.  
If the tool would support quality recipes too, I'd be able to simply use 3 of them as dump-tabs and just throw all chaos recipe items (quality or not) in there.

**Comment by kosace** [comment]
okay i will think about it. the problem is you cant mix that with normal chaos recipe and then it would be that way, that quality items would always be shown. that means it shows you the stuff in your stash but lootfilter never changes the quality stuff.

**Comment by WhiteFang5** [comment]
> okay i will think about it. the problem is you cant mix that with normal chaos recipe and then it would be that way, that quality items would always be shown. that means it shows you the stuff in your stash but lootfilter never changes the quality stuff.

If you explicitly make the normal chaos recipe search/checking with 0% quality (i.e. exclude all items with quality), then you know how many full sets you got etc... the remaining (i.e. any items excessive of the X sets required) items could be used towards the quality chaos recipe (as part of the optional setting to use non-quality items to complete the quality recipe).  
(Or visa-versa, first check quality recipe, and then remove those items from the "all stashed items" list, and use the remaining items to check for the normal chaos recipe)
  
Filter-wise you simply have to put the Quality filter(s) prior to the normal filter(s).  
Example from my own filter:
```
Show 
Quality >= 15
ItemLevel >= 60
Rarity Rare
Class "Amulets" "Belts" "Body Armour" "Boots" "Bows" "Claws" "Daggers" "Gloves" "Helmets" "One Hand" "Quivers" "Rings" "Rune Dagger" "Sceptre" "Shields" "Staves" "Two Hand" "Wand" "Warstaves"
SetFontSize 45
SetBorderColor 255 190 0
SetBackgroundColor 100 100 255 255
ItemLevel <= 74
SetTextColor 0 0 255 255
```
This shows all iLvl 60~74 rares with quality +15% (or higher) in a specific color.

**Comment by WhiteFang5** [comment]
If you want to make it really fancy, you could also allow players to "choose" their currency tab (similar indication in settings as used for chaos recipe tabs), so you can count the amount of whetstones and scraps to see if a player could apply the missing quality for the quality recipe. (e.g. if you have 13/17/5/20 quality-armours and a 10% weapon, you could check if the player has at least `80 - 13 - 17 - 5 - 20 = 25` scraps and `20 - 10 = 10` whetstones)

**Comment by kosace** [comment]
yeah i mean, its a good idea, but a lot of work. 

i will consider it at least :)

**Comment by HiMarioLopez** [comment]
This is something I maaaaaaaay consider reviving when it comes to a hard mode environment (assuming it's as crazy limited with the drops as GGG states it will be). Until then, I will not be looking at this :(

**Comment by HiMarioLopez** [comment]
So for 'hard-mode' issues (i.e. Little payoff to the users and lots of effort for the devs) I'm going to close them up and if hard mode info comes out I'm going to re-visit each of the ones tagged under this. Thanks again for your ideas!
