### ISSUE TITLE
Improvement: Better ordering for the selection process.

### ISSUE THREAD

**Issue by Davst** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#120]
I'm not sure if this is possible. But it'd be nice if the item selection could be less erratic. now the order of items selected jumps around quite a lot. 

Since the API provides the x,y location it'd be nice to weight things by the Y first and then the X location.. this way if you had a set located on the first row id' pick all those items togther, moving downwards instead of going all over the place. 

Just looking att things that'd help make the selection process faster.

**Comment by kosace** [comment]
Hello there is a distance algorithm actually. It Has the disadvantage though that in each Set Has to be 1 Chaos item. That is something i cant change. 

Could you describe what exactly troubles you in the current state? Can try to improve it

**Comment by Davst** [comment]
Not sure what you mean by 1 chaos item.

Here is an example: 
https://i.imgur.com/ICs5zBR.png

Here I can see that the required items for a full set are available in the top few rows of the quad tab. instead the selection uses more mouse movement than necessary. 

It'd be nice if it'd scan per row or per column (doesn't matter if it is top to bottom or left to right really, to try to keep the items closer at least on one of the axis.

**Comment by kosace** [comment]
can you tell me the itemlevel of each marked item?

i will have a look into the algorithm soon. there are some limitations when it comes to filling the sets though

**Comment by Davst** [comment]
I'll do that next time I dump stuff.

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
