### ISSUE TITLE
Filter issue and suggestion

### ISSUE THREAD

**Issue by Desiz168** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#123]
First of all i love this tool, i bought a big inventory page for this. But with 1.2:

1. Filter issue, weapon highlight one-hand weapon instead of two
2. Doesnt recognize bow as two hand weapon

Suggestion to make life easier:
1. Highlight the whole set to sell as chaos instead of only 1 (so people can throw all "trash" into "trash-can"
2. if there is anyway to auto refresh the filter to reflect what actually need... that would be perfect.....

**Comment by HiMarioLopez** [comment]
Both were resolved in previous patches. Please open a new issue if you need anything else; thanks!
