### ISSUE TITLE
Experienced this error, no clue what it means

### ISSUE THREAD

**Issue by nrennstimpy** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#124]
![image](https://user-images.githubusercontent.com/51141673/105643305-ee5faf00-5e43-11eb-97bf-5b0554c5f00c.png)

After I acknowledged the error, the program crashed

**Comment by KornageGaming** [comment]
Yup, just got this too and now it doesn't get stash data anymore

**Comment by padmanek** [comment]
Just got the error too and it stopped working despite restart.

**Comment by kosace** [comment]
that means that the request got blocked...

**Comment by lav5-anvil** [comment]
I solved this by using a new session id, dont know how long it will work for though

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
