### ISSUE TITLE
Items are not greyed out after reaching threshold

### ISSUE THREAD

**Issue by nut-3** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#125]
Hello.
First of all, thanks for the tool.
I'm having an issue with set threshold. I set it to 6, so according to readme items that exceed this limit should be greyed out from the panel and disabled in filter. But as you can see in screenshot provided, it's not happening. The tool is still usable though.
![image](https://user-images.githubusercontent.com/6929041/105752187-0294d080-5f58-11eb-870d-f0aefa23e975.png)

**Comment by nut-3** [comment]
Version 1.2.0

**Comment by kosace** [comment]
are you sure every item is above ilvl 60?

**Comment by nut-3** [comment]
Every piece was found with your lootfilter, so yes. Looked through briefly all are 60-74.

**Comment by dot238** [comment]
I have the exact same issue
![screenshot](https://user-images.githubusercontent.com/6302193/106332558-56205a80-6287-11eb-8151-47b6cd6a0a9a.PNG)
Except for some reason body armor is grayed out.
I tried to set the limit to different values and checked the item levels.

**Comment by EdwoG** [comment]
> I have the exact same issue
> ![screenshot](https://user-images.githubusercontent.com/6302193/106332558-56205a80-6287-11eb-8151-47b6cd6a0a9a.PNG)
> Except for some reason body armor is grayed out.
> I tried to set the limit to different values and checked the item levels.

you should activate fill greed mode, that was it for me, hope it still helps

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
