### ISSUE TITLE
Subscribe to Loot Filters

### ISSUE THREAD

**Issue by Davst** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#126]
A feature that would be amazing would be if we could subscribe to loot filters via the app. 

One of the drawbacks of this app is that I have to go back to manually updating loot filters such as Neversink etc. If the app could poll a remote source.. either via PoE ui (best for flexibility) or direct on filterblade or such and then make its changes to a local version of that lootfilter it'd be much easier to keep up to date.

**Comment by Sykh** [comment]
You just reload them every time you completed a category or turned them in, using the online filter won't change that.

**Comment by HiMarioLopez** [comment]
Wish we could implement this, but it is simply impossible to do from a technical standpoint. We will revisit this in the future if GGG changes how their filter caching/loading from profile works.
