### ISSUE TITLE
Stash UI cannot be edited or move

### ISSUE THREAD

**Issue by PrinceDijinn** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#127]
Hi,

I just started using these and for some reasons, the STASH UI does not shows or does anything

Below is the image after I clicked on the Fetch, you can see there is nothing being counted.

![Chaos Recipe](https://user-images.githubusercontent.com/67146242/106342522-21b59a00-6299-11eb-9c99-a17cfcf548ea.JPG)
.

Regards,
Dinds

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
