### ISSUE TITLE
Unexpected Error Occurred: Dispatcher.UnhandledException

### ISSUE THREAD

**Issue by BlockchainBloke** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#128]
![Capture](https://user-images.githubusercontent.com/38803876/106342723-cf529880-62ed-11eb-9312-e67e05c507fe.JPG)

I get the above error when trying to show the stash overlay.

I've tried deleting settings from within AppData and through the app itself, uninstalling and re-installing v1.2 but the issue persists, can someone please help?

**Comment by Clumsy2015** [comment]
i have the same problems :/

**Comment by BlockchainBloke** [comment]
> i have the same problems :/

FYI I ended up do a system restart and the issue was resolved -_- so yeah have you turned it off and on again? haha

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
