### ISSUE TITLE
[Bug] [Filter Manipulation] New lines parsed / queried incorrectly if filter is edited by user manually after our app has modified it

### ISSUE THREAD

**Issue by p1xel8ted** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#129]
If there is any external edit (even just opening the filter and saving the file) with VS Code - the Chaos Recipe will append a new section to the top instead of replacing when you Fetch. If you don't touch the filter file at all, it seems to be OK. To clarify, it doesn't seem to matter if the app is open or not when you touch the filter in any way for this to occur.

Steps to reproduce:

1. Start with a fresh filter.
2. Setup filter to be used in Chaos Recipe Enhancer
3. Fetch
4. Open Filter in VS Code - **doesn't seem to do it if I use Notepad++ or Notepad**
5. Click Save
6. Fetch for a 2nd time. Doesn't matter if you opened or closed the app, the end result is the same.
7. Open Filter to find a second '#Chaos' section added to the top.

You can repeat this process to continually add a new section to the top. While not necessarily a bug, it's an oddity that is nice to be aware of, as VS Code has plugins for PoE Filter Syntax Highlighting, and probably gets used a bit by the community.

**Comment by JusKillmeQik** [comment]
This happens for me even if I use Notepad. The recipe section is always added at the top, which overrides the custom filter I want for jewelry.

**Comment by JusKillmeQik** [comment]
This issue is line 299 in FilterGeneration.cs:

string[] sep = { chaosEnd + nl };

You are searching for a newline after the chaosEnd pattern. The newline you are using is \n which is a linux newline, so anyone that saves the file using an editor that converts the newlines to a windows return will no longer meet your logic. I think you can just take out the newline as part of the search but if you need it there you'll need to search for \r too.

**Comment by HiMarioLopez** [comment]
> This issue is line 299 in FilterGeneration.cs:
> 
> string[] sep = { chaosEnd + nl };
> 
> You are searching for a newline after the chaosEnd pattern. The newline you are using is \n which is a linux newline, so anyone that saves the file using an editor that converts the newlines to a windows return will no longer meet your logic. I think you can just take out the newline as part of the search but if you need it there you'll need to search for \r too.

Good catch. When our filter manipulates the line endings using the '\n' notation, when in it could very well need to be a '\r\n'

https://stackoverflow.com/q/1552749/10072406

**Comment by HiMarioLopez** [comment]
Looks like we can replace all the new lines we use in the filter generation code to use https://docs.microsoft.com/en-us/dotnet/api/system.environment.newline?view=netframework-4.8

**Comment by HiMarioLopez** [comment]
Fixed by @yenbounger 's fix. Thank you for your help with this.

https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/458
