### ISSUE TITLE
Only changed lootfilter, does not detect items in stach or inventory.

### ISSUE THREAD

**Issue by TBroderick99** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#130]
My lootfilter items have changed their colors but nothing else seems to work. it also seems to detect my stash tab since when i click on highlight stash tab it shows the stash tabs name, but it doesn't detect items inside it or in inventory. I have tried fetching and it doesn't do anything.

![Path of Exile 31_01_2021 00_37_34](https://user-images.githubusercontent.com/67122757/106374042-14161800-635e-11eb-945a-3035c4ea020c.png)

![Screenshot (4)](https://user-images.githubusercontent.com/67122757/106374062-517aa580-635e-11eb-9b53-d5fc7e4e1721.png)

my settings:

![Chaos Recipe Enhancer Settings 31_01_2021 00_44_38](https://user-images.githubusercontent.com/67122757/106374045-16787200-635e-11eb-9ec3-939dc0ebc2c5.png)

**Comment by machtmann** [comment]
Same for me.

**Comment by shadowstorm7769** [comment]
I had this problem as well! If you are using steam to login and chrome as I was try using firefox to get your session id. Worked for me hope it does for you too.

**Comment by TBroderick99** [comment]
WOW! thanks alot shadow that actually worked!!!

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
