### ISSUE TITLE
[Enhancement] [Filter Manipulation] Individual item class threshold (for target farming specific slots)

### ISSUE THREAD

**Issue by XaocDIO** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#131]
Hi!
Can you add upper margin ItemLevel <75 for all item except jewellery?
Remove margin, if checked option "Regal Recipe" 

Example:
Show
	HasInfluence None
	Rarity Rare
	Identified False
	ItemLevel >= 60 
	ItemLevel < 75
	Sockets <= 5
	LinkedSockets <= 5
	Class Body Armours
	SetBackgroundColor 221 0 255 255
	SetFontSize 40
	SetTextColor 255 255 255 255
	SetBorderColor 0 0 0

**Comment by timeshifter** [comment]
Agreed, I continue collecting jewelry for the chaos recipe past 75, and sometimes bounce back down for some chill chaos collection. My tab is currently very full of higher ilvl jewelry, and it'd be great if this tool could count that as well.

**Comment by HiMarioLopez** [comment]
I'm going to take a bit of the idea and generalize it to a new feature that can have users select their preferred item classes to add this 'ceiling' to. This is to allow target farming of a specified item class, say, gloves, that they can hoard into higher item level maps where they pick up the rest of their gear set for the chaos recipe.

**Comment by HiMarioLopez** [comment]
Adding to this conversation (via Discord):

![image](https://user-images.githubusercontent.com/23390842/185406528-73684ab0-75eb-4eb6-bf88-6b3e91639f44.png)

Looks like having individual item class thresholds could be the direction this feature is going in?

**Comment by HiMarioLopez** [comment]
I went ahead and renamed this so the scope of the feature goes beyond a specific recipe (i.e. only making it available for the Regal recipe)

I'll continue to add to this as we flesh out what it would look like from a functional perspective.

**Comment by HiMarioLopez** [comment]
i'm going to close this as i've added a new flag that allows you to manually DISABLE item slots. i don't know if the individual threshold would make much sense after implementing this feature

so yeah check it out - the 'Always Disabled' flag will disable it from loot filter but also on set tracker thx

https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases/tag/3.25.0002-beta
