### ISSUE TITLE
Lootfilter edited in wrong location

### ISSUE THREAD

**Issue by Milkysunshine** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#134]
I tried adding the #Chaos Recipe Enhancer by kosace Chaos Recipe Start & #Chaos Recipe Enhancer by kosace Chaos Recipe End lines to the END of my lootfilter, as to not overwrite other rules. The app still insists on putting an additional set of lines and filter rules at the start of the lootfilter.

**Comment by Milkysunshine** [comment]
I found that completely closing the app, editing the loot filter with the key lines, and reloading the app re-reads the location in the loot filter, and sets it correctly.

**Comment by Milkysunshine** [comment]
Well it seems I was wrong. New day, still trying to add a second set of rules at the top of my lootfilter even though they already exist later in the file.

**Comment by p1xel8ted** [comment]
Same as https://github.com/kosace/EnhancePoEApp/issues/129

**Comment by Milkysunshine** [comment]
you are correct. I did a quick scan of titles and missed the correlation. Cheers.
