### ISSUE TITLE
Will Not Fetch Data

### ISSUE THREAD

**Issue by TheYeetler** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#136]
Whenever I try to fetch it gives a super long error code about the file location missing. Basically it's saying it cant find my loot filter but I selected the one I'm running and the filter itself works fine so I know I have the right location.
![Annotation 2021-02-16 154226](https://user-images.githubusercontent.com/79172466/108125083-95172400-706d-11eb-901b-9c92d8da2342.png)

**Comment by Sykh** [comment]
Open POE, go to UI, open folder, just copy where it leads you to.

I think the FilterBlade part at the end is incorrect

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
