### ISSUE TITLE
cant fetch elder item

### ISSUE THREAD

**Issue by ogurisan** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#137]
I have a lots of  elder influence identified item in the stash
when fetching is done, it shows zero set. cant count for exalted shard recipe but filter can still pick those item()
maybe its your setting problem, influenced item doesn't need any ilvl for exalted shard recipe, only need same influenced.
please check poe wiki
I tried regal recipe, it show 13rings so I am sure that my setting is right. actually fetch the data

**Comment by kosace** [comment]
will be fixed in next patch (this week)
