### ISSUE TITLE
6 full sets, but it says need lower level items why is that (do not close please)

### ISSUE THREAD

**Issue by GastonV** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#138]
![image](https://user-images.githubusercontent.com/10828511/108410071-3eede080-7227-11eb-8375-560117b9eea6.png)

**Comment by BDrizz307** [comment]
It seems like the upper bounds of the filter isn't preventing you from picking up higher level items than the 60-74 the chaos recipe requires.  I am having the same issue.  I have the chaos filter option set but its showing me ilvl 75+ items.... Seems like something isn't working correctly

**Comment by p1xel8ted** [comment]
Play with Fill Greedy Mode checkbox on the settings tab.

**Comment by ikogan** [comment]
I have the same issue and had considered the "Fill Greedy Mode" checkbox but the tooltip seems to suggest that it'll only allow you to pickup one low ilvl per set? Perhaps I'm reading it wrong, what is the checkbox supposed to do?

**Comment by GastonV** [comment]
Here is the greedy setting for it 
![image](https://user-images.githubusercontent.com/10828511/108920046-4b61a700-7634-11eb-86ec-0b147741eaeb.png)

And why it says closed when there is non solution found to problem ?

**Comment by GastonV** [comment]
> It seems like the upper bounds of the filter isn't preventing you from picking up higher level items than the 60-74 the chaos recipe requires. I am having the same issue. I have the chaos filter option set but its showing me ilvl 75+ items.... Seems like something isn't working correctly

I have 2 quad stash tabs with 78+ iLevel more of 80+ iLevels

**Comment by kosace** [comment]
I will look into that issue when i have time. Im very busy rn but will update/ fix bugs before next league for sure.

**Comment by ertanturan** [comment]
I'm also having the same issue here. Expecting a fix :(

**Comment by GastonV** [comment]
> > I'm also having the same issue here. Expecting a fix :(
> 
> All your items level will be ilvl75+ - you can sell them now but will get Regal Orbs. You need at least one item per set in the 60-74 ilvl range to receive chaos orbs instead.

Explanation above.
