### ISSUE TITLE
Belts not updated correctly in filter

### ISSUE THREAD

**Issue by PhileyJFry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#14]
Hi there,

first of all thanks for the great tool! It is especially useful for the early days in the league.

I encountered the following problem: Belts don't seem to be updated in the filter settings? Like I set the maximum no. of sets to 6 and have like 20 belts in my quad tab, and they're still showing up highlighted in maps.

And I also have a request: Would it be possible to make the filter show the highlighted items on the minimap or play a sound when they drop? I rarely press the buttom to show the items on the ground, so I miss a a lot of these I think.

Thx again and happy Christmas,
Philey

**Comment by kosace** [comment]
belts are always on. i will add the possiblitity to remove them in the future.

you have to activate lootfilter manipulation, then your lootfilter gets rewritten everytime some itemtype should hide.

**Comment by kosace** [comment]
and the sound thing: will probably add this in the future. that you can assign sound files to item classes. but will take some time :)

**Comment by HiMarioLopez** [comment]
Closing as we've since released a few fixes to the filter features, as well as sunsetting online filter manipulation (which may or may not have been causing this bug). If you have any other issues with our new v1.4.0 release please open a new issue. Thanks!
