### ISSUE TITLE
Tool not hiding items that have reached the limit

### ISSUE THREAD

**Issue by GinStGermain** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#140]
I really liked that the tool hid items when I had enough of them. I also really like having the counter on the minified version of it. 

I jumped from 1.1.3 to 1.2.0 and I didn't realize that you had removed the hide rules that were available in 1.1.3 is there a way to add them back? I don't mind doing it manually if you walk me through it. 

Previous post:
When I reach 16 of one item, for example Helms, when I reach 16 helms instead of hiding helms, the helms revert to the lootfilter color and I can still see them. I have used the tool before and when I reached 16 helms and I update the map, then I would not see helms anymore. Now what happens is that if I reach 16 helms, the helms revert to the lootfilter color instead of disappear: for example:
tool color for helms = blue
itemfilter color for helms = red
0-16 helms, helms are blue
16+ helms, helms are red, instead of not seeing helms

**Comment by Flincae** [comment]
To resolve this I just edited the original filter so that ilvl 60 to 74 rares are hidden using filterblade.

**Comment by kosace** [comment]
Yes that was changed in order to allow using your own lootfilter without interruption from the tool. Just use a stricter version for yourself :)
