### ISSUE TITLE
Refresh in Hideout

### ISSUE THREAD

**Issue by f0rdfair** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#141]
I cant seem to fetch (update item amounts) in Hideout, is this normal or is it a setting i missed. Fetching in maps is fine.

cheers

**Comment by kosace** [comment]
You have to fetch by manually pressing the button. The autofetch option only works in not-hideout-zones

**Comment by f0rdfair** [comment]
Hey, thanks for answering!

I have tried pressing the fetch button but it doesnt do anything, I tried standing in my hideout and pressing the button 3 times over ~2 mins, no refresh, but as soon as I entered a map it refreshes

**Comment by kosace** [comment]
Did you get an error on the first fetch? There is a bug where you cant fetch anymore after that (fixed in next patch)

**Comment by f0rdfair** [comment]
No error, the button goes grey and then the resets after a while, no refresh

**Comment by kosace** [comment]
That means the data ist stale probably. The reason why ive implemented the fetch on new map is that PoE servers refresh data when you enter a new zone. That means when the tool auto fetches on new map its almost guaranteed to have fresh data. But when you join your hideout that isnt the case usually.

Can you see the small little blue bar under the overlay when you press the fetch button?

**Comment by f0rdfair** [comment]
Yeah I see a moving blue bar

**Comment by kosace** [comment]
Okay then it is like i said probably. Cant change that since PoE servers deliver the data, I can only process what i get.

**Comment by f0rdfair** [comment]
Thanks for your Times!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
