### ISSUE TITLE
New POE API authorization

### ISSUE THREAD

**Issue by Spaghe81** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#142]
Hi mate, any plans to implement the new required authentication method required by GGG?

https://www.pathofexile.com/developer/docs/authorization

**Comment by kosace** [comment]
hmm im not sure what i need to do there. i will have a look into auth2.

" This means that any distributed application (one that runs on a user's machine) will need to be backed by a secure server in order to keep your application credentials secret. " 
thats a bummer at least

**Comment by Spaghe81** [comment]
Yeah I thought that could be a problem. Either way, thank you for your tool.

**Comment by kosace** [comment]
i have some bug fixes and improvements ready already, they will come no matter what. after that i will have to see if its worth the hassle to implement oauth2. in any case the code remains online so if anyone wants to build on that or use the algo or whatever they can do that
