### ISSUE TITLE
How to set lootfilter location  for followed filters?

### ISSUE THREAD

**Issue by Erythros** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#145]
All my filters are set using the PoE website "follow" option. Something like this
![image](https://user-images.githubusercontent.com/2624183/114382708-59906600-9b95-11eb-8b4c-af26838b4268.png)

Now, in the app, I need to set a "Loot filter location".
![image](https://user-images.githubusercontent.com/2624183/114382751-690faf00-9b95-11eb-9554-5c5d205489e7.png)

But obviously, I have no loot filter locally since all my filters are done via the official website.

Is there any solution for this?

**Comment by zyertdox** [comment]
I implemented what you are asking for, so when @kosace will review pull request #146 and merge and deploy it you will have possibility to work with online filters.

But even with these changes you need possibility to edit the script, so you cannot refer the script that you are following. You need to have your own instance of the script.

**Comment by kosace** [comment]
i will have a look into your pull but the main problem is the new authorization model from ggg. i am not sure if im going to implement that but if i do i will try to fit in online filter too :)

**Comment by zyertdox** [comment]
Hmm, and what is the new auth model? If you are talking about their public API I see there is [such functionality](https://www.pathofexile.com/developer/docs/reference#itemfilters)

**Comment by kosace** [comment]
they require oauth2 now.
you can read about it here: https://www.pathofexile.com/developer/docs/authorization.

the way i understand it is that i need to register the app, host a server with api, request keys from their servers, distribute keys to clients.

**Comment by Erythros** [comment]
I'm not sure how this affects the plugin, but [Neversink re-wrote the filters for 8.0](https://www.reddit.com/r/pathofexile/comments/mppx9x/lootfilter_neversinks_filter_80_update_public/).

**Comment by Davst** [comment]
> I implemented what you are asking for, so when @kosace will review pull request #146 and merge and deploy it you will have possibility to work with online filters.
> 
> But even with these changes you need possibility to edit the script, so you cannot refer the script that you are following. You need to have your own instance of the script.

Can't wait for this to be implemented!

**Comment by HiMarioLopez** [comment]
We cannot modify followed filters. Closing this up.
