### ISSUE TITLE
Best way to update?

### ISSUE THREAD

**Issue by Erythros** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#147]
What's the best way to update the addon?

By default, I would just clone to repo and run a `git pull` every now and then. But since it is mentioned now to do this, I was wondering how I can update without losing my settings every time.

**Comment by kosace** [comment]
Just download the latest setup.msi here: https://github.com/kosace/EnhancePoEApp/releases
But you can ofc pull the source code and build it yourself. Works too ;)

**Comment by adrian-uglean** [comment]
At least for me, every time I try to update this way nothing happens. 

I have 1.2.0 already installed, and when I run the 1.2.2 installer, it runs successfully, but when I open the app, I still have 1.2.0 installed 😢

**Comment by kosace** [comment]
Uninstall the old one first. I will implement auto updates in the future maybe.
