### ISSUE TITLE
I got a strange error fetching data it's just exception window that saying "Bad Request"

### ISSUE THREAD

**Issue by Gurin-Andrew** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#148]

**Comment by Gurin-Andrew** [comment]
![image](https://user-images.githubusercontent.com/75120747/114943453-36550780-9e70-11eb-9852-ae2f15bb1021.png)

**Comment by Gurin-Andrew** [comment]
![image](https://user-images.githubusercontent.com/75120747/114943493-45d45080-9e70-11eb-81a2-cd278ffaa485.png)
my settings 
![image](https://user-images.githubusercontent.com/75120747/114943541-54bb0300-9e70-11eb-9a05-cbf46dab666e.png)
and how stashtabs looks like

**Comment by kosace** [comment]
its "standard" ;)

**Comment by Gurin-Andrew** [comment]
> its "standard" ;)

LOL :D. Not my language. Thanks, now it works, hope it will also tomorrow

**Comment by kosace** [comment]
we will see. im not so sure
