### ISSUE TITLE
Open/Close overlay rapidly crashes the program + can't relaunch it

### ISSUE THREAD

**Issue by Drildgen** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#149]
Repro steps:

1. Launch Chaos Recipe Enhancer
2. Toggle Overlay with hotkey rapidly (may take a couple tries)
3. Observe software crash
4. Try to launch Chaos Recipe Enhancer again
5. Observe Error writing file: C:\Users\...\EnhancePoE.exe. Verify that you have access to that directory ![ChaosRecipeEnhancer](https://user-images.githubusercontent.com/82672094/115059936-3c210c00-9eb5-11eb-95ab-734fa28b682b.PNG)
6. Click on Cancel
7. Observe Fatal Error ![ChaosRecipeEnhancer2](https://user-images.githubusercontent.com/82672094/115060089-712d5e80-9eb5-11eb-9a5a-ec2bd9a839b7.PNG)

Maybe I am doing something wrong? :P

**Comment by Drildgen** [comment]
Rebooting the PC makes the software usable again -- I couldn't find anything lingering in my task manager

Repro rate 100%

**Comment by kosace** [comment]
thank you for the report. i will have a look into that soon and already have an idea why that is. There are many things calculated when opening the overlay which is not a very good idea but its how it is atm :D

**Comment by HiMarioLopez** [comment]
Like previously mentioned, this seems to be 'intended' in the sense that you gotta let the app load itself up a bit. I don't see any reasonable scenario where someone would want to open/close this so often.

Gonna close for now, let me know if we need to re-open this for whatever reason.
