### ISSUE TITLE
[Suggestion] Accessories Icon, and Others. 

### ISSUE THREAD

**Issue by maclanegamer** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#15]
**I'm here to suggest if possible:**
- Add accessories icons ( Example: Belt, Amulet, Ring);
- Option to make a certain Armor Piece/Accessory to be always visible, even if full sets;
- Option to change the Notification Sound to a custom one;
- Option to Add/Remove sounds into the Armor/Accessory drops;
- A slider to change the size of In-Game Overlay.

Thanks in advance, wonderful program, love using it!

**Comment by kosace** [comment]
hello, 

thanks for your suggestions, i will consider them in the next patch.

you can change the notfication sound to a custom one. replace the files in /users/username/appdata/roaming/chaosrecipeenhancer/sounds

**Comment by maclanegamer** [comment]
> hello,
> 
> thanks for your suggestions, i will consider them in the next patch.
> 
> you can change the notfication sound to a custom one. replace the files in /users/username/appdata/roaming/chaosrecipeenhancer/sounds

Thank you for the fast reply, I appreciate it, hope to see this app grow, best of luck 💯
