### ISSUE TITLE
Full sets aren't recognized

### ISSUE THREAD

**Issue by Scolecida** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#150]
Hi,

I have some issues with the application:

1. Full sets are not recognized. As you can see below I have a full set but the counter is still at 0. Therfore I cannot get the stashtab overlay to highlight the set to sell.
2. As you can see in my settings, I set my full set threshold to 1 so all item types should now be saturated and the filter should be updated but for me only the body armours are hidden.

![grafik](https://user-images.githubusercontent.com/82723590/115121046-ee89c980-9fb0-11eb-8072-1f7f969c43b3.png)

![grafik](https://user-images.githubusercontent.com/82723590/115120982-b2566900-9fb0-11eb-96d7-2794dcbaecc7.png)
![grafik](https://user-images.githubusercontent.com/82723590/115121201-a4edae80-9fb1-11eb-8c56-f8571081df58.png)

I hope you can fix these problems. Thanks for your awesome work.

**Comment by kosace** [comment]
Hello. Can you switch to the default overlay Mode and Check if there is a warning? The Problem is you have fill greedy inactive and too many low lvl items. Switch it on and it should count.

**Comment by Scolecida** [comment]
I could not see a warning when I switched to Overlay Mode but activating Fill Greedy Mode fixed the problems. Thanks
