### ISSUE TITLE
Programm always adds new section at the very top when it updates the filter file

### ISSUE THREAD

**Issue by ColdFaith** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#151]
Hey, 

i have the following problem. 
When the programm updates my ".filter" file, it always puts the "#Chaos Recipe Enhancer by kosace Chaos Recipe Start" section at the top. 
Even if i copy it to the line i would like it to be, in the next update the programm does not find the "#Chaos Recipe Enhancer by kosace Chaos Recipe Start" section and adds a new one at the very top of the filter. 

I have my filter file attached. My copied section is at line 3189.

Best regards :)
[Filter file.zip](https://github.com/kosace/EnhancePoEApp/files/6329846/Filter.file.zip)

**Comment by kosace** [comment]
Hello im Not AT home rn and can only Check later. Did you make sure that you also copied the end line? It needs both lines to recognize it otherwise it will ignore them

**Comment by ColdFaith** [comment]
Yes, i did copy all of the lines, the programm adds to the filter. 
I copied (for example) all of the following from the very top to the line i want it to be:

#Chaos Recipe Enhancer by kosace Chaos Recipe Start

Show
	HasInfluence None
	Rarity Rare
	Identified False
	ItemLevel >= 60
	Class Rings
	SetBackgroundColor 255 3 3 255
	SetFontSize 40
	SetTextColor 255 255 255 255
	SetBorderColor 0 0 0
	
Show
	HasInfluence None
	Rarity Rare
	Identified False
	ItemLevel >= 60
	Class Amulets
	SetBackgroundColor 255 3 3 255
	SetFontSize 40
	SetTextColor 255 255 255 255
	SetBorderColor 0 0 0
	
Show
	HasInfluence None
	Rarity Rare
	Identified False
	ItemLevel >= 60
	Class Belts
	SetBackgroundColor 255 255 0 255
	SetFontSize 40
	SetTextColor 255 255 255 255
	SetBorderColor 0 0 0
	
#Chaos Recipe Enhancer by kosace Chaos Recipe End

**Comment by bgsouto** [comment]
same issue here, always adding to the top of the filter file.

**Comment by kosace** [comment]
I just tested it and it seems to work. Make sure you also delete the lines at the top. It reads from top to bottom

**Comment by Codename-Rin** [comment]
Have the same issue, cut the lines from the top, pasted at the bottom, saved, updated item drops. Now I have tool lines top and bottom of the filter (updated are on top). Attaching my file after moving.
[ExpeSemi.zip](https://github.com/kosace/EnhancePoEApp/files/6889515/ExpeSemi.zip)

Edit: Seems to be an issue with text/code editors and their configuration. I had to tinker a little bit with VSCode (LF/CRLF formatting etc.) to make it work.

**Comment by Codename-Rin** [comment]
Seems to be an issue with text/code editors and their configuration. I had to tinker a little bit with VSCode (LF/CRLF formatting etc.) to make it work.

**Comment by HiMarioLopez** [comment]
As you mentioned @Codename-Rin  this could be an issue with the line-endings (UNIX vs Windows). Is this still an issue or are we ok to close this?

**Comment by Codename-Rin** [comment]
Yes, I worked it out with the line endings, seems fine now.
