### ISSUE TITLE
My Overlay is always at 0 count

### ISSUE THREAD

**Issue by carizzibr** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#152]
My overlay was working well in Ritual, but in Ultimatum its not. Every time I fetch (its fetching because I'm not receiveing any error), the overlay can't find anything. My stash tab for chaos recipe is number 1 (the second in game). 

I also tryed with no sucess: change the ID to prefix, renew the poe session

![Untitled-1](https://user-images.githubusercontent.com/82728914/115124570-4ddbdf80-9f99-11eb-87df-b025614e66fa.jpg)

**Comment by kosace** [comment]
The Maximum amount of Sets you can have is equal to your threshold. Set it to a hidher number

**Comment by LootLary** [comment]
have the same problem, my threshhold is 14 but it just gray out body armors and says there are no sets.
![image](https://user-images.githubusercontent.com/59345859/115478771-21e58600-a247-11eb-8e0d-bd67a04e29cc.png)

**Comment by eyriewow** [comment]
I am also experiencing the same issue. My full set threshold is set to 2 but the overlay is displaying 0 sets even though, as you can see in the overlay itself, I have a sufficient amount of every item on hand.

![](https://i.imgur.com/uwnL6cF.png)

/edit: it works now after reinstalling, deleting client.txt and deleting the settings in the app and starting fresh. No clue what exactly ended up fixing it but at least it works

**Comment by torsoreaper** [comment]
> /edit: it works now after reinstalling, deleting client.txt and deleting the settings in the app and starting fresh. No clue what exactly ended up fixing it but at least it works

Thanks for the help, I was able to resolve the counting issue by using your solution

**Comment by pekok0** [comment]
Im having this issue now with the latest version, but the solution above doesnt seem to fix it. My count is zero and so my stashtab overlay doesnt start showing items to pick.

What did you guys do exactly?

I uninstall the app, deleted client.exe in the pathofexile folder, created new blank Client.txt, reinstall the app, reset the settings and then set everything again. 

EDIT: It seems that having Greedy mode off is what causing this bug. Turn it on to fix this. It also explains why reseting everything works, provided you didnt uncheck greedy mode again after reset.
