### ISSUE TITLE
Cannot seem to get tool to work

### ISSUE THREAD

**Issue by Lunar2961** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#153]
Hi there mate, I followed a video on how to setup the chaos recipe tool & at first my overlay just didn't seem to be working, but now I am getting an exceptionally long error whenever I attempt to even run the overlay. The bottom of the error told me to report the error to GitHub, so now here I am. Thanks for making this awesome tool, even if it isn't working for me at the present moment!

Gyazo of the error: https://gyazo.com/fac7f554cc4460049670042c2b9c92ce

**Comment by hakfo** [comment]
update your .net version https://dotnet.microsoft.com/download/dotnet-framework

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
