### ISSUE TITLE
No stashtabs found

### ISSUE THREAD

**Issue by Davst** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#154]
This league I'm having issues with this tool, worked fine previous leagues, now i get the error "No stashtabs found..." in the overlay

Any idea how to fix this?

**Comment by PunkS7yle** [comment]
Your league name is not == `Ultimatum`

**Comment by HiMarioLopez** [comment]
Need more detail or issues like this. If you have any screenshots and your issue isn't fixed by our latest release, please post a new issue. Thanks!
