### ISSUE TITLE
Unexpected error ocurred : Dispatcher.UnhandledException

### ISSUE THREAD

**Issue by XxOriginzZ** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#155]
![image](https://user-images.githubusercontent.com/82760080/115144479-eb2b2800-a01a-11eb-9799-601fc3a327c7.png)

**Comment by XxOriginzZ** [comment]
Was working fine until like 30 mins ago, tried uninstalling and reinstalling.

**Comment by kosace** [comment]
Did you change your lootfiter? It says it cant find it

**Comment by XxOriginzZ** [comment]
I removed the others and added a new one

**Comment by XxOriginzZ** [comment]
I went in and selected the new filter but still get the same error
![image](https://user-images.githubusercontent.com/82760080/115245363-d91cb880-a0f2-11eb-9a50-08ab4100ac3f.png)

**Comment by hakfo** [comment]
are you sure that your lootfilter is called "Log File Chaos". Cause that sounds like a pretty weird name for a lootfilter. Can you check the name of your lootfilter for me?

**Comment by XxOriginzZ** [comment]
The name of my loot filter is something like strict no heist

**Comment by XxOriginzZ** [comment]
I'll send a screenshot when I get home from work

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by XxOriginzZ** [comment]
You can close
