### ISSUE TITLE
Issue with "Not found" when fetching 

### ISSUE THREAD

**Issue by enyce** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#156]
I am having an issue this league with "Not found" when trying to fetch, and my item numbers are not updating at all. 
![image](https://user-images.githubusercontent.com/21008777/115146189-be483680-a055-11eb-8b9f-3ffd9c5267ce.png)
![image](https://user-images.githubusercontent.com/21008777/115146205-cdc77f80-a055-11eb-9967-eb6c72d1ed9b.png)
These are the pics of setup.

**Comment by enyce** [comment]
Reminder: Maybe it is because I am on steam?

**Comment by kosace** [comment]
The account name has to be the same as the name on the Poe website (top left over your character)

**Comment by enyce** [comment]
Thanks alot! Such a minor change but crucial. I thought I needed my in game name...
