### ISSUE TITLE
App closing after launch

### ISSUE THREAD

**Issue by Fblfbl** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#157]
All previous files were deleted, reinstall didn't help. All I see is a white screen, then app closes.

**Comment by kosace** [comment]
Do you have Win10?

**Comment by Fblfbl** [comment]
> Do you have Win10?

Yep. I used version 1.1.7 Ritual, worked fine. But after update to 1.2.2 i used it only 1 time, it worked. Next day, after computer rebooting, i can see only white screen that closes after 1-3 sec.

**Comment by kosace** [comment]
strange thing.. try to delete your settings manually. its under users/username/appdata/local/enhancepoe.

**Comment by Fblfbl** [comment]
> enhancepoe

Did it yesterday, same thing.

**Comment by Fblfbl** [comment]
The problem was solved.  Need just to turn off rivatuner.

**Comment by kosace** [comment]
Thanks for that tip. Im gonna add that to the errors list
