### ISSUE TITLE
Crash when starting overlay

### ISSUE THREAD

**Issue by GamingChrislyBaer** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#158]
I just updated the App to 1.2.2. when starting i get the following error

I'm using an ultra wide screen (samung odyssey g9) 

![Unbenannt](https://user-images.githubusercontent.com/82772793/115154244-21e45b00-a07a-11eb-8bc4-871a9c85c67b.PNG)

**Comment by kosace** [comment]
you are not allowed to close the windows yourself (right click -> close). You have to use the buttons from the app. Ikr its not the best solution rn

**Comment by GamingChrislyBaer** [comment]
After a fresh restart of the pc, i started up everything.

when open the chaos recipe enhancer and click on Run Overlay i can see a second windows apppearing (on the taskbar), however i cant see it, there is nothing. 

I can stop the overlay without a problem but i cant get it to work.

**Comment by kosace** [comment]
okay then try to manually delete your settings file. its in users/username/appdata/local/enhancepoe

**Comment by GamingChrislyBaer** [comment]
That fixed it for me, i guess the minibar got lost because i switched to the ultra wide screen, thanks a lot =)
