### ISSUE TITLE
[Suggestion] Auto-Hide Overlay when POE isn't focused.

### ISSUE THREAD

**Issue by maclanegamer** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#16]
An option to hide the In-Game Overlay when Path of Exile isn't focused or minimized.
Sometimes it gets frustrating when doing anything else, like, searching for items on POE.TRADE because the Overlay is in the way.

**Comment by kosace** [comment]
Hello, 

very good idea, I dont know if thats easy to implement though. I will have to look into that. You can use Hotkeys in the meantime for fast closing.
