### ISSUE TITLE
Items keep dropping even after the threshold

### ISSUE THREAD

**Issue by heliopk** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#160]
items keep showing on the ground even after the threshold i set i keep refreshing the filter in the game, but it doesnt work, help please

**Comment by kosace** [comment]
Are the symbols greyed out? It switches back to your own filter

**Comment by ernviher** [comment]
I have the same issue. Here is screen
![filter](https://user-images.githubusercontent.com/82809905/115218644-10956000-a107-11eb-8173-8a8c2e95aa03.png)

**Comment by kosace** [comment]
And did you refresh your lootfilter ingame? You can upload the lootfilter to pastebin or so, then i can have a look

**Comment by ernviher** [comment]
Yes, lootfilter is refreshed and set correctly. Sending  more screens and pastebin with filter.

![image](https://user-images.githubusercontent.com/82809905/115222337-e9409200-a10a-11eb-9d7f-d2ed74b1abfc.png)

https://pastebin.pl/view/5e23d5d8
Hopefully it helps :)

**Comment by kosace** [comment]
Look in line 120-158 there are only 3 sections. These are rings, amus and belts. So the lootfilter is right you just have to refresh it ingame. If it deactivates it switches back to your own lootfilter

**Comment by heliopk** [comment]
i refresh the loot filter in game, i changed to another, refreshed it again, and still doesnt work...everything keeps dropping =/

**Comment by projectsix84** [comment]
I seem to be having the same issue. The script was working fine before but something is funky today. I have my full set threshhold to 12 and currently have 15 helms, 13 gloves, 14 boots.. and yet they're still showing on the ground. Its in the special colours of the script too, they aren't T1 armours shown by my regular filter or anything. I only have rings/amulets as 'always active'. I am refreshing my filter when entering new areas too but nothing seems to fix it.

Edit: So, I have 13 gloves, 14 boots, 15 helms, 17 body armours, 68 1h weapons, 6 rings, 7 amulets and 21 belts. Only the body armours are greyed out on my overlay. Everything else is showing on the ground despite my threshhold of 12. Also, I have 3 sets there to hand in.. but its showing a 0 for that.  Something is not working properly.

Edit 2: Fixed it somehow. I uninstalled the app, downloaded it again and installed fresh. I reset my settings (they seemed to save even after uninstall), and then re-entered everything the exact same as I had it before. I also noticed my client.txt file was 14mb or something, so I opened it and deleted all text and saved it. It's now working properly. Its counting my sets to hand in, greying out items when they hit the 12 cap I have, playing the sound for me to update filter ingame, etc..  all good. I have no idea which step I took is what ending up fixing it.

**Comment by gino-vi** [comment]
> Edit 2: Fixed it somehow. I uninstalled the app, downloaded it again and installed fresh. I reset my settings (they seemed to save even after uninstall), and then re-entered everything the exact same as I had it before. I also noticed my client.txt file was 14mb or something, so I opened it and deleted all text and saved it. It's now working properly. Its counting my sets to hand in, greying out items when they hit the 12 cap I have, playing the sound for me to update filter ingame, etc.. all good. I have no idea which step I took is what ending up fixing it.

I have the exact same issues happening to me, I did the same things but it didn't fix the issue.

**Comment by paulohvmatos** [comment]
I have the same issue.
After some digging I found out that Filter Manipulation is only adding "SHOW" conditions to the filter to highlight items but not adding the "HIDE" ones.
This means that if I don't want "Gloves" to appear, there should be a condition to hide "Gloves". If there is no condition to hide gloves, the game will pass through the Chaos Recipe Enhancer part of the filter and will then show the gloves based on the conditions found on the rest of the filter. 
In my case, Chaos Recipe Enhancer will still highlight the items that I need and the game will still show the items I don't need in a different color (whatever color I have configured in my base filter).

I solved my issue by adding the following statement to my filter after #Chaos Recipe Enhancer by kosace Chaos Recipe End

#Chaos Recipe Enhancer my BUGFIX START
Hide #Hides all unindentified rares between iLvl 60 and iLvl 74
HasInfluence None
Rarity Rare
Identified False
ItemLevel >= 60
Class == "Amulets" "Belts" "Rings" "Boots" "Gloves" "Body Armours" "Helmets" "Bows" "Claws" "Daggers" "One Hand Axes" "One Hand Maces" "One Hand Swords" "Rune Daggers" "Sceptres" "Staves" "Thrusting One Hand Swords" "Two Hand Axes" "Two Hand Maces" "Two Hand Swords" "Wands" "Warstaves" "Shields" "Quivers"
ItemLevel <= 74
#Chaos Recipe Enhancer my BUGFIX END

**Comment by HiMarioLopez** [comment]
Thanks for the details notes, y'all. We can re-open this if needed and fix in future patches.

For now, I'm closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
