### ISSUE TITLE
Unexpected error ocurred : Dispatcher.UnhandledException

### ISSUE THREAD

**Issue by AirCase** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#161]
I tried Admin and no Admin, even install it with cmd as admin as well and still the same issue... Added the app and folder to my Anti exception and firewall and still getting this problem.. such a bummer, man. Any way to get past this situation?

![2f44cff7ee6ecd5b86fe918cf35da239](https://user-images.githubusercontent.com/31215657/115434280-84eb0480-a1d6-11eb-993c-bc458607c4e4.png)

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Also gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
