### ISSUE TITLE
[Enhancement] [Installer] Sign .exe & .msi for seamless installation experience

### ISSUE THREAD

**Issue by DanielGKnudsen** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#163]
I would suggest signing the MSI. Also, someone is using Google AdWords to forward searches to other tools.

**Comment by HiMarioLopez** [comment]
Would loooooove to do this! I think it's more of a funding issue than anything. For now, we'll just have to work around it by having people accepting the security prompts.

**Comment by dyfrgi** [comment]
https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork From the readme of this project, it looks like signpath.io provides free signing for them. https://signpath.org/ is the site for their non-profit wing. From the editions page, looks like you have to email support to get set up. https://about.signpath.io/product/editions

**Comment by HiMarioLopez** [comment]
Done as a part of our latest v3.25.1001 Release:

https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases/tag/3.25.1001

![image](https://github.com/user-attachments/assets/79cd92cf-4b3b-4abe-a9eb-380af9fd77c2)

All future releases and installers will be signed. Thanks for your issue report
