### ISSUE TITLE
error fetching data: not found

### ISSUE THREAD

**Issue by matherith** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#164]
Whatever i tried i keep getting this error:

Error fetching data
Not found.

client.txt pathway is correct. 
lootfilter pathway is correct.
using 1.2.2

**Comment by matherith** [comment]
okay thank you. i was an idiot.

but now when i press fetch it goes grey and the overlay does not show me how many of what item i have. there are no numbers.

i've changed instances fyi.

**Comment by matherith** [comment]
thank you my good sir. it was a simple case of me being an idiot.

**Comment by hakfo** [comment]
glad it worked :)

**Comment by deflash-pixel** [comment]
> generate a new POEID and enter that in the application, also make sure that you are using the right account name. Also make sure that you are using a version >1.1.4

Maybe a stupid question but how do I create a new POEID?

**Comment by HiMarioLopez** [comment]
> > generate a new POEID and enter that in the application, also make sure that you are using the right account name. Also make sure that you are using a version >1.1.4
> 
> Maybe a stupid question but how do I create a new POEID?

To 're-generate' your PoE Session ID you can simply navigate back to pathofexile.com, clear your cookies, and once you've relogged simply go back to your cookies to get the ID.

![image](https://user-images.githubusercontent.com/23390842/152456008-fe988544-79a1-4504-a5ca-83a8f6e5b0e6.png)
