### ISSUE TITLE
Number of items required not populating when I hit S

### ISSUE THREAD

**Issue by SecretCrocodile** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#165]
![image](https://user-images.githubusercontent.com/82994706/115658264-53b12800-a2ed-11eb-869c-d6e67a943d53.png)

and 

![image](https://user-images.githubusercontent.com/82994706/115658287-6592cb00-a2ed-11eb-84cc-75f2c12dc6b0.png)

**Comment by matherith** [comment]
in the overlay tab, make sure "show item amounts" is not none.

**Comment by SecretCrocodile** [comment]
wow that seems to have fixed it! thank you!

**Comment by matherith** [comment]
glad it helped.

**Comment by gabrielstollagli** [comment]
This solved my problem too.
