### ISSUE TITLE
Clicking the "0" or stash button only brings up grid but does not count sets

### ISSUE THREAD

**Issue by SecretCrocodile** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#166]
![image](https://user-images.githubusercontent.com/82994706/115806982-9d0c8080-a39c-11eb-9d93-7785783923dc.png)

this is what it looks like when I click the 0 in the bottom left corner

these are my settings

![image](https://user-images.githubusercontent.com/82994706/115807040-b0b7e700-a39c-11eb-8759-546fb2bdc6d6.png)

![image](https://user-images.githubusercontent.com/82994706/115807064-ba414f00-a39c-11eb-9c70-8fe936e19d76.png)

Any ideas? Appreciate everyone's help.

**Comment by SecretCrocodile** [comment]
Had to reinstall, delete Client.txt and reset settings and it seems to work.

**Comment by mdemuria** [comment]
I am having the exact same problem you are, however reinstalling, deleting client.txt and resetting settings did not do anything. I even have it set to show how many more of each item I need, and it shows I have way more items then I need, but somehow 0 sets. Pic attatched to show settings.

![poe drop enhancer](https://user-images.githubusercontent.com/77870354/115967594-1d47f880-a4f9-11eb-8b4f-8b84dc2042ea.png)

**Comment by jkreczmer** [comment]
I'm also seeing the same issue, even after the above steps of reinstallation.  It will count items, but only grey out the chest slot when you go over the cap.  Due to this, it will not count completed sets, and not highlight in the stash overlay.

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by jkreczmer** [comment]
I think this was solved by a recent patch, as I was able to use it last
season. It can be closed. Thanks!
