### ISSUE TITLE
Influenced chests seem to be tagged as amulets

### ISSUE THREAD

**Issue by Davst** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#167]
![image](https://user-images.githubusercontent.com/3330933/115955070-c6d8bb00-a4f4-11eb-8297-1fab71898c60.png)

Including filter for reference (Neversink softcore economy Strict)

[NS-Softcore-Strict - Copy.filter.txt](https://github.com/kosace/EnhancePoEApp/files/6369364/NS-Softcore-Strict.-.Copy.filter.txt)

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
