### ISSUE TITLE
Have 60+ ilvl items in my stash but the tools doesn't see them

### ISSUE THREAD

**Issue by S-Mukha** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#168]
The tool shows all items type icons as if dont have the items. The .net is updated and i have no error messages of any kind.

**Comment by mp3tk0v** [comment]
Same issue here, not sure whats wrong

**Comment by bugzor** [comment]
Thirded

**Comment by happylittletree** [comment]
Same problem here.
No errors but 0 items found.

**Comment by moose627** [comment]
same issue for me also

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by S-Mukha** [comment]
All is working now.
