### ISSUE TITLE
Multiple windows - Windows stuck on moved window

### ISSUE THREAD

**Issue by mselberg** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#172]
Chaos Recipe Enhancer window is stuck on "wrong" screen when changing positions on multiple monitors.

How to replicate:
At least two monitors. 
Put one screen above the other. 
Move Chaos Recipe Enhancer window to top window. 
Change Screens to be beside each other
Chaos Recipe Enhancer window can't be accessed. Have to change screens to top/down and move down the window.

**Comment by 7e11** [comment]
I switched from a dual monitor setup to a single monitor, and this happens for me too.

From the steps here, method 2 worked for me:
https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4

**Comment by HiMarioLopez** [comment]
Duplicate Issue:

Please see this comment https://github.com/kosace/EnhancePoEApp/issues/267#issuecomment-1029335113
