### ISSUE TITLE
I can't install the app, after uninstalling the previous version

### ISSUE THREAD

**Issue by kleytondread** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#174]
I have the ritual version of the Chaos Enhancer. I saw there was a new version for this league, so I decided to uninstall the previous version to install the new one. I downloaded, and when I double-click the .msi file and click on execute, nothing happens. I tried to find the process the the app is running on the Windows Task Manager but no luck so for, I have tried to restart the pc after the uninstalling, but also no luck. Any ideias what could be ausing it to not install?

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

Also, for uninstalling absolutely everything, including 'lingering files' I like to recommend "Revo Uninstaller"

Let me know if you have any questions

**Comment by HiMarioLopez** [comment]
Closing due to stale issue. Please open a new issue if you're still having problems. Thanks!
