### ISSUE TITLE
[Enhancement] [Set Composition] Add option to include larger weapons (4x2) in our chaos recipe (e.g. "Space Saver" mode that can be toggled off)

### ISSUE THREAD

**Issue by AndreiTapai** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#175]
Noticed two handed weapons occupying 8 spaces are excluded from the filter. Picking up these bases for example from the end boss drops helps finish the weapon portion of sets quickly and should at least have a toggle or option to show them

**Comment by HiMarioLopez** [comment]
I can consider this! As someone with a gazillion quad tabs this wouldn't be the worst option. My only qualm is revisiting some of the logic we have in our distance algorithm for picking items from the stash.

I'll mark this as low-priority for now.

**Comment by HiMarioLopez** [comment]
Looking to add this ahead of 3.25. Thanks for your feature request and patience! Will update when it's in.

**Comment by HiMarioLopez** [comment]
added options to toggle space saving features for loot filter manipulation; you can now include larger weapons and even shields

![image](https://github.com/user-attachments/assets/4980d38e-f36e-4272-b780-8bfdc3485a97)

https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/commit/c6a9485958c14bdacf27f001b6e42ec98c4d4861
