### ISSUE TITLE
Suggestion: option to show currencies you're running low on

### ISSUE THREAD

**Issue by z0w13** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#176]
Would be nice to also have a feature to scrape a currency stash tab and show/highlight currencies the player is low on, especially for us that can't be bothered to deal with trade as much.

**Comment by HiMarioLopez** [comment]
I appreciate the suggestion, just think it's a bit ouf of the scope of our app at the time being. We may revisit this in the future.
