### ISSUE TITLE
feature request: optimization

### ISSUE THREAD

**Issue by 3r1u5** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#177]
can you change it or add an option to only show 3 tall 1 wide weapons. it will show me bows which I don't want to pick up and I don't need it to show me bows, its more efficient to use single handed weapons for a chaos recipe. I realize come people might use bows for the recipe that is why an option to do this might be useful. also when I'm in an area level 80 it still shows the gear on my filter, but the chaos recipe range is ilvl 60-74, I've tried it with even ilvl 75 items and it doesn't accept the recipe it gives a bunch of random currency instead. I know for the exalted shard recipe ilvl doesn't matter too much, I've tried editing the lines that it adds to the filter but it always shows ilvl above 60 even if its too high and re-adds bows to the filter. if this could be added it would be greatly appreciated. its an amazing tool and its helped in organizing a lot.

**Comment by paulohvmatos** [comment]
In regards to bows I used to think just like you until I realised that you don't need to pair bows with a quiver for the recipe to work so... Picking up a 3x2 Bow is as efficient as picking up two 3x1 weapons, in fact is more efficient because you only need to click once ;)

**Comment by 3r1u5** [comment]
yeah I have realized that since my last post, thanks for the tip :). so not so much of an issue with bows anymore, would still like the ilvl to be more accurate depending on which recipe the tool is set to look for. chaos is 60-74, regal is 75-100, which is a bit more work having to check the ilvl to make sure the recipe will work. but other than that its a great tool.
