### ISSUE TITLE
Turning off rings and amulets doesnt appear to work.

### ISSUE THREAD

**Issue by sclient** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#178]
I have collected a crapton of them as I was doing heists, and when I disable the option to always show rings and amulets, it seems to ignore that setting (despite having plenty of both in the stash tab, and every other item type working fine).

**Comment by HiMarioLopez** [comment]
Howdy! We've made tons of bug fixes and updates to the app since you posted. If you are still seeing this issue let me know and we can investigate further. If not, we can close this issue.
