### ISSUE TITLE
Don't include high ilvl influenced bases with fill greedy mode on

### ISSUE THREAD

**Issue by dovry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#179]
Some high ilvl bases are worth far more than what you'd get if you vendored them for 2c with fill greedy mode on.

#18 maybe related

**Comment by therber2** [comment]
I have the opposite problem.
No matter what I do, I can't get the program to ever recognize any influenced items.

**Comment by dovry** [comment]
idk if you've tried messing with the settings, but here are mine that work just fine.
![image](https://user-images.githubusercontent.com/15201298/120620812-a12cc300-c45d-11eb-8552-e69b75d7ec9b.png)

**Comment by HiMarioLopez** [comment]
Little out of the scope of this app. It is possible with a ton of work, but I just can't see us putting in the time for this. Contributions are always accepted for stuff like this.

Thanks!

**Comment by dovry** [comment]
I think you may have gotten distracted by the price thing. Isn’t this easy to fix with a toggle of ‘[ ] include influenced items’ and a line in the filter ‘influenced yes/no’ ?
