### ISSUE TITLE
Suggestion for Enhancement to Not Hide Influenced Items

### ISSUE THREAD

**Issue by bschalk** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#18]
Thank you very much for this tool, it is extremely helpful.  However, I noticed that when I am full on a chaos recipe item, gloves for example, it will then hide all unid'd gloves.  This is intended for normal items, but I would like the option to prevent the hiding of influenced items, and instead rely on the source filter for that.  I believe you can simply add the "HasInfluence None" line to each of the items that you are hiding to achieve this, and it will then only hide non-influenced items.  I believe the current setup is hiding influenced items in an unintended fashion when the chaos recipe tab has enough of that item base type to meet the threshold of the sets in the configuration.

**Comment by kosace** [comment]
hello,

i can try that, but not sure if hasinfluence none is valid in itemfilters. if thats valid ill add it

**Comment by kosace** [comment]
seems to work. will be added in 1.1.1

**Comment by bschalk** [comment]
Awesome, thank you very much.  Keep up the great work, this tool is really nice!

**Comment by kosace** [comment]
is fixed
