### ISSUE TITLE
Is Exalted Shard Mode working?

### ISSUE THREAD

**Issue by therber2** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#180]
It looks like in the update notes, you guys have gotten the ex shard recipe working, but I'm having some trouble.

I know I have influenced items in the tabs I've input.
I know I've inputted the tab numbers and poesessid, league, etc all correctly because this works beautifully for me for both the chaos recipe as well as the regal recipe.....just not for the exalted shard recipe.

When I attempt to run this for the ex shard, the quantities show all zeros for each item type and I know that isn't true.
Note:  Under the 'Overlays' tab, I DO / did make sure 'Total Items' is the selected option for 'Show item amounts' which always seems to correctly count number of chaos and regal recipe items by category correctly.

I also checked the header of my lootfilter file.
Am I doing something wrong or is ex shard not set up yet?

Thanks! Been loving the program.

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
