### ISSUE TITLE
How to fix 0 amount on each item, when full stash?

### ISSUE THREAD

**Issue by igorekrodi** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#182]
![69iA5el](https://user-images.githubusercontent.com/59632969/126858920-61c058b1-14d8-4de1-ac17-5a2f70e2887e.png)

Already did reinst, reset settings, deleted client.txt.

**Comment by null77** [comment]
Having the same problem. Might be something to do with the expedition patch?

**Comment by Streidominating** [comment]
Same issue, tried updating to 1.2.2 as well but didn't help, maybe the stash indices have changed?

Hopefully this can be fixed asap

Is it just the counts that are broken? It still detects it as a quad stash tab

**Comment by Ralle911** [comment]
Im having the same issue. It does seem to find the stash tab though. If you put in a stashtabprefix that doesnt exists you do get an error message and since you dont get the error message when you put in the correct thing I would assume it atleast gets the names of the stash tabs.

**Comment by bugforppl** [comment]
![image](https://user-images.githubusercontent.com/87899507/126866943-be1d4bea-eb14-4772-a216-3360af82e7d9.png)
1 item from request (https://www.pathofexile.com/character-window/get-stash-items?accountName={accName}&tabs=1&league={league})
`{"verified":false,"w":2,"h":2,"icon":"https:\/\/web.poecdn.com\/gen\/image\/WzI1LDE0LHsiZiI6IjJESXRlbXMvQXJtb3Vycy9IZWxtZXRzL0hlbG1ldFN0cjgiLCJ3IjoyLCJoIjoyLCJzY2FsZSI6MX1d\/8bd91531d0\/HelmetStr8.png","league":"Expedition","id":"5b68535f3f4ffcc366f67597ef91dd60325100733811947d3fd126c6a2de7142","sockets":[{"group":0,"attr":"S","sColour":"R"},{"group":0,"attr":"S","sColour":"R"}],"name":"","typeLine":"Samnite Helmet","baseType":"Samnite Helmet","identified":false,"ilvl":62,"properties":[{"name":"Armour","values":[["276",0]],"displayMode":0,"type":16}],"requirements":[{"name":"Strength","values":[["114",0]],"displayMode":1}],"frameType":2,"x":6,"y":0,"inventoryId":"Stash1","socketedItems":[]}`
Code:
`private static string GetItemClass(Item item)
        {
            List<string> iconParts = new List<string>(item.icon.Split('/'));
            String itemClass = iconParts[6];
            switch (itemClass)  
            {
                case "Weapons":
                case "Armours":
                    itemClass = iconParts[7];
                    break;
                case "Rings":
                case "Amulets":
                case "Belts":
                    break;
                default:
                    return null;
            }
            return itemClass;
        }`
Unfortunately, I am unable to resolve this issue.

**Comment by MarkWHodgson** [comment]
Just commenting that I am having the same issue. Thank you.

**Comment by Pantera3370** [comment]
> Just commenting that I am having the same issue. Thank you.

me2

**Comment by kosace** [comment]
fixed in new version
