### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by igorekrodi** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#186]
![1111](https://user-images.githubusercontent.com/59632969/126877367-432df398-12d7-41cb-b24b-b5dbda6781b3.png)

**Comment by kaidman** [comment]
Don't use Online filter feature i had same issues.

**Comment by igorekrodi** [comment]
Thank you!

> Don't use Online filter feature i had same issues.
