### ISSUE TITLE
How to fix 0 amount on each item with Chaos Recipe Enhancer 1.2.3?

### ISSUE THREAD

**Issue by NnikK** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#189]
How to fix 0 amount on each item with Chaos Recipe Enhancer 1.2.3?
![FAIL](https://user-images.githubusercontent.com/1997465/126895934-36e5fa2a-260c-44f5-ac9e-bea735c37b4f.png)

**Comment by kosace** [comment]
go to overlays tab and switch "show item amounts" on to see the numbers of each class.
