### ISSUE TITLE
[Feature Request] Auto-Reload Item Filter on Changes

### ISSUE THREAD

**Issue by kxc0re** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#190]
We can now load an item filter with the chatcommand: 

```
/itemfilter [itemfilter name]
```

that way we could auto reload it after doing a change
getting the itemfilter name could be as cutting the .filter-extension from the filename

**Comment by kosace** [comment]
Im gonna Test that later. If that works i will implement that asap

**Comment by kosace** [comment]
When Im thinking about it, it may be illegal. Its probably kinda easy to implement but yeah. Not sure if that would be against ToS

**Comment by kxc0re** [comment]
it would be the same as the `/hideout` macro wouldnt it ?

**Comment by kosace** [comment]
Yes it would be the same, but the /hideout macro is against the ToS and against everything GGG said until now. Their rules is: only 1 button actions are allowed so no automation. Enter -> typing -> enter are at least 3 actions.

**Comment by kxc0re** [comment]
im pretty sure opening the chat and typing is no server action, hence no breaking of TOS

> **Is this app approved by GGG? Can I get banned for using it?**
> There are no approved apps created by community. If app complies with the game ToS, does one server action per button press and doesn’t interact with the game client itself (injecting into the process, changing the process memory aka cheats) it can be considered safe.
> If you get banned, the first action is to Contact Support

_( from: https://snosme.github.io/awakened-poe-trade/faq )_


also this should be a lot cleaner and leave a lot less room for user error 
(maybe it can be integrated as itemfilter refresh button on the ui ?)
```
1. save current clipboard content
2. build the "/itemfilter [filtername]" line and save it to clipboard

3. send "ENTER"
4. send "CTRL-V"
4. send "ENTER"

5. restore clipboard
```

**Comment by OfflineBrain** [comment]
It's about server actions. It is only 1 action - send a /commant to server.
That's why flasks macro forbidden. It's an action per each flask.

**Comment by HiMarioLopez** [comment]
Yeah, our stance on automating too much is pretty conservative at the moment. We want to er on the side of caution when it comes to these sorts of enhancements to not break ToS. 

We apologize, but we don't want to risk any of our users' accounts!

Thanks.
