### ISSUE TITLE
[Enhancement] [Overlays] Improved visibility for item counts in main overlay when items are full

### ISSUE THREAD

**Issue by Blekota2k** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#191]
Could we have slider for setting opacity for groups of items we already have enough to full set? When im using minifield mode its hard to see the numbers of these groups.

**Comment by HiMarioLopez** [comment]
I have made it so only the item icons are faded out and the text for their counters are NOT when you meet this threshold. I also bolded the font of the counters so it's _very slightly_ easier to read.

To be released in 3.25 patch later this week. https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/commit/629af6cfe48ff4c7d09daf075e4cf52d49fdfdf0

![ItemCountsNotHidden-Minified-SetTrackerOverlay](https://github.com/user-attachments/assets/89196a56-913a-4803-914e-85f719418b53)
![ItemCountsNotHidden-MinifiedVertical-SetTrackerOverlay](https://github.com/user-attachments/assets/b03fce19-14f3-4e8d-8c2b-f4d70e44aaf4)
![ItemCountsNotHidden-Standard-SetTrackerOverlay](https://github.com/user-attachments/assets/7bf61577-8ab7-4574-b4dc-bbc9a87dd704)
![ItemCountsNotHidden-StandardVertical-SetTrackerOverlay](https://github.com/user-attachments/assets/45ad6eb5-0f4e-49f1-83f2-58d880dc9a93)
