### ISSUE TITLE
Virus total Trojen notification

### ISSUE THREAD

**Issue by Sal82** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#193]
When scanned on virus total showing that it is infected with Trojan.Malware.300983.susgen

**Comment by kosace** [comment]
Hello,

could you provide more information about that? There is a tab with details.

**Comment by Sal82** [comment]
Sure, Direct link (https://www.virustotal.com/gui/file/ff0cb6c926a250ec2888c49f910f80dc762113f09b1f981a57d288822b86a89b/details) Not sure if it will work if not this is what is under Details:
Basic Properties
MD5	41d9549895a4d04672c15d429a9eb669
SHA-1	78f3b328472b73ad9df894e7495b10a0679b7392
SHA-256	ff0cb6c926a250ec2888c49f910f80dc762113f09b1f981a57d288822b86a89b
Vhash	295036551514b0a16fff715614b6
Authentihash	232774005d6954102f669d3bb5815caa6899550190ffb01c1073f435e0526553
Imphash	f34d5f2d4577ed6d9ceec516c1f5a744
SSDEEP	12288:B5vDVzHgSZRrFt4W4DOMRtgVwfHjMqATsPZqATs:zVzAalVVMRyyPl
TLSH	T1D9154F02D269F535E6A71E79F09B6A514FA0EC3755E8C28B245A3D6F38743C0E8F60C9
File type	Win32 EXE
Magic	PE32 executable for MS Windows (GUI) Intel 80386 Mono/.Net assembly
TrID	Generic CIL Executable (.NET, Mono, etc.) (69.1%)
TrID	Win64 Executable (generic) (9.9%)
TrID	Win32 Dynamic Link Library (generic) (6.2%)
TrID	Win16 NE executable (generic) (4.7%)
TrID	Win32 Executable (generic) (4.2%)
File size	894.00 KB (915456 bytes)
PEiD packer	.NET executable
History
Creation Time	2092-02-18 20:29:30
First Seen In The Wild	2021-07-24 15:47:52
First Submission	2021-07-24 15:23:54
Last Submission	2021-07-24 15:23:54
Last Analysis	2021-07-25 20:36:29
Names
EnhancePoE.exe
Signature Info
Signature Verification
 File is not signed
File Version Information
Copyright	Copyright © 2020
Product	EnhancePoE
Description	EnhancePoE
Original Name	EnhancePoE.exe
Internal Name	EnhancePoE.exe
File Version	1.0.0.0
X509 Certificates
null
VeriSign Time Stamping Service
Microsoft Root Authority
Microsoft Code Signing PCA
Microsoft Corporation
Portable Executable Info
.NET Details
Module Version Id	e3898cd4-ad09-4d01-8c44-44ddad832757
Header
Target Machine	Intel 386 or later processors and compatible processors
Compilation Timestamp	2092-02-18 20:29:30
Entry Point	853382
Contained Sections	3
Sections
Name	Virtual Address	Virtual Size	Raw Size	Entropy	MD5	Chi2
.text	8192	845196	845312	5.98	02505c67b1395e6dfd7e1ad08da1288e	19102850
.rsrc	860160	68692	69120	3.48	646f603ce124747493fce00b41c8a516	3547625.25
.reloc	933888	12	512	0.08	9f12d60ca9ca6a906df8289cd7f684b5	128522
Imports
mscoree.dll
Contained Resources By Type
RT_GROUP_ICON	1
RT_VERSION	1
RT_ICON	1
Contained Resources By Language
NEUTRAL	3
Contained Resources
SHA-256	File Type	Type	Language	Entropy	Chi2
517257343bee654c79da38912b566433e0593f0c862a14f0a12b54e16de6e766	Data	RT_ICON	NEUTRAL	3.46	3512697.25
cd0991dd595a1392452a8c7ccf089e73626bc6eed1fd3f54ee4c6aa7ffbaedba	ASCII text	RT_GROUP_ICON	NEUTRAL	1.98	1669.6
80dcfeadcd208dc0e339c9de8057719f666557d9518069842b1a70314d92726e	Data	RT_VERSION	NEUTRAL	3.25	68973.15
Dot Net Assembly
Common Language Runtime metadata version	1.1
CLR version	v4.0.30319
Assembly name	EnhancePoE.exe
Metadata header Relative Virtual Address	57456
Assembly flags	COMIMAGE_FLAGS_ILONLY, COMIMAGE_FLAGS_32BITREQUIRED
Entry point token	100663322
RVA entry point	139732
Resources va	713408
Strong name va	0
Streams
size	entropy	chi2	md5
#GUID	16	3.625	336	f1db19ed37a8c8bca75ac3392187f07c
#Blob	8328	5.718904972076416	70110.734375	998d34ee7e19e2db2a24d8b44d2795dd
#US	11876	3.7298855781555176	761822.6875	b203bfbc54496d63516b0ddb401fba64
#~	35036	5.801193714141846	851172.125	38522dae995aa8b4d8d852f44c78e88d
#Strings	26912	4.96888542175293	294604.78125	55eeb059716bd01b81ff5bc4a590a348
Manifest Resource
EnhancePoE.Properties.Resources.resources 
EnhancePoE.g.resources
External Assemblies
Xceed.Wpf.Toolkit v4.0.0.0 
System.Xaml v4.0.0.0 
PresentationCore v4.0.0.0 
mscorlib v4.0.0.0 
System.Net.Http v4.2.0.0 
WindowsBase v4.0.0.0 
HtmlAgilityPack v1.11.32.0 
System v4.0.0.0 
System.Drawing v4.0.0.0 
System.Windows.Forms v4.0.0.0
Type Definitions
System.Windows.Interop.WindowInteropHelper 
System.Windows.Threading.DispatcherUnhandledExceptionEventArgs 
System.Windows.Threading.DispatcherObject 
System.Windows.Threading.Dispatcher 
System.Windows.Threading.DispatcherUnhandledExceptionEventHandler 
System.Object 
System.Type 
System.Delegate 
System.ValueType 
System.Exception
External Modules
user32.dll 
kernel32.dll
Unmanaged Method List
kernel32.dll: GetModuleHandle 
user32.dll: SetWindowsHookEx, UnhookWindowsHookEx, CallNextHookEx, GetWindowLong, SetWindowLong

**Comment by kosace** [comment]
Yes the problem here is that the application is not signed by a trusted authority. You know it costs money to do so and i thought it was not worth it. You can see the exclamation mark next to "File is not signed". Some virus checkers dont like that. 
In the end it is an open-source project so you can download the source code and compile yourself. That way you can be sure that the app is not malicious (if you understand the code).
