### ISSUE TITLE
Bug with followed online filter

### ISSUE THREAD

**Issue by Davst** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#194]
![image](https://user-images.githubusercontent.com/3330933/126913057-1944bae2-3959-4454-924f-76ae65658542.png)

Added neversinks filter

**Comment by kosace** [comment]
That happens when you specified the wrong name. It will be fixed in next update. Make sure you copy the name of the lootfilter correctly

**Comment by Davst** [comment]
Checked spelling, same error. doing this on a FOLLOWED online filter.. might make a difference to the ones that are "mine"

**Comment by kosace** [comment]
Okay i have to test that. For me it works for the neversink online filters at least.

**Comment by kosace** [comment]
Yes the tool wont work with followed filters because it cant read or write them. I have added an exception and warning message in the newest version for that case
