### ISSUE TITLE
When i click the first piece, the overlay doesn't move on to the next piece

### ISSUE THREAD

**Issue by alqeren** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#195]
Hi there, when i try to sell my sets before the full set threshold i activate the overlay and its showing me the first piece but when i ctrl+click the first piece the overlay doesnt moving on to the other one. Is it because i dont have the full set threshold or am i doing smthng wrong?  I havent tried with full 5 sets (my threshold)

Thanks for the app btw, this is the first league i'm using and having a blast with it !!

**Comment by kosace** [comment]
Did you try with admin rights?

**Comment by PenKnight** [comment]
I think I have a similar issue. 
I found that I have to click in the upper left quadrant of any of the highlighted cell to make the overlay move onto the next piece.
it is like the hitbox was shrunk.

I am using a 4k screen which might the issue. When I was using a 1920x1080 screen, the script worked fine.

**Comment by omarbaf** [comment]
Same issue here, but I don't have a 4K screen.  Tried your suggestion of clicking on the upper left quadrant, but it didn't make any difference.

**Comment by LorenzoBatto** [comment]
The same happens to me. I haven't tried using admin rights though. I also moved to a bigger screen, though I keep using 1920x1080 because my graphics card can't handle bigger resolution.

**Comment by omarbaf** [comment]
I did try admin rights and made no difference.

**Comment by kosace** [comment]
do you have display scaling at 100%? it only works at 100% atm

**Comment by omarbaf** [comment]
I have it at 100%, same as I had for last league.  All settings are same as last league, which worked flawlessly.

**Comment by alqeren** [comment]
The solutioun for me was reinstalling and run as admin from the right-click properties panel. Thanks !!

**Comment by omarbaf** [comment]
Have done all that..  Set the display to 100%, uninstalled and reinstalled again, ran as administrator and it does not advance to next item.
If I change the mode to show the set, all the items do get highlighted, but no advancement to next item when in 'item by item' mode.

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
