### ISSUE TITLE
Full Set Threshold Not working in 1.2.3

### ISSUE THREAD

**Issue by timtrousdale** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#196]
It Doesn't recognize when you have reached the threshold for an item. This also affects loot filter changes as all items always show up.

**Comment by wakasm** [comment]
seems to happen for me as well.  Only Armors seems to reach the threshold, but even with enough for 15 sets right now, it never finds a full set and thus can't highlight the stash.

**Comment by timtrousdale** [comment]
I dug deeper and found that the update changed everything to always active, removing them resolved it. This is a non-issue, user error.
