### ISSUE TITLE
Full Set Threshold Not working in 1.2.3

### ISSUE THREAD

**Issue by wakasm** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#197]
There was another thread opened on this, but someone closed it.  

For some reason, only Armours (for me) close out when it reaches a threshold.  I've gone into the settings and turned everything off from "always active" and even with 30 boots, 30 gloves, etc, they still show up on the fetch bar and I am still at 0 sets, despite having many sets now.  

This causes the filters to never update and the stash/set feature to never work. 

I've tried closing, reopening, opening as admin, etc.

**Comment by wakasm** [comment]
![image](https://user-images.githubusercontent.com/734064/127099219-9b4e1c44-5088-4e60-baf9-59482deb9bc5.png)

Just commenting an example.   Account successfully fetches the stash.   Full Set Threshold is set to 10 atm (I've tried 1, 10, 15).  Always Actve - Rings - Amulets - Belts.   

I've been using since version 1.1.14, so not sure what the issue is.

**Comment by kosace** [comment]
Do you have fill greedy active? If not activate that.

**Comment by Partymancer** [comment]
I had the same issue and fill greedy mode fixed it.  Never ticked it back on  after disabling for end game last league.
