### ISSUE TITLE
No stashtabs found

### ISSUE THREAD

**Issue by joviix12** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#198]
Hello, I've been searching a lot on the internet, but after a good hour of research I decided to come and ask here.

I checked several times, my account name, my Session ID, the name of the stash, the name of the league, to fetch at several different times, to restart the game, I even deleted the settings and Enhancer several times. I also looked on the Discord, but nothing worked.

So... Yo, i need your help ! Please !

![image](https://user-images.githubusercontent.com/42441145/126971202-328b603f-cfcc-4050-99fb-7af29a0675ff.png)

**Comment by kosace** [comment]
Hey can you try with stash Index too? Also are you using the Accountname or the Charaktername?

**Comment by joviix12** [comment]
I've already tried it, but when in doubt I did it again x)
But nothing better :/
Yes ! my account name

![image](https://user-images.githubusercontent.com/42441145/126973980-42fc02ca-9d28-44f8-bd8c-85f2d0238b57.png)


![image](https://user-images.githubusercontent.com/42441145/126974019-1f6e1451-5289-4193-a22d-8e0160107daa.png)

**Comment by kosace** [comment]
Set the threshold top at least 1

**Comment by joviix12** [comment]
![image](https://user-images.githubusercontent.com/42441145/126975342-8cd56971-0a87-4d62-a1b8-ae511b736bdd.png)

**Comment by joviix12** [comment]
It doesn't make sense x)

**Comment by kosace** [comment]
look in "General" the first input "Full Set Threshold". Set it to 1 or higher

**Comment by joviix12** [comment]
OH sorry !
The same thing happens

![image](https://user-images.githubusercontent.com/42441145/127019448-d3d5f0ad-46e9-46a2-81cb-6f028954a838.png)


![image](https://user-images.githubusercontent.com/42441145/127019788-9d830f41-6c47-47b9-960b-aad46d53ade9.png)

**Comment by kosace** [comment]
I will message you on discord later when im at home. Its weird and i dont see an error atm

**Comment by joviix12** [comment]
Ok, I hope we can find it x)
I'm now curious to know where the problem could come from ^^

**Comment by joviix12** [comment]
I'm just the biggest idiot on the planet, I was logged into the wrong steam account, so it wasn't the right account name, nor the right PoE Session ID....

I'm so sorry Kosace. I' m so sorry Kosace, really, thanks for responding <3

**Comment by kosace** [comment]
haha okay. glad you solved it. I was a little confused what it could be? :D
