### ISSUE TITLE
Fetching Error: Bad Request

### ISSUE THREAD

**Issue by matherith** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#199]
i have no idea why it's happening. it just says "bad request" when i fetch data.

**Comment by bilkoh** [comment]
Same here
![image](https://user-images.githubusercontent.com/43228593/127071581-6fd43942-39d8-46b8-833e-b0c6f264b274.png)

**Comment by kosace** [comment]
Wrong accountname or league probably

**Comment by GoldenBroom** [comment]
same

**Comment by bilkoh** [comment]
Thanks for getting back to me.

Did I type the League name correctly on the screenshot? "Expedition" Right? The account name is correct, you can see here: https://www.pathofexile.com/account/view-profile/eris_is_free

**Comment by matherith** [comment]
yeah same here. my info is not wrong. i've updated session id multiple times by now. i've tried both ID and Prefix to fetch the tab.
unfortunately still not working, just says "bad request".

**Comment by kosace** [comment]
did you update to the newest version? if yes try to get a new poe session id.

**Comment by InspiredHeart** [comment]
> did you update to the newest version? if yes try to get a new poe session id.

Have same, the newest version, but nothing change, says "bad request"

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
