### ISSUE TITLE
Double Clicking is counter to user interface design standards

### ISSUE THREAD

**Issue by bjbeare** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#2]
The required double-click to set the function keys or to set the path to the filter is counter intuitive and contrary to user interface design standards. If you must keep it as a double-click... change the box text to reflect the required action.

**Comment by kosace** [comment]
Hello,
 thanks for feedback!

For ssf league in heist it should be "SSF Heist". Works for me, respond pls
if it doesn't for you.

The double click thing is really counter-intuitive you are right. The thing
is, this was my learning project for WPF and I did the Hotkeys at the
beginning and just didn't know how to change that.. I will look into it
next update :)

If you have more bugs or feedback you can also join the discord. It's a
little easier to write there. https://discord.gg/KgVsUdSSrR

Regards

Am Di., 15. Dez. 2020 um 17:14 Uhr schrieb Bruce j Beare <
notifications@github.com>:

**Comment by bjbeare** [comment]
I am playing SSF Standard. I think I tried that and it didn't work.

**Comment by bjbeare** [comment]
Ah... "SSF Standard" does, in fact, work.
Thanks. Probably should document that.

**Comment by kosace** [comment]
Will add that to github!

⁣BlueMail for Android herunterladen ​
