### ISSUE TITLE
[Suggestion] Auto-Updater

### ISSUE THREAD

**Issue by maclanegamer** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#20]
It seems no one has suggested this yet, so I'll leave it here.
An auto-updater for the program.
Also, it seems when I install new updates without uninstalling the old one first it doesn't get updated at all, still shows the old 1.0.9 version instead of the 1.1.0, I had to uninstall the old one first, then install the new update to show the right version.

**Comment by kosace** [comment]
I would need a ftp server for that, I dont think it is possible over github. 

So wont come anytime soon, since that costs money.
