### ISSUE TITLE
Overlay does not fetch items from stash

### ISSUE THREAD

**Issue by laukunas** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#200]
For some reason, the overlay does not fetch the item count from my stash. All numbers are 0. There are no errors and log file is empty.

The stash always used to be the first stash, so ID should be correct - 0. Account name, league name were copied from website to avoid misspellings (last league it worked fine). Just relogged in website and copied new session ID to make sure the issue is not there.

![image](https://user-images.githubusercontent.com/63304773/127122244-1c784907-a31f-4535-91e5-2476d4b54090.png)

Stash has items that were highlighted by the tool so it should fetch something:

![image](https://user-images.githubusercontent.com/63304773/127122745-a3799cf9-c968-475c-be5d-5954c31d9194.png)

**What has been done so far:**

- Tried launch the app as admin - no difference
- Reinstalled the app
- Checked through stash API link - the stash tab ID is correct
- Copied user ID and league name from website to avoid misspellings
- Re-logged in in website, copied new session ID
- Tried to use Prefix instead of ID - same issue

Any ideas what else might be wrong?

**Comment by kosace** [comment]
You have to update to the newest version. GGG broke the tool in Expedition.
