### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by TheOGinSC** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#201]
![image](https://user-images.githubusercontent.com/88037109/127152504-b5aec597-a06d-490f-8c72-f38f3636d195.png)

I get this error when I click on fetch.

**Comment by etaus** [comment]
Same

**Comment by TheOGinSC** [comment]
I saw where someone reset setting and entered again and I tried. It worked. Thanks
