### ISSUE TITLE
Exception when using on different account than the one that originally installed with

### ISSUE THREAD

**Issue by z0w13** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#202]
Steps to reproduce:
1. Install 
2. Switch to a different user account
3. Configure loot filter manipulation
4. Hit fetch
5. Exception occurs

![image](https://user-images.githubusercontent.com/50455229/127156218-3e42c4d2-a098-4377-8d16-3b875fd63db5.png)

It seems that there's files only created on install that are required by the app, maybe have these created on app launch instead?

**Comment by kosace** [comment]
it should work if you installed for all users. the reason there is this file is that you can change the styles of the highlighting yourself. but yeah i will think about just including them in the exe

**Comment by z0w13** [comment]
I'd suggest copying the files over if missing, or at least having a more friendly error message for it.
