### ISSUE TITLE
the tool cant fetch items from my stash tab

### ISSUE THREAD

**Issue by alaa777** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#204]
the tool cant fetch items from my stash tab
just hit mobs lvl 60 ++ and started putting items in my stash and the tool cant fetch from my stash V1.2.3

**Comment by fricotta** [comment]
Same here

EDIT: previous version 1.2.2 was not uninstalled, so I removed both 1.22 and 1.2.4 and then re-installed, launched the game and it is working again.

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
