### ISSUE TITLE
Item by item feature is not working

### ISSUE THREAD

**Issue by omarbaf** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#207]
Hi,

When I click on the first item highlighted, the highlight does not move to the next item.  I have tried both 1.2.3 and 1.2.4, and neither work.  Had no problem in the Ultimatum league.

Any ideas?

Thanks

**Comment by kosace** [comment]
Display scaling in windows at 100%?

**Comment by omarbaf** [comment]
yes, display is 100%, uninstalled and reinstalled again, ran as administrator and it does not advance to next item.
If I change the mode to show the set, all the items do get highlighted, but no advancement to next item when in 'item by item' mode.

**Comment by HiMarioLopez** [comment]
Howdy, is this issue still present on the most recent update, v1.4.0? If so, can you help me with some reproduction steps? And a quick screenshot of your settings wouldn't hurt!

If not, we can probably close this up.

**Comment by omarbaf** [comment]
Hi

I downloaded the newest version a couple days ago. At first it worked as expected, but the next day it stopped working and acted the same as previously reported.  It showed the first item and did not advance to the next item. 

I can send screenshots of my configuration and the screen if you still interested in resolving the issue. 

Send from my phone

**Comment by HiMarioLopez** [comment]
Have you tried to check the 'Fill Greedy' option, btw?

**Comment by omarbaf** [comment]
Yes I have the greedy option set. As I said, it worked for the few hours and I quit the program. The next day when I started it, it stopped working.  No settings was changed by me. Removing the app and reinstalling it didn’t make any difference. 

Send from my phone
