### ISSUE TITLE
Unauthorized Access Exception error - Still Present after following FAQ

### ISSUE THREAD

**Issue by Kataklysm83** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#209]
Getting the Unauthorized Access Exception error.

 I'm using version 1.2.4. these are the things I already tried to do to remedy the issue:
- My lootfilter is not read-only, also tested other filters with no read-only.
- Added the tool to trusted programs with my anti-virus. Also disabled my anti-virus to test, still get the error.
- Added the tool to my firewall as well.
- Uninstalled, deleted created folder at users/username/AppData/local/EnhancePoE

![image](https://user-images.githubusercontent.com/47700966/127497503-5ab45814-4dd4-4142-85d6-e4e855a13dfb.png)

**Comment by kosace** [comment]
did you test with admin rights too?

**Comment by Kataklysm83** [comment]
Yes, running in Admin

**Comment by Kataklysm83** [comment]
Update: Installed 1.2.5 and I get the same issue but notice its when I choose Lootfilter Manipulation. This is only preventing seeing loot with related colors to the item.

**Comment by arblaz01** [comment]
I am having this same issue. I have 1.2.6. I have tried everything I can think of. Triple checked my Account Name and Session ID. My lootfilter is a blank copy from filterblade. Running as admin, nothing is protected. I did get the same result that Kataklysm83 mentioned - when I turn off Lootfilter Manipulation, the error goes away. But that takes away a huge function of this program ... first time using it, would love to figure this out.

**Comment by HiMarioLopez** [comment]
Howdy,

Closing this issue as we've added multple bug fixes to loot filter manipulation and also removed online filter manipulation in its entirety due to many issues it has been causing and our inability to do real-time updates to online filters.

If you have any questions or have issues with our most recent release, please open a new issue.

Thanks!
