### ISSUE TITLE
Chaos recipe items not being detected for me

### ISSUE THREAD

**Issue by thebeast792** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#21]
I'm trying out the tool for the first time. Downloaded it and compiled. It doesn't seem to be picking up my items except maybe the body armours.

I think it's picking up the right stash tab because I checked the API and it showed the same one I'm looking at. I also enabled the option to see remove only tabs and they are no where near the front. I have the tab index set to "0". The stash tab name is unique (I think) and it seems to match up with the stash overlay where you align the stash slots.

I am sure that most, if not all, the items are within ilvl 60-74.

Is there debug logging for this? Might be a good idea to add an option in the config to enable debug logging. Can't tell what is wrong.

![image](https://user-images.githubusercontent.com/14367281/103145459-3c27b100-46f8-11eb-8855-95b12c0328db.png)

**Comment by kosace** [comment]
Hello,

make sure you have set your full set threshold. The standard value for quad tabs is pretty high. I guess I have to lower the standard values for each tab a little bit.

And no, there is no logging atm, you will have to write that yourself. I may add it in the future, but since most users dont know how to compile it and test it themselves, I dont think its worth it atm.

**Comment by thebeast792** [comment]
I have the full set threshold set to 2. The UI says "Sets 0" so it doesn't seem like it's finding any sets at all. I have more than enough for 3 sets or so.

The logging setting wouldn't need compiling. It could just be a value in the config file that you can set to true or false and the program would log or not depending on that setting. If you don't have time or don't want to, that's fine.

Here are my settings:
![image](https://user-images.githubusercontent.com/14367281/103154089-8b023480-4752-11eb-9ea9-acdc78bcd985.png)

**Comment by kosace** [comment]
Activate fill greedy. Otherwise it will only stick 1 low ilvl item in each set. When you have mostly low ilvl items no set will be filled

**Comment by thebeast792** [comment]
Ah, that makes sense now. I thought it worked a different way for some reason. Thank you!
