### ISSUE TITLE
LootFilter manipulation item on ground highlighting not working

### ISSUE THREAD

**Issue by Genhain** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#214]
tried using online, and local and resetting a few times and still no luck, is it a bug or am i doing something wrong?

Also as a follow up, is the UI number checking also supposed to take into account your current inventory to calculate if you have enough or is it purely stash based?

**Comment by kosace** [comment]
Did you refresh your lootfilter ingame?

No the inventory is not considered.

**Comment by Genhain** [comment]
i do believe i did, i loaded up the filter and the clicked the refresh button next to it in the menu

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
