### ISSUE TITLE
When Filter name is "FilterLoot"  it doesn't update

### ISSUE THREAD

**Issue by ahmedgaafer** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#216]
After troubleshooting for about 10 mins.

 I found out that when the filter name is "FilterLoot" - the default name for filterblade filters -  the filter won't change and the colors that I set doesn't work.

after  changing the filter name and refreshing the filter it worked

**Comment by HiMarioLopez** [comment]
Just tested this and the issue seems to have been resolved with one of our previous updates. Thank you for filing an issue! Let me know if you need anything else.
