### ISSUE TITLE
[Enhancement] [General] Allow resizing of main settings window

### ISSUE THREAD

**Issue by TheveninRDM** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#218]
The configuration window is currently displayed at a fixed size. The width of the window is fixed wider than 1080 pixels, causing it to run off the edge of many vertically oriented displays. This is a simple feature request to allow users to adjust the dimensions of the window.

**Comment by HiMarioLopez** [comment]
Major UI changes with dynamic sizing released in https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/485
