### ISSUE TITLE
Suggestion: Save Settings

### ISSUE THREAD

**Issue by CollinHerber** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#23]
Right now when closing the program, if you don't have minimize to try selected, your settings will be wiped and you will be forced to redo all of them.

Please save the settings so you don't have to re-configure the program everytime you load it up.

Maybe things like POE Session ID won't save, but at least the rest of the settings should.

**Comment by kosace** [comment]
Hello, 

this is a bug. I dont know how to fix that atm, since wpf behaves strangely in that regards. I will add a save button again in the next patch.

**Comment by kosace** [comment]
Added Save Button to make sure settings are saved correctly
