### ISSUE TITLE
Malwarebyte detection release 1.2.6

### ISSUE THREAD

**Issue by Moubai** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#234]
Detected has malware, MachineLearning/anomalous.95%

**Comment by kosace** [comment]
Hey,  do you have any more information about that? Usually there is some information given in these tools

**Comment by Moubai** [comment]
Export of log only showing this info 
-Détails du malware bloqué-
Fichier: 1
MachineLearning/Anomalous.95%, C:\Program Files (x86)\ChaosRecipeEnhancer\EnhancePoE.exe, En quarantaine, 0, 392687, 1.0.44048, , shuriken, , 80397D51D3AE4A0BD4716CF8F30385FC, 6CAE9C33644FC96CCF0441C05D3B1927190CE62DF89A6283A0160A4BEDC9CFAB

**Comment by kosace** [comment]
And in the earlier versions it didnt complain? I have to check that out. 

But in general: the application is not signed and some antivirus tools complain about that. It is a open-source app though so you can always compile the sourcecode yourself to be sure its not malicious.

**Comment by Moubai** [comment]
Neverget any quarantine with older version
i've autorised it for the moment
surely a false positive, it happens sometime

**Comment by dovry** [comment]
My guess is that it's the autoupdate feature

**Comment by HiMarioLopez** [comment]
I can confirm no fishy business or malicious intent with our program. I believe this  false-positive may be related to the way our auto-updater is currently built. Happy to have someone else comb through the code to validate these claims.

The way our auto-updater works will be changed at some point in the near future (before 3.18, but not for 3.17).  For now, I'm going to close this. Please re-open a new issue if you have any other questions. 

Thanks!
