### ISSUE TITLE
Add Folder Mode

### ISSUE THREAD

**Issue by Aradiv** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#236]
It would be nice to have a folder mode where you specify a folder and then all tabs in that folder get checked for the items.

This would allow to easily use standard tabs or add and remove tabs without the need to reconfigure the app every time.

As far as i understand it you can query the folder and get all Child Tabs via the Stashtab API:
https://www.pathofexile.com/developer/docs/reference#type-StashTab

**Comment by HiMarioLopez** [comment]
This is a good idea. I'm going to see if I can include this in a future version (eyeing this for v1.5)

Thanks!

**Comment by george-delchev** [comment]
I can take a look at this tomorrow if you haven't started it yet. Just add it so that StashTab prefix/suffix also looks at matching folders and adds all the stashes inside? Not sure if its possible with stash id, gotta check what the api returns.

**Comment by HiMarioLopez** [comment]
> I can take a look at this tomorrow if you haven't started it yet. Just add it so that StashTab prefix/suffix also looks at matching folders and adds all the stashes inside? Not sure if its possible with stash id, gotta check what the api returns.

Go for it! My work week has been a bit busy so haven't had too much time to look at these enhancements

**Comment by george-delchev** [comment]
Not possible currently. Need to use the API and not the character window/stash from the site, since that doesn't include folders. Probably hold it off until a rework of that is done.

**Comment by HiMarioLopez** [comment]
Closing for now. We'll revisit this at a later date, thanks for your research.
