### ISSUE TITLE
 Loot Filter highlighting not working properly

### ISSUE THREAD

**Issue by PCSorcerer** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#238]
Hello,

I use the Full Set Threshold set at 10 sets and even tho I have more then 10 pieces of each gear (gloves, boots, helmets ...) the filter keeps showing them as missing (and I am refreshing the filter). Except body armor, that one is working. As soon as I have 10 body armors in stash it stops showing them on the ground.

![image](https://user-images.githubusercontent.com/25296681/130810683-997c7a0b-45d5-45cd-88e5-404b78963d38.png)

**Comment by Partymancer** [comment]
I had this issue last league start and it was because "fill greedy" was not checked.
