### ISSUE TITLE
Stashtab Errors

### ISSUE THREAD

**Issue by StorMaestro** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#239]
So at first i was having the issue of it giving me the "no stashtabs found. fetch first." then when i go into the general setting and have it set as "ID" and the Indices set as "0, 1," i keep juggling these setting for either or prefix and putting either the ''0, 1'' or the ''chaos, 1". 
I have been trying to get this to work for a few hours now and ive even looked at the other issue reports to help me confirm my settings. Just want to get this to work. any help is appreciated. thank you in advance.
![kosace complaint pix](https://user-images.githubusercontent.com/89699903/131226658-3f602e09-9ddb-4dde-aad2-9112a7f34a8d.png)

**Comment by StorMaestro** [comment]
I now have it to where the overlay bar just says No StashTabs Found but the error code I get says Index needs to be a number but I am pretty sure that's what the 0, 1, is unless I'm writing it incorrectly. But i dont see how.

**Comment by alfaman09** [comment]
@StorMaestro  I had a similar issue and the root cause was that Windows Defender was preventing the system from correctly accessing and writing to the root folder. May check the debug to make sure there aren't any errors showing.

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
