### ISSUE TITLE
Suggestion: Add Contributing Section

### ISSUE THREAD

**Issue by CollinHerber** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#24]
Create a section in the readme on how to contribute to the project.
I'm sure there are plenty of software engineers, myself included, that would help with coding of this project. A contributing section is good for laying out the foundation for engineers to get their feet wet and how to run/test/etc.

**Comment by kosace** [comment]
Yeah i have to look into that. I dont have much experience with github and stuff.

Thanks for your feedback btw

**Comment by kosace** [comment]
I have the discord though, you can join it if you want.

**Comment by HiMarioLopez** [comment]
I'm going to make sure to prioritize this post league launch for 3.17. Thanks!

**Comment by HiMarioLopez** [comment]
I added some more guidelines to the latest version of the Contributing section in the README.md with some steps on getting started. Surprisingly straight forward, so it didn't end up being a novel, just a few solid points to follow. Let me know if you need me to add any other details to that section, thanks!

Note: The changes are in 'develop' at the time of writing (to pair with our latest pre-release). They'll be merged to 'master' in the next few days.

**Comment by CollinHerber** [comment]
> I added some more guidelines to the latest version of the Contributing section in the README.md with some steps on getting started. Surprisingly straight forward, so it didn't end up being a novel, just a few solid points to follow. Let me know if you need me to add any other details to that section, thanks!
> 
> Note: The changes are in 'develop' at the time of writing (to pair with our latest pre-release). They'll be merged to 'master' in the next few days.

Took some time to look it over. Looks great thank you.
