### ISSUE TITLE
Picking up Regal Orb Recipe even though I chose the Chaos Recipe

### ISSUE THREAD

**Issue by jerichojx** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#240]
When using the Overlay, the Lootfilter picks up items that are overleveled for the Chaos Recipe. So when I turn the sets in, it gives me Regal Orbs instead of Chaos Orbs

**Comment by SirPownzalot** [comment]
On the left of the overlay there is a "Stash" button. Click on it and the tool will highlight the items you should trade in. The behavior you are describing sounds like you are just picking whatever items you feel like from your stash tab, but the tool tells you to pick up several "regal orb" ilvl items and then put in 1 "chaos orb" ilvl item. That way you maximize the low ilvl items so you don't have to run low ilvl content forever.
