### ISSUE TITLE
Unexpected Error when fetching

### ISSUE THREAD

**Issue by TsT-wIaGoD** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#241]
This is the message I get, when trying to fetch data.

How to solve this?

![grafik](https://user-images.githubusercontent.com/90612069/133064474-415ff851-7d29-469e-b2a0-2aff13eac266.png)

Thanks
TsT

**Comment by Joseph7695** [comment]
+1

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Pleas re-open a new issue if you need anything else! Thanks for your report.
