### ISSUE TITLE
[Installer Improvements] Custom Install Location, Confirmation of Install, Shortcut Options

### ISSUE THREAD

**Issue by Afgan0r** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#243]
The problem occurs only in 1.2.6, 1.2.5 installs fine and works

No errors appear so i can't understand what cause the problem

I'm not use any antivirus 
Windows antivirus also fully disabled
Tried to run as administrator, no effort
Also tried to disable all programs in tray, no effort

Any ideas how to fix that or how I can see maybe a log or something like this so it will be possible understand the cause of the problem?

**Comment by Vara88** [comment]
For me it installed and closed like yours. Found out it automatically installs it on the c: drive. Can't change the folder where it installs.

**Comment by Afgan0r** [comment]
> For me it installed and closed like yours. Found out it automatically installs it on the c: drive. Can't change the folder where it installs.

Oh, you're right. That new installer looks super weird

**Comment by hoerlahu** [comment]
LOL - i just downloaded visual studio to compile from code... 

i got a feature request: popup to tell you it worked

**Comment by Hillgrove** [comment]
please allow for installation in another folder. I don't use C: for anything but my OS.

**Comment by HiMarioLopez** [comment]
Howdy, this is something I want to help change in the future. More installation options, and general better behavior by the installer.

I'll keep y'all updated on the status of this enhancement!

**Comment by HiMarioLopez** [comment]
Closed https://github.com/kosace/EnhancePoEApp/pull/371
