### ISSUE TITLE
The enhancer is not working

### ISSUE THREAD

**Issue by VanDex93** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#245]
whenever i click reset lootfilter...
this error came up
![Capture](https://user-images.githubusercontent.com/93041354/138557708-64056014-6b99-4465-b158-fc5a588be5ba.PNG)

**Comment by sclient** [comment]
Same error here.

**Comment by Essyer** [comment]
PR is ready https://github.com/kosace/EnhancePoEApp/pull/247
Until it's merged you can use https://github.com/Essyer/EnhancePoEApp/releases/tag/1.2.6.1

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
