### ISSUE TITLE
Full Set Threshold only working on Chest Armor

### ISSUE THREAD

**Issue by Sweetyeetus** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#248]
Only Chest Armors are filtered out when reaching the Full Set Threshold.
![image](https://user-images.githubusercontent.com/93079035/138591462-392edfea-4b14-488b-9635-f20e7306af8f.png)

**Comment by DevConFox** [comment]
Hi @Sweetyeetus ,
can you post your settings? Because I cannot confirm this as a general bug in particular:
![image](https://user-images.githubusercontent.com/93077838/138610634-9af2b150-77f7-4310-8a43-a143cd4db3b6.png)

What I did notice is, that 'Fetch on new Map' does not work  properly for me and I have to fetch manually to update the item filter thresholds.

**Comment by mariandiaconu452** [comment]
Hello,
I got the same issue like @Sweetyeetus .These are my settings:
![image](https://user-images.githubusercontent.com/60629577/138653915-3a1b2549-ef23-4f75-9170-f5fcf3018f4f.png)
![image](https://user-images.githubusercontent.com/60629577/138653953-38b27002-715e-463c-83b4-ad43f7370ff6.png)
![image](https://user-images.githubusercontent.com/60629577/138654008-59546ba3-f049-4f0a-84cd-eb598d3ce4f3.png)

**Comment by DevConFox** [comment]
Hi @mariandiaconu452 ,
does the thresholds - besides armor - update, if you fetch manually?

**Comment by Sweetyeetus** [comment]
Eyoo,

I fetch manually after every map, but the threshold only worked for the body armors.
Here are my settings.
Thanks for the help! <3

![image](https://user-images.githubusercontent.com/93079035/138693053-b0ddcf13-7e25-463b-8769-cd0b44fbe66d.png)
![image](https://user-images.githubusercontent.com/93079035/138693090-a42478a2-a8a4-4855-ab63-ef8d898915ac.png)
![image](https://user-images.githubusercontent.com/93079035/138693114-197a99df-908b-4e81-bcb4-6e93d8fd4f6c.png)


Edit: For some reason it's now working for my weapons but not the other things that hit the threshold of 8.
Resetting the settings didn't help and there's no updates available.
![image](https://user-images.githubusercontent.com/93079035/138693592-83ea0bfd-753e-403a-9378-91822bbcd21d.png)

Edit 2: 
![image](https://user-images.githubusercontent.com/93079035/138700630-0c7be091-64f2-47c0-b88e-23d914dadb42.png)
Looking better but I'd love to get rid of gloves, helmets and boots as well. D:

**Comment by Sweetyeetus** [comment]
Aight. It's because of the Fill Greedy Mode.
I don't really get it, but enabling "Fill Greedy Mode" made everything work like a charm and I'm still getting 2c per recipe. 
¯\_(ツ)_/¯
