### ISSUE TITLE
why i must update the ItemFilter and stop/Fetch the programm after every map?

### ISSUE THREAD

**Issue by nshaltern** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#25]
Hello...
i dont have a problem to stop/fetch the overlay after switch any location but update the ItemFilter to dont make much fun because i really dont know when i must do it.
1 overlay on fetch 
2 start and enter a map
3 update the item filter into the map
4 grab items and before i go out of the map i stop fetching
5 putt all items in the stash and close it.
6 start fetch and must wait 15 seconds to see a update what i must grab in the next map (15sec. is way to much in my opinion :)
7 start with point 2 after upgrade 

is there no way to automaticly this process?

**Comment by kosace** [comment]
Hello,

just leave it running, dont wait for it. 

You only have to refresh your lootfilter when you hear the sound playing.
