### ISSUE TITLE
Loot Filter Manipulation not working

### ISSUE THREAD

**Issue by smackdo** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#251]
Loot filter manipulation is no longer working after the scourge league update, despite working prior to update and the rest of the features working. Loot filter has been reloaded many times, and I've reinstalled the app to try and fix.
Thank you for any help!

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
