### ISSUE TITLE
Reloading filter is sending the latest clipboard contents

### ISSUE THREAD

**Issue by BlueChimera** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#252]
When I click the R to refresh/reload filter after a scan for completion changes, it will sometimes send other commands, like I messaged someone for an item earlier, and it has messaged them 3 times so far, thankfully they are offline and I am not bothering them.
(Update)
it just happened again, so it seems the clipboard contents are being reused when calling the function to reload the filter.
added screenshot of exception

![EnhancePoE_MeEADwl9Y2](https://user-images.githubusercontent.com/16711569/138755907-73f17eeb-819f-4e8b-93da-64409f0a4603.png)

**Comment by bbseal** [comment]
Same here.  I don't get the exception window, it just dumps the contents of the clipboard to local or trade chat.

**Comment by AAAAaaa-ship-it** [comment]
Same here, the content of the clipboard is dumped in game after pushing reload filter.

**Comment by bbseal** [comment]
Just in case it helps new users of this tool, you can reload the filter manually from the in-game options.  The reload action from the tool isn't doing anything special, it's just a shortcut.

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
