### ISSUE TITLE
Settings window not showing up on Windows 11

### ISSUE THREAD

**Issue by Unknown-Guy** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#254]
After upgrade to Windows 11, the app opens, but there is no settings windows, just app icon on taskbar. Tray works - can exit app.

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by LukusLive** [comment]
can confirm i'm using Win 11 and v1.3.0 and above is working ok for me.

**Comment by HiMarioLopez** [comment]
Please check out our v1.3.1 release with fixes to the filter modification for weapons! Thanks!

**Comment by Unknown-Guy** [comment]
Still the same issue for me. Hovering on icon just shows up black.

![image](https://user-images.githubusercontent.com/640231/152498480-06d9b710-e4f3-46e3-be8d-bfb550fd4065.png)

**Comment by Unknown-Guy** [comment]
This should be reopened. Still same issue. 1.25 works. All later versions not working, same issue as in picture above.

**Comment by HiMarioLopez** [comment]
Are you an admin user on your PC? Any oddities going on with your display scaling (is it set to 100%)? @Unknown-Guy

**Comment by Unknown-Guy** [comment]
Yes, admin user. Will check later, might be 125% for 1440p monitor, will test if 100% changes anything but it's not an issue on older versions. 

As someone mentioned that 1.2.4 worked, I tested with that today, the settings window shows up fine. Did not test if in-game overlay is fine though.  Then tried 1.2.5. - still fine. Then tried 1.2.6. and with this one the issue appears and is the same in all later versions.

I have 2 monitors, 1440p and 1080p, think back then tried with just single one and nothing changed but will retest this.

**Comment by HiMarioLopez** [comment]
Sadly not an issue on older versions =/= we will support the exact same functionality as with older versions.

If you could do me a favor and test in 100% Display Scaling to see if that fixes it, that would be great!

**Comment by Unknown-Guy** [comment]
Single 1080p monitor, 100% scaling - main settings window not showing up. Just icon in task bar same as in picture above.

**Comment by Unknown-Guy** [comment]
So downloaded latest Visual Studio, cloned repo, hit run and works fine.

**Comment by HiMarioLopez** [comment]
Ok so that leads me to believe there's an updated dependency I don't have listed in the install steps. 

More likely than not .NET Framework 4.7.2 Runtime (And in our next release, .NET Framework 4.8 Runtime since I updated to the newer version in our app's v1.5.0)

**Comment by HiMarioLopez** [comment]
Closing this out, if anyone has a different issue where installing the .NET Framework 4.7.2 Runtime doesn't resolve it, please open a new one and we'll track accordingly.

https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472

**Comment by Unknown-Guy** [comment]
Tested with 125% scaling on 1440p and still fine. In game overlay also fine after resizing the grid, recipe shows up fine, clicking found sets also OK.

I have 4.8 which satisfies dependencies I guess, judging from this:
```
PS C:\Users\Unknown_Guy> Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name version -EA 0 | Where { $_.PSChildName -Match '^(?!S)\p{L}'} | Select PSChildName, version

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04161
Full                             4.8.04161
Client                           4.0.0.0
```

Let me know if you need anything else.

**Comment by HiMarioLopez** [comment]
Perfect. I'll make sure to have folks install that version of the runtime moving forward, given it covers our bases for the older framework version. Thanks a ton for the clarification!
