### ISSUE TITLE
Enhancer not manipulating filter

### ISSUE THREAD

**Issue by lonezeig420** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#255]
A friend recently downloaded and cannot seem to get it to work, it wont edit his filters to show the items. I have walked him through the steps to get it to work, like it does on my pc, but it wont on his.

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Pleas re-open a new issue if you need anything else! Thanks for your report.
