### ISSUE TITLE
Items are not fetching

### ISSUE THREAD

**Issue by ekampos** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#256]
Hi
For some reason the tool is not fetching any item. 
I click on Fetch and nothing happens. I map and collect the items, droped in the stash tab 0, and nothing happens, I open a new map and do the same thing, and still noting happens. I try Heist, and the same.
The filter works fine, the configuration seems to be right as well...
I try different tabs, in different positions but nothing works.
Can you give me a hand on this?  
Thank you very

![1](https://user-images.githubusercontent.com/5678029/139100411-65b093d9-3c71-47ec-920f-efcd07bbcbd7.jpg)
![2](https://user-images.githubusercontent.com/5678029/139100413-5f1b9092-cc78-419b-b7f1-c4707942f374.jpg)
![3](https://user-images.githubusercontent.com/5678029/139100417-85450a6a-e767-4985-ab3d-bffcb06f4f7f.jpg)
![4](https://user-images.githubusercontent.com/5678029/139100419-f1c64b02-c32b-4317-b5f8-53cb75ebf026.jpg)
![5](https://user-images.githubusercontent.com/5678029/139100406-93e61c5b-f2f0-46fc-9776-79e22c1cedc0.jpg)

**Comment by jpwalsh1** [comment]
Same issue here.

**Comment by Chris2Schill** [comment]
This happened to me. I reset the settings and tried again and its working.

**Comment by ekampos** [comment]
> This happened to me. I reset the settings and tried again and its working.

This doesnt work for me, I try to reset settings and reinstall the app, and still same issue

**Comment by HiMarioLopez** [comment]
Howdy, we just released a new version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by Poeticstuff** [comment]
I'm experiencing the same issue, though now I'm playing on Arch Nemesis and not Scourge.

 Running on 1.3.2.0 and the app doesn't seem to be collecting info from my stashes. Worked perfectly the night before Arch Nemesis launched when I tested it, but now it doesn't seem to work.

**Comment by HiMarioLopez** [comment]
Can someone re-test this to see if it's still an issue? My gut feeling says there was insane server load on the stash API on GGG's side of things and our app was not handling it well enough. 

Something I need to work on is reporting GGG-side errors on the app to the client so we know if it's them or us.

**Comment by HiMarioLopez** [comment]
Closing due to stale...

My recommendations for issues like this are (try one at a time):

1) Try a new PoE Session ID
2) Reset Settings
3) Reinstall Application
