### ISSUE TITLE
The loot filter stopped working

### ISSUE THREAD

**Issue by ernviher** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#258]
As in the title, everything was fine but i started to see this:
![image](https://user-images.githubusercontent.com/82809905/139506104-9899413c-f886-4a8c-8fb7-738f5c17506a.png)

Everything was working fine, then i wanted to reload filter and this info started to appear

**Comment by cw-1988** [comment]
same here

**Comment by anarchisticlees** [comment]
mine works but it doesn't show the colors I set up, it just shows regular filter's settings instead. nobody bothered to answer my problem. I wouldn't be surprised if nobody bothers to answer yours either

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
