### ISSUE TITLE
Filter manipulation doesnt work 

### ISSUE THREAD

**Issue by XenosTec** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#259]
It doenst work for items beside Rings, Amuletts and Belts somehow
<img width="1915" alt="1-min (1)" src="https://user-images.githubusercontent.com/40244746/139536529-38ebe2db-b789-4048-b5b1-85abfa516248.PNG">

**Comment by anarchisticlees** [comment]
I am having the EXACT same problem. Its not even showing the right colors for the rings

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
