### ISSUE TITLE
[Enhancement] [General] Allow for copying error window contents (maybe even add a "Click to Copy Exception" button)

### ISSUE THREAD

**Issue by Davst** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#264]
I get an exception every now and then which you want me to report on github. 

the message is very long and not copyable. So I mean.. I'm not copying all of that by hand so could you make the messages selectable?

**Comment by HiMarioLopez** [comment]
This is something I'm going to be working on for v1.5.0 to help make issue reporting a much easier thing for y'all. Thanks for your issue report!

**Comment by george-delchev** [comment]
You can currently copy the errors by pressing "ctr-c" while the error window is focused. You just can't select specific parts of it.
We can change the message to explain this better for now and/or add **Yes**,**No** buttons that copy the text or straight up send an email with the exception on **Yes**.

**Comment by HiMarioLopez** [comment]
Changed the tags on the wrong issue. Woops. And yes, I totally agree. Another thing I would want to include as a part of this error reporting enhancement feature is adding some logs users have access to in case we need more info.

**Comment by HiMarioLopez** [comment]
So technically we can do this already. by clicking the error window and simply doing a "CTRL + C". It will copy the contents for easy pasting.

Related commit: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/e5ba392961372c70cb78001262a4a8a1a9785c3c
