### ISSUE TITLE
Able to change the Pick Order.

### ISSUE THREAD

**Issue by NOTFreedom** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#265]
Hello, 

I propose the idea to change the pick up order when putting them in the inventory, like Body Armour->Helmet->Glove->Boots->Weapons->Accessories.
In my case, he will be more fluid since i got 3 stashs for doing chaos recipe, (Armour, Weapons, Accessories).
Just an idea for min-max the App.

(Or if you can tell me how to change the pick order in the current version, that would be cool)

Have a nice day.

**Comment by dovry** [comment]
Show entire sets and pick whatever order you want. If you want to do two recipes at once just pick the big items first

**Comment by HiMarioLopez** [comment]
> Show entire sets and pick whatever order you want. If you want to do two recipes at once just pick the big items first

This is a solid work-around.

The proposed feature is gonna take a bit too much time to figure out. I think the work-around for your specific scenario would be good enough to suffice if someone wants to do that.
