### ISSUE TITLE
Color overlay not working in lootfilter for POE

### ISSUE THREAD

**Issue by anarchisticlees** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#266]
My loot filter works fine, but the color overlay I chose suddenly stopped working after I played in Path of Exile's endless delve event in Scourge league. I currently use the loot filter from FilterBlade. The chaos enhancer now uses the filter's default instead of the customized overlay colors from Enhancer I set.

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Pleas re-open a new issue if you need anything else! Thanks for your report.
