### ISSUE TITLE
Overlay stuck in another monitor

### ISSUE THREAD

**Issue by llucioo** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#267]
I had a 2 monitor setup with the overlay on the secondary monitor, but it died and now it seems the overlay remained in the ghost monitor. I tried right clicking on the taskbar and telling it to snap left, right, go in a new desktop, but it didn't work. I also tried the move and the resize options, the cursor tries to snap to the overlay window, but it is bound to the single monitor, so it can't catch the window border. I guess I'll be able to resolve it when I buy a second monitor again, but it's unusable atm
![bug_report](https://user-images.githubusercontent.com/29893439/145991801-c8043a76-b3ee-45a4-b32b-5f948c16fd09.png)
![bug_report_2](https://user-images.githubusercontent.com/29893439/145991951-9b4eeb8a-04bd-483a-a318-516beabca566.png)
.

**Comment by muhlisatac** [comment]
same here

**Comment by muhlisatac** [comment]
Right-click a blank area of the task-bar, then select “Cascade windows“. This solution worked for me.

**Comment by HiMarioLopez** [comment]
@llucioo Did @scorpion86 's solution work for you? So we can close the issue.

**Comment by dovry** [comment]
common windows issue, not program related. Might as well close 

https://support.ti.davidson.edu/hc/en-us/articles/115016089728-Move-an-Application-Window-From-Off-screen-Back-to-Your-Main-Desktop-Windows
