### ISSUE TITLE
wrong class

### ISSUE THREAD

**Issue by acidh0uze97** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#269]
maybe sm1 has same problem? 
![image](https://user-images.githubusercontent.com/63073221/152450294-ceef55c1-0e16-4415-b39c-11365a6c2de5.png)
only in new 1.3 version, 1.2.6 works fine
@[HiMarioLopez](https://github.com/kosace/EnhancePoEApp/commits?author=HiMarioLopez)

**Comment by acidh0uze97** [comment]
i think ev1 should have this problem in 1.3 vers idk why nobody cares

**Comment by HiMarioLopez** [comment]
Thanks for bringing this to my attention. I do care! I should have the fix published by tonight.

**Comment by acidh0uze97** [comment]
> Thanks for bringing this to my attention. I do care! I should have the fix published by tonight.

thx

**Comment by acidh0uze97** [comment]
same with onehandweapons

**Comment by LukusLive** [comment]
Hey fyi to get user going until fix; i'm using local filter and updated the classes "OneHandWeapon" to "One Hand" and "TwoHandWeapon" to "Two Hand"
and it's now working. 
These are inside the filter you specify at lines 22 and 33 respectively.

**Comment by HiMarioLopez** [comment]
Just fixed both 1 and 2 hander class issues with filters. Please open a new issue if you find anything else wrong with the app please!!! Thank you
