### ISSUE TITLE
Fetch on new map bug

### ISSUE THREAD

**Issue by deswild** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#270]
the feature made it impossible to click "Run Overlay" 
An error message kept popping up "Please add log file location" regardless if I added a loot filter from windows or my online loot filter.
Once I unchecked it, then it worked I thought id report on the bug, thanks for updating this wonderful 3rd party app :D

**Comment by HiMarioLopez** [comment]
Can you drop a few screenshots of your settings? As well as of the issue you're seeing?

Having a bit of trouble understand the problem here, sorry.

**Comment by catinsock** [comment]
@deswild It's possible you have the wrong path to your log file which is different from the location under the lootfilter tab. The log file location refers to a Client.txt file which is needed for the fetch on new map feature.

Note the the location of client.txt is at **Path of Exile\logs\client.txt** and the default location of that will depend on if you installed via GGG's launcher (program files/grinding gear games) or Steam (steamapps/common).

**Comment by HiMarioLopez** [comment]
@deswild Was that the fix, adding the Client.txt file? If so, I can close this up.

**Comment by HiMarioLopez** [comment]
Closing under the assumption that the previous answer fixed it.
