### ISSUE TITLE
Not showing full sets

### ISSUE THREAD

**Issue by gwntd541** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#277]
Full sets appear zero. Armor piece info bar displays more then enough individual pieces.

Quad tab, followed by 3 normal tabs. Multiple item in tabs that are not equipment. I.e. cards currency ,essence.

Full set threshold adjustment from 0 to 10 did not change anything. Is there certain restrictions on things that can pollute the stash besides equipment?

**Comment by Pro7ech** [comment]
Same issue here, the stash is properly fetched (the overlay shows the correct stash) but only body armor are counted and the rest is ignored.

**Comment by chancii** [comment]
I had the same and clicked on reset settings (there is a button for that) and re-entered all my settings and it now works ;)

**Comment by LeiRaion** [comment]
I am having the same issue. No idea what could be causing it...
Only the body armor slot is updating. All other pieces are continuing to count up and up forever. 
I currently have 3 sets available for turn in for example and it shows 0 sets. My threshold is set to 10 but chests are dark on the overlay and off the filter....
While Gloves are at 16 and still on it and lit up on the overlay.. same with boots at 13 and helms at 21, weapons at 23... all still lit up on the overlay and still on the loot filter.
"always active" is not checked for any of these. 

options I'm using are here: https://imgur.com/a/gIKUgGX
Using the reset button did not work for me.


EDIT: I found out why the reset button works for some people --- "Fill Greedy Mode" if you leave this on for some reason the app goes back to working as expected.

**Comment by HiMarioLopez** [comment]
> I am having the same issue. No idea what could be causing it... Only the body armor slot is updating. All other pieces are continuing to count up and up forever. I currently have 3 sets available for turn in for example and it shows 0 sets. My threshold is set to 10 but chests are dark on the overlay and off the filter.... While Gloves are at 16 and still on it and lit up on the overlay.. same with boots at 13 and helms at 21, weapons at 23... all still lit up on the overlay and still on the loot filter. "always active" is not checked for any of these.
> 
> options I'm using are here: https://imgur.com/a/gIKUgGX Using the reset button did not work for me.
> 
> EDIT: I found out why the reset button works for some people --- "Fill Greedy Mode" if you leave this on for some reason the app goes back to working as expected.

This has been the go-to “fix” for a lot of things. Still not 1,000% sure why, to be completely honest. I am still learning a lot about this code base 😅

@gwntd541 did either of the potential solutions fix your issue? So I can close this issue. I have multiple duplicates that report the same, or a very similar bug.

**Comment by gwntd541** [comment]
the fill-greedy mode did the trick. Is there an ilvl lookup that is bugging out mb?

**Comment by Pro7ech** [comment]
Same here, resetting and enabling fill-greedy did the trick too

**Comment by HiMarioLopez** [comment]
Thanks everyone, hoping to have this fixed Soon™️

Wish we could do it sooner but given the circumstances we basically had to put out a beta for this league since I'm still new to the project haha. I'll do better next time.
