### ISSUE TITLE
Pressing Left Control while settings window is open causes an exception and crash

### ISSUE THREAD

**Issue by wowee999** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#278]
![image](https://user-images.githubusercontent.com/98685396/152639938-c88e9521-0164-4e5b-9d52-4bde8d22e13e.png)

**Comment by wowee999** [comment]
This happens even when the settings window does not have focus

**Comment by wowee999** [comment]
Seems this only happens after setting at least one of the keybinds to some combination containing control

**Comment by HiMarioLopez** [comment]
What OS version are you using?

**Comment by natfubar** [comment]
Me too. I'm on Win11.

**Comment by HiMarioLopez** [comment]
Gonna try to replicate this and start debugging the issue this weekend. Thanks for your reports! Hopefully I come back with some good news.

**Comment by HiMarioLopez** [comment]
Fixed in https://github.com/kosace/EnhancePoEApp/pull/360
