### ISSUE TITLE
Loot filter is modified but not working, also items in stash are ignored

### ISSUE THREAD

**Issue by Sathorn** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#279]
Basically as subject says. If you need more info let me know. 
Stash is recognized because I can see correct stash tab name in overlay. 
Loot filter inside has chaos recipe included but this part of filter doesnt work in the game, rest of the filter is working.

**Comment by HiMarioLopez** [comment]
Definitely need more info. Can you post full screenshots of your settings? Specifically which filter you’re manipulating.

**Comment by Sathorn** [comment]
Ok, so it is a copy of one of official filter from Neversink, here you have what it contains (only a begining, file is too long to post it completely.)
Well, its just a wall of text - is there a way to attach it?

![image](https://user-images.githubusercontent.com/461804/152654829-2f91e571-e54e-497d-aab6-c18d675f773f.png)
![image](https://user-images.githubusercontent.com/461804/152654842-01d6e3ad-2c05-4657-bf9a-5e5859046e4b.png)
![image](https://user-images.githubusercontent.com/461804/152654856-7f78aaae-d54f-4655-a2c8-fb3613d56769.png)

**Comment by Zinterax** [comment]
It seems like items occasionally are getting "stuck" in odd states. This morning the only thing that was working for me was body armors, resetting all my settings fixed the issue for a while. However now body armors are over my set threshold and are never being greyed out.

**Comment by Sathorn** [comment]
Ok I am an idiot, it was items below level 60, under allowed threshold for chaos recipe...
