### ISSUE TITLE
Reloading Filter button in Minified overlay mode just pastes clipboard in chat

### ISSUE THREAD

**Issue by a3person** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#281]
Reloading Filter button in Minified overlay mode just pastes clipboard in chat
Same button in standard overlay mode properly reloads filter

**Comment by HiMarioLopez** [comment]
Howdy, what OS are you on? 
Can you screenshot your settings and post them here? Specifically interested in what filter you’re targeting for manipulation

**Comment by a3person** [comment]
Windows 10, Home Version 21H1. I have no other overlays open. Here's my settings
![EnhancePoESettings](https://user-images.githubusercontent.com/3909629/152653752-76a53985-27aa-4a59-8de5-19def3365857.jpg)
Loot filter location: ‪E:\Quentin\Documents\My Games\Path of Exile\chaos.filter

Here's my loot filter at the moment txt since Github doesn't support .filter files
[Chaos.txt](https://github.com/kosace/EnhancePoEApp/files/8008578/Chaos.txt)

**Comment by LunarBear** [comment]
Not sure if it's the same issue, but "Reloading filter" button doesn't work for me most of the time.
It just briefly focuses the chat window, but the filter is not reloaded. Size of the overlay (minified or full) doesn't change anything for me.

**Comment by vhbert** [comment]
I have the exact same issue as the OP.
It's getting quite annoying since I keep randomly messaging people instead of reloading the filter.
Any files I can provide to help?

**Comment by sclient** [comment]
Came here to post this if it wasn't already. Latest version of Windows home.
Since I had just finished setting up the possesid, it posted that in global!
Thankfully, I play in a small private league, and it is unlikely it will be abused, but this could be a serious security risk for others!

Edit: Also, I don't use it minified, so it happened in standard mode. If there is anything on the clipboard, it will paste that instead of reloading.

**Comment by AmenLi** [comment]
Similar issues, but I can reload successfully, it need more clicks.

**Comment by herofromhyrule** [comment]
Came here for this as I am having the same problem. I'm having to make a habit of clearing my clipboard to ensure that I don't end up messaging people when I'm trying to reload the filter.

I am using Windows 10 21H2,

**Comment by HiMarioLopez** [comment]
The fix for this has been identified and implemented in our latest dev build. It will be released in v1.4.1. Thanks for reporting this!
