### ISSUE TITLE
Negative quantity of items not being removed from the filter

### ISSUE THREAD

**Issue by VirA-C** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#284]
Hey,
Thanks for putting together an amazing addon to help with the chaos recipe.  

I am having an issue with too many of a type not being removed from the filter.  For example, my threshold is set to 10 and I currently have 22 helms in my quad tab however helms are not being removed from the filter and are displaying active on the overlay.  Also due to the numbers being negative, I don't believe it sees a complete set?

![image](https://user-images.githubusercontent.com/49855796/152664002-9ce7de30-5ee5-4983-b178-59dfc74c10e9.png)

Update: This is only occurring on identified items, I do not have the issue with unidentified items.  Working perfecting on unidentified.

**Comment by stoyicker** [comment]
This happens to me even though I only have unidentifieds.

**Comment by HiMarioLopez** [comment]
Howdy, can I get some screenshots of your settings? Also, are you running on the latest versions of the app? 

Thanks!

**Comment by stoyicker** [comment]
Running 1.4.0, settings attached.

![settings_0](https://user-images.githubusercontent.com/1732935/153582060-2217aa64-2107-458d-995d-815b347c3271.png)
![settings_1](https://user-images.githubusercontent.com/1732935/153582061-1bf424bc-d4e5-4eb4-bf4f-628dbba7e5f1.png)
![settings_2](https://user-images.githubusercontent.com/1732935/153582064-a655c388-6da3-41b4-b28b-b5c6e8c14f06.png)

**Comment by Aminus106** [comment]
Had the same problem. I tick the box for "Fill Greedy Mode" and the negative items are now transparent. 
Also, like VirA-C I had -20 Chests and they were transparent.

So maybe I don't understand the Greedy Mode not correctly (most likely) or it has some problem.

Hope it helps :D

**Comment by HiMarioLopez** [comment]
Thinking this whole thread was just user error, which is bad on my part. I have made many improvements to clarify what the feature formerly known as "Fill Greedy" does (now named "Do Not Preserve Low Item Level Gear").

Please open a new issue if you want to make further proposed changes to how we present this feature and its intended behavior.
