### ISSUE TITLE
What could be the problem.

### ISSUE THREAD

**Issue by Brat0108** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#285]
Good day. What could be the problem.
![Снимок экрана (16)](https://user-images.githubusercontent.com/15873641/152670720-e39a35be-b3f9-4edb-80d5-c3583f186fdc.png)

**Comment by HiMarioLopez** [comment]
Howdy, can I get some reproduction steps after you've updated to our latest version and tried to recreate the issue? Thanks!
