### ISSUE TITLE
Tool - not counting or highlighting availbale full sets - all correct level and not ID'd. (1.3.2 fresh install)

### ISSUE THREAD

**Issue by Geoituz** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#289]
![image](https://user-images.githubusercontent.com/13705599/152784636-6694c5f2-c5c9-47e5-9581-16dac7993ef7.png)

![image](https://user-images.githubusercontent.com/13705599/152784731-c3c65cb8-b2b6-495f-807d-a3d71c2a143a.png)

**Comment by HiMarioLopez** [comment]
Howdy, is this issue still present on the most recent update, v1.4.0? If so, can you help me out with some possible reproduction steps?

And a quick screenshot of your settings wouldn't hurt!

**Comment by HiMarioLopez** [comment]
Try checking the 'Fill Greedy' option and see if that fixes it, btw.

**Comment by Geoituz** [comment]
New Updated sorted it...well done and great work, ty
