### ISSUE TITLE
Program Not Opening after last update

### ISSUE THREAD

**Issue by therber2** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#295]
I've tried uninstalling and running the latest msi installation, but after installation, the program doesn't open....
...it shows open on task bar but a hover over shows it in the background stalled with a black screen in the window

**Comment by HiMarioLopez** [comment]
Are you still seeing this issue? Trying to see how you could potentially reproduce or provide me with more info to test it out.

**Comment by HiMarioLopez** [comment]
Closing; Please see #333
