### ISSUE TITLE
[Bug] [Overlays] Overlay window stuck off-screen for some users when swapping to and from multi-monitor setups

### ISSUE THREAD

**Issue by pszentg** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#296]
Hi!
Since yesterday the overlay is not opening properly. I can see it when I alt-tab through my opened windows:
![image](https://user-images.githubusercontent.com/19414976/152889798-eea86107-73ab-4e7b-a965-e34e0d9f2021.png)
but can't open it or interact with it. Tried reinstalling and even reinstalling an older release, the same issue persists. Are there any config files that persist after an uninstall I should try removing?

**Comment by therber2** [comment]
I am having the same exact issue. I uninstalled, restarted computer and tried an older version 1.29 I think it was. It opened.
Now it isn't opening again (ie. it is doing the exact same thing OP described).

**Comment by Speedwagon98** [comment]
Same issue here. I had 1.2.6 before, uninstalled and installed 1.4. On older version, I could see the overlay in alt-tab, but couldn't see it on the desktop anywhere. On 1.4, I can't see the overlay at all, just a chaos recipe icon when I alt-tab.

Just installed 1.2.4, and that one seems to be ok. 1.2.6, 1.3, 1.4 all fail. But then 1.2.4 works again, after uninstall, install on each of these, and back to 1.2.4.

**Comment by HiMarioLopez** [comment]
Can you check if any of these resolves your issue? Common problem with multi-monitor setups. Also could happen with single monitor setups.

https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4

Try them out and let me know

**Comment by Speedwagon98** [comment]
I appreciate the response. The only thing I am able to accomplish, using
1.2.6, is to maximize the display. When I do that, it takes up the entire
screen. But I cannot cascade, resize it, or anything else.

I also tried with just the laptop's built in display, and that didn't help
either.

**Comment by HiMarioLopez** [comment]
> Can you check if any of these resolves your issue? Common problem with multi-monitor setups. Also could happen with single monitor setups.
> 
> https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4
> 
> Try them out and let me know

Yeah, so this is a bug that tons of apps run into. All I can do is point users to the link above to try and resolve their issues. It's more of a Windows problem, than anything.

My recommendations for users is to upgrade their display drivers, upgrade their windows, and upgrade our app.

I'm going to keep this open to see if there are any ideas in the future that we could implement into our application to help reduce the frequency of this unintended behavior.

**Comment by Speedwagon98** [comment]
Upgrading to 1.5.5 fixed the issue. I thought I had installed the newest one a few days ago, but I apparently didn't remove the 1.2.6 setup file from my computer first, and accidentally installed that one.

But 1.5.5 is showing now.

**Comment by HiMarioLopez** [comment]
Awesome to hear your issue was resolved. It may have been a settings reset that reset the positions for you.
