### ISSUE TITLE
[Enhancement] [General] Improved error reporting in warning windows when catching connection exceptions

### ISSUE THREAD

**Issue by Invictus6474** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#297]
I occasionally receive this error during play:

![CRE Error](https://user-images.githubusercontent.com/99221192/152895339-891e35d4-132e-4668-b213-f9c78bb4f96f.jpg)

The app continues to function with no issues, but the pop-up appears above the game window and takes input focus away from the game.

**Comment by Invictus6474** [comment]
Update: I believe the app stops updating item count after this error appears (even after clicking the Stash button).
I need to Exit the app and restart it for the counts to update.

Was not running the app in Admin mode (not sure if it matters). Will run in Admin mode and see if the error appears again.

**Comment by Invictus6474** [comment]
Update: Ran the app as Administrator. Same issue.

After the error appears, the app no longer updates item numbers, even when pressing the button.

**Comment by HiMarioLopez** [comment]
Howdy! 

Can I get some reproduction steps? Is there any scenario where this happens 100% of the time? Any details around your network conectivity when using the app (weak wifi signal, you're using a proxy/vpn, etc.) that could help me find the root cause?

A few screenshots of your settings wouldn't hurt, either


Thanks!

**Comment by Invictus6474** [comment]
Thank you for looking into this.

The error appears at random, unable to reproduce consitently.
Using a wired connection, No proxy/VPN, app is added to firewall (allowed).
I do use a PiHole ad blocker on the network, but the app works fine until the error.

![Settings 1](https://user-images.githubusercontent.com/99221192/153966932-12eb25cd-46ab-4054-ae35-0ebb3f1a4b01.jpg)
![Settings 2](https://user-images.githubusercontent.com/99221192/153966934-3fc15d5a-8d8f-4f34-a22b-fa43115bf5d2.jpg)
![Settings 3](https://user-images.githubusercontent.com/99221192/153966936-55187c21-80a2-43a9-96ff-827a9a3403a9.jpg)

**Comment by HiMarioLopez** [comment]
When was the last time you updated your PoE session ID?

**Comment by Invictus6474** [comment]
My PoE session ID has been the same since I started using the app (I haven't logged out of the PoE site). I updated it twice in the last week, as a part of settings reset.

**Comment by HiMarioLopez** [comment]
Could be just some network blips and our app isn't handling them properly. From what I can see, our app looks for any 'success' response after querying to GGG's API (Code 200 - 299), else we spawn this window. What I can do is see if there's any way to better display what specific error you're getting based on the response code.

**Comment by HiMarioLopez** [comment]
Closing this and tracking 'solution' here https://github.com/kosace/EnhancePoEApp/issues/380
