### ISSUE TITLE
Asking for log File Location

### ISSUE THREAD

**Issue by ManicManiac6102** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#298]
It had been running fine for 2 days before this. now today when I hit "Run Overlay" to start it a "Missing Settings" box pops up and says 
Please add:
  -Log File Location
Ive never had this problem before and I dont know what log file its asking for. Any help would be great

**Comment by HiMarioLopez** [comment]
It's asking for the Client.txt file that's located in your game's source directory. This is used to read when you switch areas.

**Comment by HiMarioLopez** [comment]
Here's an example of what the path to your log would look like (Assuming you installed PoE on your C drive; this WILL be different if you installed on Steam).

"C:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\Client.txt"

Let me know if you run into any issues after setting this in the settings, thanks!
