### ISSUE TITLE
Can't install the app

### ISSUE THREAD

**Issue by CmdrVimes212** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#299]
When running the CREsetup.msi, the installer starts but immediately closes and i can't do anything about it. Could you please help me?

**Comment by HiMarioLopez** [comment]
Howdy, we have had that issue appear on Windows 11, don't necessarily know the cause. The program may have installed automatically, can you check if it appears in your start menu?

**Comment by CmdrVimes212** [comment]
Wow, i haven't even checked it as i thought it straight up crashed. Turns out it really installed automatically, i'm on windows 10 tho.

Thank you for your reply, have a great one!

**Comment by HiMarioLopez** [comment]
Sounds great! Like I said, we want to make sure it's a more interactive and consistent installation experience. Sometimes people get prompts, sometimes they do not :(

**Comment by Kazatel** [comment]
Hi , I just bought new laptop with windows 11 home edition and when I tried to install this .msi file I was redirected with pop out widnows to search app in MS store, where is of course not found. I tried to run it in MS installer which failed.
Solution:
Right mouse button on installer file -> select properties ->on General tam on very bottom was unblock button or maybe checkbox

reference: https://support.site24x7.com/portal/en/kb/articles/197194
good luck, thank you for the app
