### ISSUE TITLE
[Enhancement] [General] Add proxy setting

### ISSUE THREAD

**Issue by AmenLi** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#300]
Hi, I am a Chinese user, can you add a proxy setting (like Socks5).
Because open the system proxy settings of Windows will affect other software and cause conflicts.

Anyway, thanks for your software, it's very easy to use

**Comment by RocketPop** [comment]
This should be fairly straightforward using NET 6 I think. SOCKS support is built into that version of HttpClient AFAIK. I tried a quick&dirty project conversion to 6 but some of the dependencies (the extended WPF toolkit) weren't compatible it seemed.

**Comment by HiMarioLopez** [comment]
Hi, I was snooping through the folks and noticed someone went ahead and created a Chinese variant of the app. I'm assuming the proxy is maybe not the only thing that differs from our apps, so I encourage you to check it out! https://github.com/SingHill/EnhancePoEApp_CN

If you still need other help with our app, please post another issue, thank you again for your support.
