### ISSUE TITLE
League Issue after 1.4.0.0 Update

### ISSUE THREAD

**Issue by Celonic** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#305]
After updating to v1.4.0.0 we are no longer able to set our league manually. While this was great for users in trade league, if you are in a private league, you can no longer enter the league name. This keeps the application from being able to read the stash tab, breaking the entire thing.

**Comment by kosace** [comment]
Hello,

you can downgrade the version by downloading a previous release here for now if you cannot use it anymore: https://github.com/kosace/EnhancePoEApp/releases

**Comment by sclient** [comment]
I have to request this feature to be reverted. I would like to use the current version with my private league. I realize we arent in the majority here, but this was better as it was (I would really like to be able to take advantage of all the features added in the future). Best of both worlds would be to read the private league based on sessionID, but I have no idea if this is possible.

At minimum, it would be nice to at least have a checkbox like 'enable private league entry'.

**Comment by HiMarioLopez** [comment]
> I have to request this feature to be reverted. I would like to use the current version with my private league. I realize we arent in the majority here, but this was better as it was (I would really like to be able to take advantage of all the features added in the future). Best of both worlds would be to read the private league based on sessionID, but I have no idea if this is possible.
> 
> At minimum, it would be nice to at least have a checkbox like 'enable private league entry'.

I'm gonna work to get a solution out that will cater to both parties. I've had too many issues reported where their solution was a simple typo in the league name. Give me a few days to get this back up for you private league folks!

**Comment by HiMarioLopez** [comment]
Releasing a fix for this today. Thanks for your issue reporting!! Makes a big difference.
