### ISSUE TITLE
Overlay won't show at all

### ISSUE THREAD

**Issue by Ilnez** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#306]
I have tried both the keybind for show overlay and the button and neither gives me any sort of overlay.

No errors or feedback whatsoever from the app.

Worked fine with the previous version.

**Comment by HiMarioLopez** [comment]
Any other info would be great!

Could you try completely uninstalling the application and installing it again? Maybe that'll get us somewhere. Also, attempting to run it in admin mode and seeing if that does anything.

**Comment by pszentg** [comment]
This seems to be a duplication of https://github.com/kosace/EnhancePoEApp/issues/296. We wrote down there that uninstalling and even reverting to previous versions did not fix the issue.

it also is written and I can confirm that rerolling to 1.2.4 fixes that issue so some changes between that and the next version broke this.

**Comment by Unknown-Guy** [comment]
#254 my issue was closed but is still the same. Tested with 1.2.5 and it works fine.  1.2.6. is broken. Suspect installer change broke something.

**Comment by HiMarioLopez** [comment]
We went ahead and resolved @Unknown-Guy 's issue, it was a missing .NET Framework Runtime

@pszentg @Ilnez Any updates on your issues? If it isn't resolved can we start by posting some screenshots of the taskbar / icon tray to see if anything is showing up at all

**Comment by HiMarioLopez** [comment]
Closing this out again as it has become a bit stale. Try running the latest version 1.5.4 and please re-open a new issue if you run into any problems.
