### ISSUE TITLE
Online Loot Filter Manipulation Feature Disappeared

### ISSUE THREAD

**Issue by RickTorresJr** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#308]
After upgrading to 1.4.0 the Online Loot Filter Manipulation functionality has vanished and I'm no longer able to select an online filter, only offline local ones.

<img width="852" alt="cre-missing" src="https://user-images.githubusercontent.com/12430441/154382001-3de88e97-da66-4b97-b2e7-64cd056fef63.png">

**Comment by HiMarioLopez** [comment]
Hi, we removed this feature due to limitations on the GGG side of things. It won't work properly for the foreseeable future.

edit: We removed it in v1.4.0, you can definitely roll back but we won't support or tend to any bugs related to it.
