### ISSUE TITLE
Frequent crashing

### ISSUE THREAD

**Issue by ShaneOK** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#31]
Great tool but I'm getting frequent crashes while using the stash overlay. While mousing over items the game will lag and then crash without any dialog. Also will sometimes crash during gameplay when items are dropping.
[sk-dxdiag.txt](https://github.com/kosace/EnhancePoEApp/files/5758772/sk-dxdiag.txt)

**Comment by kosace** [comment]
Hello,

which version are you using?

**Comment by ShaneOK** [comment]
The 1.1.3 release

**Comment by ShaneOK** [comment]
Not sure if this is related but I ended up with this error. The only hotkey I setup was Stash tab toggle to ctrl+alt+T which I've since removed. I also have been crash-free for awhile now after changing the Overlay highlight mode to Set by Set instead of Item by Item.

![Screenshot 2021-01-02 011224](https://user-images.githubusercontent.com/6115652/103454320-9ba53400-4c97-11eb-913c-4cfd98dd7ef1.jpg)

**Comment by kosace** [comment]
max 2 keys are allowed thats why. I didnt know it was even possible to register 3 keys... 

very interesting
