### ISSUE TITLE
open with windows!

### ISSUE THREAD

**Issue by arman0091** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#312]
hey its a useful app but it would be better if u add an option to make it open with windows startup :)

**Comment by dovry** [comment]
Run app on startup
https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd

**Comment by HiMarioLopez** [comment]
Closing for now as there has been a resource pointed to add executable to startup manually, may revisit this in the future but it'll be quite low priority for now. Thanks!
