### ISSUE TITLE
Tab overlay on different monitor

### ISSUE THREAD

**Issue by Sathorn** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#313]
I dont know how, but my overlay just switch to another monitor and I can't get it back
![image](https://user-images.githubusercontent.com/461804/154750884-2c6d3ef0-34c2-44a9-aa9a-11bb161f45ce.png)

**Comment by dovry** [comment]
Edit, then grab inside the red border to move it.
![image](https://user-images.githubusercontent.com/15201298/155123845-c02c2336-1163-4e4b-a47a-0e9a9428c847.png)

**Comment by HiMarioLopez** [comment]
Also recommend checking out #267 

See: https://support.ti.davidson.edu/hc/en-us/articles/115016089728-Move-an-Application-Window-From-Off-screen-Back-to-Your-Main-Desktop-Windows
