### ISSUE TITLE
Missing dynamic resolution handler

### ISSUE THREAD

**Issue by SimpleCookie** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#315]
# Problem
Running on a higher or unusual resolution causes the stash tab overlay to have cascading offsets.

![image](https://user-images.githubusercontent.com/3315595/154849039-81d5f7fa-050b-4b54-99be-fb6466a5e642.png)

# Solution
Fetch or ask for the game window resoluton and draw the grid accordingly.

**Comment by HiMarioLopez** [comment]
The manual overlay resizer should be enough for now. The little pull tab on the bottom right.

I could maybe look at automating this action in the distant future, it would be a very low priority enhancement though
