### ISSUE TITLE
Unable to launch app

### ISSUE THREAD

**Issue by AeroScorch** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#316]
![error](https://user-images.githubusercontent.com/100156484/155005219-62e8fd24-db8a-4688-87d5-aa1508b65ac4.PNG)

This error appears when launching the app. I tried reinstalling but it did not work.

**Comment by HiMarioLopez** [comment]
Can you try running admin mode? Any other info including OS build etc. is useful to me. Thanks!

**Comment by AeroScorch** [comment]
Running as administrator gave the same error. I am currently clearing the EnhancePoE folder in appdata and reinstalling again to see if it is an error with that part of the installation.

**Comment by AeroScorch** [comment]
Update: clearing the appdata folder and relaunching worked. No reinstallation needed.
