### ISSUE TITLE
Can't initiate program

### ISSUE THREAD

**Issue by PMazee** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#32]
Hi!
I have a problem with starting this App and getting this error.
![image](https://user-images.githubusercontent.com/76904443/103477759-05216180-4dc2-11eb-8ff1-2d3a8611cd83.png)
Any tips ?

Ofc I am using lastest version and installed from .msi

ps. If You need i can translate non-english parts but i am pretty sure You probably dont need it.

**Comment by kosace** [comment]
can you check if following file exist:

users/username/appdata/local/enhancepoe/enhancepoe..../1.0.0.0/user

and if it exists can you copy paste it here?

**Comment by PMazee** [comment]
Sure.
user.config

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <EnhancePoE.Properties.Settings>
            <setting name="accName" serializeAs="String">
                <value>Grothart</value>
            </setting>
            <setting name="TopMain" serializeAs="String">
                <value>362</value>
            </setting>
            <setting name="LeftMain" serializeAs="String">
                <value>421</value>
            </setting>
            <setting name="Sets" serializeAs="String">
                <value>3</value>
            </setting>

**Comment by PMazee** [comment]
Sure
user.config

Looks like config is corrupted - .xml is broken.
![image](https://user-images.githubusercontent.com/76904443/103479713-df9b5480-4dcf-11eb-8e74-02dd44bfa145.png)

I will delete i install again.

**After deleting this user.config and reinstalling its working.
Thanks for advice and great work.**

**Comment by kosace** [comment]
ok nice :)
