### ISSUE TITLE
"Reload Filter" button on overlay issue

### ISSUE THREAD

**Issue by AeroScorch** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#320]
When I click "reload filter" on the CRE overlay, my session ID is pasted into global chat. Could this possibly be a conflict with a keybind? Or is there a setting somewhere that would stop this from happening?

**Comment by HiMarioLopez** [comment]
The bug is that it's pasting your most recent clipboard item to the chat, which is an issue we've been tackling for a while now. If you copy something else, it will paste that into the chat.

**Comment by HiMarioLopez** [comment]
Gonna be closing this issue out since it's gone stale. Please open a new one if you have any other issues!
