### ISSUE TITLE
The following exception occured

### ISSUE THREAD

**Issue by towen2525** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#323]
<img width="1199" alt="Chaos_Error" src="https://user-images.githubusercontent.com/100450127/155817395-ceaf19b5-73eb-4303-bd23-03fe7006fcf0.PNG">

**Comment by cozy13198** [comment]
same to me. do u have any way to fix it?

**Comment by HiMarioLopez** [comment]
Howdy, are y'all still seeing this issue? @cozy13198 @towen2525 ?

Are you running as an admin user? Can I get some screenshots of your settings or any other info that could be useful

**Comment by towen2525** [comment]
I uninstalled the program and now that 3.18 is out I downloaded the lastest
again and it seems to be working.

**Comment by towen2525** [comment]
Sorry I have tried a few things and still I get the same error. I have
removed it from my computer several times, but nothing has changed. I
suppose next step would be I will try to post it on Discord.
