### ISSUE TITLE
[Bug] [Overlays] Item by item feature won't work for some users unless both CRE and PoE are running in admin mode

### ISSUE THREAD

**Issue by ssman7810** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#324]
When I click on the first item highlighted, the highlight does not move to the next item.

**Comment by okitasyou2** [comment]
me, too!

**Comment by HiMarioLopez** [comment]
Getting increased reports of this same issue and really hoping to get some reproduction steps! Haven't been able to reproduce it locally on my machine :/

Hoping to fix this before next league launch for sure but need some help here!

**Comment by HiMarioLopez** [comment]
Can y'all make sure your Windows display scaling is set to 100%? This was the fix for another person having the same issue.

**Comment by HiMarioLopez** [comment]
Any updates from y'all @okitasyou2 @ssman7810 ? If not, I will go ahead and close the issue out

**Comment by trunksdmx** [comment]
Never used the tool before, was having the same problem in standard while testing it (version pre-release 1.5). Native res 1920x1080, windowed fullscreen, windows display scaling 100%. One of these things fixed it for me.

-POE is running in admin mode but the tool was not; Exited tool, relaunched tool in admin mode (which was definitely messing with the tool as reloading tool in admin mode made other features function correctly)

-Have stashtab mode set to Prefix (value= C ), tabs named C1 and C2, noticed overlay shows tabs in different spot then the position they are in; Moved the position of C1 and C2 tabs to the first 2 tab spots in stash to match the overlay (mostly). Relaunched tool.

Both things that are probably explained in the documentation and are pretty obvious if you have experience using 3rd party tools in POE but could be overlooked.  Works perfectly for me now.

**Comment by Jaxxas** [comment]
This issue is still happening in 1.5.1, When you remove an item from your stash tab, the Highlighted area just stays where the item use to be. It does not move on to the next item to be removed.

Changing windows scaling to 100% did NOT fix it. ( I was at 125%)

EDIT: OK BOTH POE and the tool needed to be run as ADMIN. As mentioned above.

**Comment by HiMarioLopez** [comment]
> This issue is still happening in 1.5.1, When you remove an item from your stash tab, the Highlighted area just stays where the item use to be. It does not move on to the next item to be removed.
> 
> Changing windows scaling to 100% did NOT fix it. ( I was at 125%)
> 
> EDIT: OK BOTH POE and the tool needed to be run as ADMIN. As mentioned above.

Good clarification, I'll keep this in mind. It is definitely not intended, but I'll advise users to try this as a work-around if they run into the same issue.

It's in the plans to change how we manage user input, which will help resolve issues like this one. Still a long ways off, but know it's in the backlog.

**Comment by xrande** [comment]
Posting from duplicate issue #378 
My app has always been running in admin mode. My POE hasn't been admin mode. Let me try that.

**Comment by REllEK-IO** [comment]
Running this on a clean install on Windows 11, have tried both admin mode and the window scale @ 100% for both monitors. No luck.

My thoughts would be windows unfortunately

**Comment by HiMarioLopez** [comment]
Closing this as the issue has become stale, and we're cleaning up our issue board ahead of the 3.20 league launch. Please open a new issue if you would like us to take a look at this again. 

I put the note about needing to run CRE in Admin mode if you are running the PoE client in Admin mode to the [F.A.Q.](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/wiki/F.A.Q.)

Thanks!
