### ISSUE TITLE
Dispatcher.UnhandleException

### ISSUE THREAD

**Issue by cozy13198** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#326]
Error when fetching
![image](https://user-images.githubusercontent.com/102278154/159848008-afe4b78c-b34d-4376-9afa-ff9cb6426652.png)

**Comment by HiMarioLopez** [comment]
Can you drop a screenshot of your settings page to start off? Thanks!

This error looks like there's an issue with your Client.txt log file route, could be something else, though!

**Comment by cozy13198** [comment]
hi there
![image](https://user-images.githubusercontent.com/102278154/160434264-e130b0b9-59f1-482c-ab07-161b0b80dbc4.png)
****
![image](https://user-images.githubusercontent.com/102278154/160434381-72c5b04e-27ae-4b74-a5a3-748fea3a5d47.png)

![image](https://user-images.githubusercontent.com/102278154/160434432-7f6d5609-8600-4515-b9b3-b03dda70ae01.png)

**Comment by HiMarioLopez** [comment]
Your account name seems to be empty, is there a reason for that? Just to omit it from the screenshot?

**Comment by cozy13198** [comment]
ah i just deleted it xD
