### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by robyrollover** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#329]
![Screenshot (5)](https://user-images.githubusercontent.com/103808609/163662826-7d393e37-b78d-435c-9aa4-1b1be2e44ab4.png)

**Comment by HiMarioLopez** [comment]
Can I get a screenshot of your settings, please?

**Comment by robyrollover** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/103808609/163892592-080abb87-238f-43bf-912f-33516be1a097.png)
![Screenshot (8)](https://user-images.githubusercontent.com/103808609/163892594-8f4aa942-dd57-4bae-9c36-f71978fbf9de.png)
![Screenshot (6)](https://user-images.githubusercontent.com/103808609/163892598-9ce4a773-6fd3-495c-a4d3-29ccddd869ee.png)

**Comment by robyrollover** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/103808609/163892623-4bae8c2d-4762-47ac-bbd8-d18f866bbdb5.png)
![Screenshot (11)](https://user-images.githubusercontent.com/103808609/163892624-33d1c3e2-d6f7-4a90-bfb1-3291248e1abc.png)
![Screenshot (9)](https://user-images.githubusercontent.com/103808609/163892626-cf455b06-a4d9-4af1-b724-5504615ba92c.png)

**Comment by HiMarioLopez** [comment]
Howdy, revisiting this. Any updates from your end? Are you still seeing this issue?

**Comment by HiMarioLopez** [comment]
Closing this; try out 1.5.4 and re-open if you see this issue again. Thanks!
