### ISSUE TITLE
Minor bug: Thicket Bow

### ISSUE THREAD

**Issue by xeske** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#33]
Just noticed that Thicket Bow (2x3 size) wrongly highlighted as 'Weapons' in a lootfilter.

(Bows require a quiver to complete chaos recipe, therefore are not practical)

**Comment by kosace** [comment]
Hello,

bows dont require quivers for chaos recipe.

**Comment by xeske** [comment]
Oh indeed, in this case everything works great!
