### ISSUE TITLE
Unable to Edit the stash overlay

### ISSUE THREAD

**Issue by natfubar** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#330]
The Stash overlay is in the wrong location and I cannot click the Edit button to reposition/resize it. It feels like it is behind POE. Is there a hotkey that can put it into edit mode?

**Comment by HiMarioLopez** [comment]
There is not. Is your PoE running in “Windowed Fullscreen” mode? That’s the only way overlay apps like this one will work

**Comment by natfubar** [comment]
Yeah it is. I managed to wrangle it to the right spot using right-click move/size options on the windows icon. So all good.

**Comment by LahkLeKey** [comment]
I found a pretty bizarre workaround for this if your playing on 4k / 8k. Set resolution to 100% (still unclickable. Hover over windows app and right click ("Set to Fullscreen"). Set scaling back to what you want it to be. (300% in my case). Now you can interact with the stash UI. 

Most likely needs some DPI setting configured on your overlay.

https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8
