### ISSUE TITLE
[Bug] [Overlays] "No StashTabs Available!" when user attempts to query existing tab that is empty (May just be bad error handling logic)

### ISSUE THREAD

**Issue by ChaosRecipeEnjoyer** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#331]
I have the overlay successfully running but it will not fetch my stash tabs. 

I open POE. Reload (filterblade) filter. 
Open ChaosRecipeEnhancer. POE Session ID is grabbed from POE forums site (signed in, character overview page, POESESSID number copied under Value column, Paste in Session ID). 
Run Overlay. 
Reload Filter. 

Fetch. 

Result: No Stashtabs found...
![Fetch = No Stashtabs found  ](https://user-images.githubusercontent.com/105264355/167547688-9c973d9a-c406-46fe-b09d-900c87cbef21.jpg)

-When I click Stash button (because it's there, why not). 
![After Stash button](https://user-images.githubusercontent.com/105264355/167547766-5c1dfe62-a67e-48b4-89cc-dbe76c005072.jpg)

Here are my settings: 

General 
![CRE- General](https://user-images.githubusercontent.com/105264355/167547838-6c8f7d94-747a-40e8-aa9d-5fe2a2ae66c0.jpg)

Overlay
![CRE- Overlays](https://user-images.githubusercontent.com/105264355/167547843-66e7c5bb-3696-4151-b94a-1eb529230d2f.jpg)

Loot Filter
![CRE- Loot Filter](https://user-images.githubusercontent.com/105264355/167547852-a4eea70b-a11c-4b4e-83cd-d34dcd5bd8b7.jpg)

I have followed a few youtube guides (PathOfMatth, Von Victum) and searched around for similar issues but there seems to be limited info out there for such a good tool. The only references where attached to an update awhile back but I am running the newest version and I see no open issues about this so there must be something I'm missing. I'm having this problem on 2 computers with 2 accounts so it's probably me. 

Any hints or tips or suggestions would be appreciated! I've completely hit a wall.

**Comment by HiMarioLopez** [comment]
Howdy, can you post a screenshot of your PoE stash screen with the tabs visible? Thanks!

**Comment by ChaosRecipeEnjoyer** [comment]
Sure thing! 

Screenshot of PoE Stash Screen with Tabs:
![PoE Stash Screen with Tabs](https://user-images.githubusercontent.com/105264355/167648716-7e3681ad-7301-49d4-b8b9-17ff0c2a3ef1.jpg)

**Comment by HiMarioLopez** [comment]
This is really dumb to mention, but I'm sure you know already:

In order for stash data to get updated you need to zone into a new area in the game. You're doing that, right?

**Comment by HiMarioLopez** [comment]
So, for example, if you change a stash tab name or move items around, or remove items from the stash, none of those changes get 'published' to the server until you zone into a new area, and the API's we call to get all the stash data won't return anything until those changes are present on the GGG side of things.

**Comment by EdwoG** [comment]
Currently, the website api doesnt update stashtabs, most likely because of League transition. Thats why it cant find your stashtab with prefix, and suffix give invalid stashtab errors

Source: Thirteenera on discord

**Comment by HiMarioLopez** [comment]
> Sure thing!
> 
> Screenshot of PoE Stash Screen with Tabs: ![PoE Stash Screen with Tabs](https://user-images.githubusercontent.com/105264355/167648716-7e3681ad-7301-49d4-b8b9-17ff0c2a3ef1.jpg)

User on discord reported a very similar issue. They also had an empty tab, as in your picture. Wondering if there's some buggy / flawed logic going on in our app when the GGG API returns some empty stash contents.

I'm going to look into this.

**Comment by intekritysolutions** [comment]
I'm having the exact same issue. I've been screwing with it for hours and no matter what I do, I get a "No Stashtabs Found" message. I've tried ID, suffix, and prefix. Nothing works. Any suggestions?

![image](https://user-images.githubusercontent.com/88560258/169188448-d225655d-9288-4f9d-a757-07a0e19ee3ce.png)


![image](https://user-images.githubusercontent.com/88560258/169188388-ca3fd751-d9e7-44f1-8708-39ade0f9185d.png)

**Comment by HiMarioLopez** [comment]
@intekritysolutions Worth asking, are your tabs also empty? 

If they are, put stuff in them to see if that’s what’s causing the issue.

I’ve got a busy week coming up with a trip this weekend then a traveling for a conference for work. I won’t have time to look through the code until sometime next week, if that.

**Comment by Adjayjay** [comment]
Same Issue here. It was working great last league but I had to reinstall Windows and I can t get it to work again.

Fetch or sets do nothing, reload fileter works fine and stash will show stash overlay.

I got this error at some point but can t replicate it :

![error](https://user-images.githubusercontent.com/111930185/186285491-5fed9b17-9b19-4671-87a4-7078b7732b26.png)


My settings and stash :


![1](https://user-images.githubusercontent.com/111930185/186285527-733dd4c6-7e8f-4f80-89ca-7ddc56d28bc4.png)

![2](https://user-images.githubusercontent.com/111930185/186285529-27092d86-3d93-4b80-b729-bf2541bc3a74.png)

![stash](https://user-images.githubusercontent.com/111930185/186285566-40e0571d-8fc3-4d3f-a1ca-b4a59015963b.png)

![3](https://user-images.githubusercontent.com/111930185/186285664-d0b50d3b-cae2-4bda-844e-c458c442ef68.png)

**Comment by HiMarioLopez** [comment]
Moved tracking to https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/380
