### ISSUE TITLE
[Bug] 1.5.0 Won't open

### ISSUE THREAD

**Issue by akadevvy** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#333]
Can't seem to get this to open. Installed over 1.4.1 and wouldn't open. Reinstalled a few times application just closes in task manager after a second. Installed 1.4.1 and works fine, settings are still saved too could that have anything to do with it?

**Comment by Christian654** [comment]
cant open it too, seems that somethings happens in the background but nothing i can do. any suggestion?

**Comment by HiMarioLopez** [comment]
Howdy, seeing this message pop up in discord and these 2 things have resolved it for everyone thus far (working to automate the first):

1) Nuke everything if you're coming from an older version

Remove directories you may or may not have in:

C:\Users\YOUR WINDOWS USERNAME\AppData\Local\EnhancePoE
C:\Users\YOUR WINDOWS USERNAME\AppData\Roaming\Chaos Recipe Enhancer
Uninstalling all instances of the app from Windows

2) Not having .NET Framework Runtime installed https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48 

Let me know if either of these fixes the issue for you, especially the 1st one. If not, please message me on Discord so we can find you a resolution! (Much faster to respond on there). My ID on there is Meatbox#1607 , and if I'm not online you can just hop on the server and see if anyone else is able to help https://discord.gg/HDSQVpnd

**Comment by akadevvy** [comment]
Looks to be working now.

Deleting AppData\Local\EnhancePoE is what worked for me. I'll clear out the other directories just incase

**Comment by dovry** [comment]
Removing `%USERPROFILE%\AppData\Local\EnhancePoE` fixed 1.5.0 not launching for me to.

@HiMarioLopez Could you reference this issue on the release page and keep this issue open until this is fixed?

**Comment by HiMarioLopez** [comment]
That's a great idea! Thanks @dovry 

Pinned now :)

**Comment by Maleix2** [comment]
False alarm :)

****** It installed fine silently, sorry not used to that, thanks for reply <3  ****

**Comment by HiMarioLopez** [comment]
it installed silently probs, try hitting your windows key and search "Chaos" and it should pop up @Maleix2

**Comment by pikess** [comment]
I tried everything this thread and the newest version still won't open. I am able to use 1.4.1 just fine.

**Comment by HiMarioLopez** [comment]
@pikess See https://github.com/kosace/EnhancePoEApp/issues/348
