### ISSUE TITLE
Reload Filter button spewing out my clipboard* in chat

### ISSUE THREAD

**Issue by username418** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#334]
Using 1.5.0

When I press the Reload Filter button, sometimes it works and the filter reloads, other times it writes out my poessid in chat

**Comment by username418** [comment]
Correction: it's pasting what is on my clipboard, I just had my poessid on it.

**Comment by HiMarioLopez** [comment]
Hi, can I get a quick screenshot of your settings for the app, if you don't mind? Thanks!

**Comment by username418** [comment]
![general](https://user-images.githubusercontent.com/67152835/167936372-a977a308-fdb1-467d-8a04-7047a3362855.PNG)
![lootfilter](https://user-images.githubusercontent.com/67152835/167936377-9351f860-cf2f-4aa1-a78c-17eb0f7115be.PNG)

Overlays is default

**Comment by HiMarioLopez** [comment]
Can you try running the app in admin mode and seeing if that works?

**Comment by username418** [comment]
It works.
