### ISSUE TITLE
[Bug] [General] Exceptions when querying from normal (non premium) tabs

### ISSUE THREAD

**Issue by Zer0101010** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#335]
When 1st opening the program at sc000.
after exiting and trying again, the program can be run as normal, after that;
This happened when I click the "Stash icon"

 "No StashTabs Available! Fetch before opening Overlay" << how to fix this?

![Sc0000](https://user-images.githubusercontent.com/105369272/167869932-58f0860c-33e2-46c0-b264-aba18b55b2b7.png)
![Sc0001](https://user-images.githubusercontent.com/105369272/167869946-bf5b090d-8d0e-4e76-a01a-db8a42fd0a0b.png)
![Sc0002](https://user-images.githubusercontent.com/105369272/167869947-16a5079b-d63c-4041-95a6-9817a321deab.png)
![Sc0003](https://user-images.githubusercontent.com/105369272/167869949-a2a8ae5d-e312-466b-a5f6-3b517c1dc2d7.png)

Stashtab Mode either changes to ID or Prefix the result is still the same.

**Comment by HiMarioLopez** [comment]
Hi, I believe GGG's API responses were all messed up this morning and yesterday evening due to the Archnemesis league ending and merging back into Standard.

When you have a chance, can you let me know if you're still having issues with the stash tabs? If you are, can I get a screenshot of your stash tabs, please?

**Comment by Valderhide** [comment]
Not sure if it the same problem. But I am also getting the same error. Which when I try to fetch the data give me a "Not Found" error. As far as I can tell my Session ID is correct. 
![image](https://user-images.githubusercontent.com/84632419/167983989-1e1d02a9-b159-46be-acf2-ef86d5b2d165.png)

**Comment by HiMarioLopez** [comment]
Any updates? Else I'll close this out in the next few hours before I release the new update.

**Comment by Zer0101010** [comment]
still the same thou no change at all still the problems presist

**Comment by Zer0101010** [comment]
update on the latest tryout.. run overlay and click on the stash icon.. error pop up showing the problems.. program is closed, opening it again, run overlay same problem
![Sc0005](https://user-images.githubusercontent.com/105369272/168315405-d1ad97d9-5257-4a6b-a24b-1530736e46a3.png)
![Sc0006](https://user-images.githubusercontent.com/105369272/168315418-3e272efe-edd5-43e3-a0b6-ee41a0c8ae59.png)
![Sc0007](https://user-images.githubusercontent.com/105369272/168315424-c3064227-16eb-44ac-a81a-3205aa620d49.png)
![Sc0008](https://user-images.githubusercontent.com/105369272/168315429-554233b1-2b01-4504-b149-f98f8866a12b.png)

**Comment by HiMarioLopez** [comment]
Seeing a pattern with some of these issues; all the issues that have a similar error are using normal (not premium) tabs. I'm going to see if there's an issue with how we parse the response payload from GGG's stash tab API for normal tabs vs premium/quad tabs.
