### ISSUE TITLE
Filter is highlighting items outside of chaos recipe iLvl range

### ISSUE THREAD

**Issue by pikess** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#336]
I'm testing out Chaos Recipe Enhancer for league start and I noticed that in my tier 16 maps, the filter was highlighting iLvl 83 items. iLvl 74 and up items should be hidden from the filter, and they have been in the past, but it does not appear that is happening now. See screenshots below and let me know what troubleshooting I can do to help solve this. I love the tool and I hope this can get fixed before league start. Let me know if I can help. Thank you!!

![1](https://user-images.githubusercontent.com/16213626/167975410-59dc1781-9391-4807-b317-384bae04a439.png)
![2](https://user-images.githubusercontent.com/16213626/167975412-df4c583f-853d-46db-8db9-af3b375daaf2.png)
![3](https://user-images.githubusercontent.com/16213626/167975413-9f547d9d-f3c9-4319-8361-5b7921781bd9.png)
![4](https://user-images.githubusercontent.com/16213626/167975493-333bebc0-0487-49e6-817d-b8ae028ba964.png)
![5](https://user-images.githubusercontent.com/16213626/167975689-fa05e411-73cf-445f-9320-667d762a7a92.png)

**Comment by Jaxxas** [comment]
Comparing the filter before and after updating it would help. Looking at the body armor filter right now for 1.5.2 and it seems to be correct.

![image](https://user-images.githubusercontent.com/12674007/168338390-3cc13fb0-13d7-4338-8a09-607ebe87038c.png)

**Comment by HiMarioLopez** [comment]
This is intended behavior. What we do in our logic when composing sets is first 'assign' a single chaos item to the set. Once that is fulfilled, we will fill it with any item higher than item level 60 (even 74+).

You don't need a full set of 60-74 gear to get chaos, just a set that *contains* a single 60-74 item.

I went over the bit of code that does this when fixing another issue, but it does indeed make complete sense as to why it's built this way.

I want to clarify that if you are, however, we do account for the lack of item level 60-74 items, as well, and update the filter accordingly (i.e. add the lines for ilvl <= 60, ilvl >= 74 back into your filter).

This is all done depending on what you need to complete your sets.
