### ISSUE TITLE
Select install folder

### ISSUE THREAD

**Issue by MaxMatviienko** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#337]
Please add the feature to select where to install the tool, instead of auto-installing it to system disk folder.

**Comment by HiMarioLopez** [comment]
Thanks for the tip! I went ahead and pinned #243 which captures this feature request. If you have any more comments on that related issue, please post a comment on there.

If you have another feature request, please don't' hesitate to post a new issue on this forum. Cheers!
