### ISSUE TITLE
[Intended] v1.5.1/ v1.5.2 Creates New Settings File; Settings are 'Reset'

### ISSUE THREAD

**Issue by Jaxxas** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#343]
I updated from 1.5 to 1.5.1 an all my info was deleted and reset.

**Comment by HiMarioLopez** [comment]
That was noted on the release notes, apologies. It fixed a critical bug that caused the app to crash on startup https://github.com/kosace/EnhancePoEApp/issues/333

**Comment by HiMarioLopez** [comment]
And to be clear, you settings haven't been deleted, they're simply in another folder

For me they were located here: (this may look very different for you)

C:\Users\mario\AppData\Local\EnhancePoE\EnhancePoE.exe_Url_bipp1lws5g5rqeubwwougjxajwaibgnj

![image](https://user-images.githubusercontent.com/23390842/168314516-37160c69-7eca-417a-b806-3f2f78e78f0d.png)

So, if you had some really fleshed out custom settings, you could go and reference your file and even copy and paste the settings into your new file, just make sure the naming conventions follow the new settings base. Again, apologies for the inconvenience.

**Comment by HiMarioLopez** [comment]
And to add on, I do not planning on doing this again until there's another major feature release that requires me to modify the existing settings structure. Thanks for your understanding
