### ISSUE TITLE
v1.5.1 installer install v1.5.0

### ISSUE THREAD

**Issue by ocombe** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#344]
The installer for v1.5.1 listed in the releases actually installs v1.5.0 (which has the "not starting" issue).

**Comment by HiMarioLopez** [comment]
fixing rn

**Comment by HiMarioLopez** [comment]
should be fixed, let me know if anything else is needed fam

**Comment by ocombe** [comment]
Thanks !
