### ISSUE TITLE
1.5.1 Item Icons are missing on the overlay.

### ISSUE THREAD

**Issue by Jaxxas** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#346]
![image](https://user-images.githubusercontent.com/12674007/168317710-f3d73459-c582-475f-82aa-0b47a5835347.png)

![image](https://user-images.githubusercontent.com/12674007/168318099-3a1a831d-3cc7-4176-a15a-1610f02bf822.png)

Item icons are missing on the display since I updated.

I then uninistalled completely and downloaded the fresh 1.5.1 MSI and installed, set up from scratch. Still missing.

**Comment by tomeresk** [comment]
Having the same issue (also tried re-installing without success)

**Comment by HiMarioLopez** [comment]
fixed https://github.com/kosace/EnhancePoEApp/pull/347 please download 1.5.2 thx for the issue report
