### ISSUE TITLE
[Intended; Bad Design 😅] If PoE Trade API is down, App Will Not Start

### ISSUE THREAD

**Issue by hb-wright** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#348]
I updated to the latest version, and now it will not open. Double clicking the exe causes a brief wheel on the mouse, and then nothing. I uninstalled, also deleting relevant files in AppData, restarted, reinstalled, and same issue. Are there any logs where I can provide more info?

**Comment by itzome** [comment]
i have the same issue even after cleaning up the APPDATA folders. And reinstalling different 1.5.x versions

**Comment by romankuz19** [comment]
Same

**Comment by krterberg** [comment]
Same thing here on a fresh install (first time user so no existing config).

**Comment by romankuz19** [comment]
Probably its deactivated for some time, before the patch

**Comment by hb-wright** [comment]
Seems this is just because the trade API is down. Found this pinned message on discord:

> RE: v1.5.X App won't open
> 
> shitty design on my party but if the API is down the app won't launch, the API wll come up like an hour before league launch, so you'll have time to put some settings for your new install

**Comment by HiMarioLopez** [comment]
Copy pasting from our discord:

RE: v1.5.X App won't open ahead of 3.18 league launch

shitty design on my party but if the API is down the app won't launch, the API wll come up like an hour before league launch, so you'll have time to put some settings for your new install 

a good test is basically if https://www.pathofexile.com/trade is up  the app should*** work

**Comment by HiMarioLopez** [comment]
To be clear, I wish to change this in the near future. Just waaay to close to league start to change this behavior. Next patch for sure! Along with tons of other improvements to the error reporting
