### ISSUE TITLE
2 days of non-stop trying to make this work

### ISSUE THREAD

**Issue by boksken** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#35]
For the last two days i have been trying to make this overlay work for me. I have installed and removed it more times then i can count, but for some reason it just will not work. 

First of all, i connect to POE with steam. When i check the POE website, to see Manage Connections, it shows my email and also my secondary login (steam), Epic Games is not connected. 

The account name (is that the name of the character that i am playing with or is this my steam number or something else? I have been using my character name. 
I have reconnected many times on the poe site to get a fresh session ID, so that should be correct. 
The League I am using it for is:  Heist (i just have it like this, no other numbers or anything)
Full threshold I have tried 0, nothing and 3 or 4.
Refresh rate was set to 15 or 30.
Fill Greedy mode, checked or not 
StashTab mode: Prefix, Stashtab Prefix (i use the name of the quad tab), I did try to use the ID too and set that to 0 or 0,1 
Lootfilter checked and the correct filter is being used too. 
I also did keybind all the overlays
Highlight mode, set by set or item by item.

What i do for the test is: I am in my stash tab, the correct one in the right place - when i press STASH i get the popup: 
No Stashtabs available! Fetch before opening Overlay. So, the other times i just dont even use Stash and just go for Fetch Start - at this point i always get the message: Not Found (error fetching data)

I really hope there is a way to make this work, this overlay is something that will make me enjoy playing POE again. Because not everybody is a fast gamer where they only need this for a day or two. I would be enjoying this for a long time. 

Thanks in advance for any hints or tips

**Comment by boksken** [comment]
I have tried using Chaos Recipe Enhancer 1.1.2 and 1.1.3

**Comment by kosace** [comment]
Hello,

you have to use your account name not your character name.

When you login into poe website it is the name in the top left. You can read there:
"Logged in as kosace" in my case.

**Comment by boksken** [comment]
Brilliant that did the trick!
A last question I have is: after pressing on Stash there doesnt seem to be an edit button to line everything up, after pressing it again i am getting the error you see in the picture.

https://i.gyazo.com/c84a1a35c0d2c30bc6176aa8da437406.jpg
https://i.gyazo.com/7b0854a38364ca1da4ea27e3cb4f0414.png
https://i.gyazo.com/595906f372934260be190a44b4000720.png

Do you have any suggestions regarding this? So looking forward to utilize this :)

**Comment by kosace** [comment]
In the stashtab overlay at the very top there is the "Edit"-button.

For the error: do you use v1.1.3 now?

**Comment by boksken** [comment]
Using 1.1.2

**Comment by kosace** [comment]
there is a common crash fixed in 1.1.3. Could be the same. It occurs after fetching usually.
