### ISSUE TITLE
[Suggestion] Add a popup when POE is down that explains the program dosn't work without the API.

### ISSUE THREAD

**Issue by Jaxxas** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#350]
To minimize issue reports.

**Comment by CoffeeAndLoot** [comment]
I submitted on a pr for this issue. #351

**Comment by HiMarioLopez** [comment]
For sure. 

To be clear, I should decoupling an external API crashing our app before it even starts, it's really terrible design!  🙃

But in general this suggestion is right on the mark. 

I want to implement a new Error handling / reporting system in the future, with logs that can get generated on a per-user basis to better troubleshoot some of the trickier bugs that are reported. It's definitely on the list of improvements for the next release (1.6.0)
