### ISSUE TITLE
1.5.2 Not opening 

### ISSUE THREAD

**Issue by rayz0101** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#353]
I've tried the [solution](https://github.com/kosace/EnhancePoEApp/issues/333#issuecomment-1123727191) listed for 1.5.0 (appdata delete) but the app still will not open. 1.5.1 was working but the auto update seems to have bugged it. I'm switching back for now.

**Comment by HiMarioLopez** [comment]
See https://github.com/kosace/EnhancePoEApp/issues/348

**Comment by rayz0101** [comment]
Oh god I'm retarded, why didn't I think of that realm is down with all API and session id fetch.
