### ISSUE TITLE
[Bug] [Overlay] Item class icon opacity not reflecting item amounts when "Do Not Preserve" setting is enabled / disabled

### ISSUE THREAD

**Issue by InsanityPrelude** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#354]
Having more helmets than required when showing item amounts by Missing will show a negative number of helmets still required and never update the filter.

![image](https://user-images.githubusercontent.com/38642020/168414503-1d615c2f-55fb-4d5c-8bdf-32575bfa0f25.png)

**Comment by InsanityPrelude** [comment]
This is apparently the case for all of them?  It just seems like Body Armor was the only one willing to shut off once I had "enough." It also continuously says I have 0 sets.

**Comment by NattyPew** [comment]
Having the same issue, except I use the total amount of items instead of missing. It has only detected body armors as being over my limit of 6, while I currently have 25 boots and it doesn't seem to care.
Also showing 0 sets, so I can't use it for selling, even though I should have 9 sets.

![image](https://user-images.githubusercontent.com/38313657/168466433-88fe224e-3a6b-4434-a2f3-a0c4473297cc.png)

**Comment by InsanityPrelude** [comment]
@NattyPew So actually, I was able to resolve this problem eventually!  I reset my configuration and then reinstalled the latest release of the enhancer and it worked fine afterwards.  I'm not sure what it was about, really...

Overall it just seems a bit finicky at the moment.  Most amusingly, a number of my guildmates including myself discovered that after running for a while and using the Reload Filter button several times it would no longer send the correct command to reload the filter, rather it would just repeat the last thing that I had sent into chat, usually something from my clipboard.  I had to apologize to some guy after asking to buy his jewel like five times in a couple of hours because of it.

**Comment by Aradiv** [comment]
i have the same issue and tried deleting config and reinstalling the tool completly but neither solved the issue.
I get a correct set count but i have multiple negative requirement icons.
And none of the Items is set to "Always active"

**Comment by HiMarioLopez** [comment]
> after running for a while and using the Reload Filter button several times it would no longer send the correct command to reload the filter, rather it would just repeat the last thing that I had sent into chat, usually something from my clipboard. I had to apologize to some guy after asking to buy his jewel like five times in a couple of hours because of it.

Howdy, this is something I've been trying to tackle for a while. 1.5.4 had some changes to the clipboard situation, hoping it would resolve it. It has indeed helped a few users out but let me know if it still is affecting you.

As for the other issue at hand, do you guys have the "Do Not Preserve Low Item Level Gear" ticked on or off?

**Comment by NattyPew** [comment]
> As for the other issue at hand, do you guys have the "Do Not Preserve Low Item Level Gear" ticked on or off?

I have it ticked off, since all of the items are ilvl 65-75

**Comment by InsanityPrelude** [comment]
I had "Preserve Low Level Gear" disabled.  Like I said though, the issue seems to have been resolved for me personally when I went ahead and reinstalled the program.  It looks like the behavior of that toggle has switched to "Do Not Preserve Low Level Gear" in the latest version.  I was previously playing with 1.5.2

**Comment by HiMarioLopez** [comment]
Heyooo, can I get a screenshot of y'alls' settings please?

**Comment by HiMarioLopez** [comment]
Ok so I got confused for a second. There are 2 issues at play here.

One discussing negative item amounts not fading out even though the requirement for that has been met. This makes sense, it sounds like a but for sure. I'll be looking at the code for that bit.

Another one sounds like potential user error, which InsanityPrelude has solved with a reinstall. I'd tick "Do Not Preserve Low Item Level Gear" and see if your issue is resolved @NattyPew. By default, the setting is checked.

@Aradiv I now see the issue you were having. I'll look into this.

**Comment by HiMarioLopez** [comment]
Ok I was finally able to replicate the issue.

![image](https://user-images.githubusercontent.com/23390842/168887021-21fdcd37-314f-4c7b-b2a7-00334acd3c36.png)

Here is what we would expect it to do, notice the "Do Not Preserve Low Item Level Gear" setting is enabled.

![image](https://user-images.githubusercontent.com/23390842/168887095-1ffc2a6f-db58-4687-a443-82b507714c63.png)

Here is what some of you guys are seeing. Items that are at 0 should be faded out, and in general my values are off for the total number of sets I have to turn in (theoretically).

My general idea is... "Do Not Preserve Low Item Level Gear" setting is messed up quite a bit under the hood. If you can, CHECK THE BOX. Retest after you've done so and let me know if it solves your issue.

**Comment by HiMarioLopez** [comment]
Here's a related (but not 100% similar) issue caused by the "Do Not Preserve" setting.

https://github.com/kosace/EnhancePoEApp/issues/384

**Comment by NattyPew** [comment]
That does look like it could be the issue, considering mine says "Preserve low item level gear" 
![image](https://user-images.githubusercontent.com/38313657/168900028-6975dd2c-4c58-4768-bb59-830fffa3b98e.png)

**Comment by HiMarioLopez** [comment]
You need to update your app @NattyPew . The setting is mislabeled on the previous version. The new setting more accurately represents what it's trying to do.

**Comment by NattyPew** [comment]
Aight yeah it's working perfectly fine now. Updated and checked it
![image](https://user-images.githubusercontent.com/38313657/168901181-d091d055-d207-429a-be06-00c4175229e5.png)

**Comment by Aradiv** [comment]
Withot Do not preserve Low Item Level Gear:
![image](https://user-images.githubusercontent.com/764172/169710033-2fd6224b-70b7-4a5c-86ab-eac99cf5ff77.png)

With do not preserve Low item Level Gear
![image](https://user-images.githubusercontent.com/764172/169710102-264acb33-b1db-42cd-9723-1d6b8152b531.png)

So in my case it looks like there is no difference between the two options.

**Comment by HiMarioLopez** [comment]
Duplicate of https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/384

Root cause of icon opacity is the values being inaccurate when fill greedy mode is toggled off
