### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Nyxion** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#355]
Trying to map CTRL+ALT+SHIFT+F6 as a key bind for overlay, but every time I press CTRL the application crashes.
Edit#1:
Also SHIFT+ [0-9][A-Z] produces the same crash.

Is there no log or anything I can look at?

Edit#2:
Infact pressing SHIFT anywhere in windows makes the application crash, no matter if my browser is in focus or poe or whatever.

Why does it listen for hotkeys globally? and def better with only while poe window in focus.
## Specifications

  - Version: [EnchancePoEApp 1.5.2](https://github.com/kosace/EnhancePoEApp/releases/tag/1.5.2)
  - Platform: Windows 11
  - OS Version: 22000.675

**Comment by Nyxion** [comment]
Also SHIFT+ [0-9][A-Z] produces the same crash.

Is there no log or anything I can look at?

**Comment by HiMarioLopez** [comment]
Deploying this in a hotfix later today. Thanks again for your help.
