### ISSUE TITLE
Crashes everything I press Fetch

### ISSUE THREAD

**Issue by xrande** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#357]
I can't seem to get my EnhancePOEApp to work. It crases everytime I press F. Using latest version 1.5.2

I have uninstalled and reinstalled the app, no changes. I setup the stash tab settings using ID. I have it the first tab on my stash.

EDIT: I restarted Windows and works now.
EDIT2: Crashed again

![image](https://user-images.githubusercontent.com/81092399/168475955-4060f41f-a5e7-47b4-b9a9-575eec832935.png)
![image](https://user-images.githubusercontent.com/81092399/168475969-68c5645e-16e4-4567-8a75-91f4f74ad952.png)

**Comment by xrande** [comment]
Didn't really do anything and it is crashing again on Fetch.

**Comment by NameTrillion** [comment]
Same thing happens to me, nothing I have done to troubleshoot has fixed it.

**Comment by HiMarioLopez** [comment]
can y'all try again on v1.5.3 pls and let me know if the issue persists?

**Comment by xrande** [comment]
> can y'all try again on v1.5.3 pls and let me know if the issue persists?

Seems to be working. Thanks for the update. Will re-open if any more issues persist.
