### ISSUE TITLE
loot filter manipulation not working.

### ISSUE THREAD

**Issue by gotya96** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#361]
So for some reason CRE isn't modding my lootfilter, not sure what has happened.

The overlay works and is updating depending on what i put in, but the filter isnt changing.
Rings, amulets and belts are modded with the correct colour, but everything else is normal.

I've tried reinstalling, resetting settings and deleted/added new filter. Filters are not "read-only"

![Screenshot_4](https://user-images.githubusercontent.com/65258119/168484089-695bf2ce-ed88-4211-9e36-27aed31037b4.png)
![Screenshot_5](https://user-images.githubusercontent.com/65258119/168484090-daaf924a-111c-4c2f-b65f-0e18cbcaced1.png)

**Comment by HiMarioLopez** [comment]
https://github.com/kosace/EnhancePoEApp/commit/de326983dee2d0488bfc40bc796648560b5095c0

Just committed* in some changes for loot filter manipulation command being a bit buggy. Basically wasn't updating the files all the time you hit the button. I will be releasing this fix in the next patch, thanks for your issue report!
