### ISSUE TITLE
Items not Highlighting/Showing Sets as completed.

### ISSUE THREAD

**Issue by ERS7187** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#365]
I have multiple sets completed in the stash tabs i designated to work with the app. However, It is showing that there are zero completed sets. In addition, when Pulling up the stash tab overlay there are no items that are getting highlighted in the stash tabs telling me what to sell
![CRE_Snap](https://user-images.githubusercontent.com/105613735/168500487-27c933b5-b368-4776-8331-a0f10d37a7c1.PNG)

**Comment by HiMarioLopez** [comment]
Update to the newest version (v1.5.3) and try checking the setting box for "Do Not Preserve Low Item Level Gear" and let me know if the issue persists. Thanks

**Comment by HiMarioLopez** [comment]
I have a feeling this is related to https://github.com/kosace/EnhancePoEApp/issues/354

Try enabling that setting and let me know if that's what caused it. I may remove the checkbox in the future and just default it to that. 

Closing to keep issue board clean... let me know if I need to re-open this.
