### ISSUE TITLE
[Enhancement] [General] Auto-focus Hotkey window when it's opened

### ISSUE THREAD

**Issue by HiMarioLopez** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#366]
Title. When I open the window to change a hotkey, I need to click on the window that spawns before I can set a new hotkey. This is a small inconvenience. I'd like to get this fixed in the near future, but it could also be a neat opportunity for someone to get into the codebase and make this small change to enhance the app.

The main file you'll want to reference for this issue is:

EnhancePoEApp\EnhancePoE.UI\View\HotkeyWindow.xaml.cs

**Comment by misaelitox** [comment]
I would like to work on this issue in order to get it fixed.

**Comment by HiMarioLopez** [comment]
Ask and yee shall receive, my good sir. I have some setup instructions for running the application locally on the end of the README.md

Ping me on discord @ Meatbox#1607 if you have any questions at all! I'm always happy to help in any way

**Comment by misaelitox** [comment]
Hey, I will work on this issue tomorrow since it's 11:48 PM here, so I will take a look at README file first, If I have any doubts or questions I'll contact you on Discord, thank you!

**Comment by HiMarioLopez** [comment]
Forgot to close, appreciate your contribution @misaelitox 

Your changes live here (and have long been merged into our app!): https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/395
