### ISSUE TITLE
Settings not saved - Stab Tab error

### ISSUE THREAD

**Issue by xrande** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#368]
Getting Stash Tab error when I press Fetch. It keeps referring to it as indices/index even when my setting is already Prefix with CR

The app then stay in the background even after it crashes. Have to end task to completely kill it.

I checked the config file EnhancePoE.exe.config. My settings in the UI seems correct, but in the config file might not have been saved.

```
<setting name="StashTabMode" serializeAs="String">
        <value>0</value>
      </setting>
      <setting name="StashTabName" serializeAs="String">
        <value />
      </setting>
      <setting name="StashTabIndices" serializeAs="String">
        <value>0</value>
      </setting>
```

![image](https://user-images.githubusercontent.com/81092399/168572132-3b85ef35-44cd-4157-a9c8-9070101e80cc.png)
![image](https://user-images.githubusercontent.com/81092399/168572150-c3623faf-6cdc-41d8-8907-0a403c5604a7.png)

![image](https://user-images.githubusercontent.com/81092399/168571725-b6ec7a4c-546d-4a77-818b-29400005c1e3.png)
![image](https://user-images.githubusercontent.com/81092399/168571825-463b6df7-1826-4145-9041-064a571edbb4.png)

**Comment by VeeTeg** [comment]
I experienced the same issue after updating to version 1.5.3

**Comment by xrande** [comment]
I deleted my settings folder in the appdata. Seems to solve the issue.
