### ISSUE TITLE
Unexpected Error Occured

### ISSUE THREAD

**Issue by DocPaintfull** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#369]
the error throws sometimes when trying to hide the stash overlay, don't know any specifics yet but had it thrown several times since the new update, will give more information if I find some.

nuking the settings did not help.

![chaosrecipeenhancerError](https://user-images.githubusercontent.com/28151033/168643524-d2aa69d7-6bd4-4884-9026-e4b3a5e5ad84.png)

edit: it always happens when i press fetch while the overlay is already opened.

**Comment by HiMarioLopez** [comment]
Oh man I'm not fluent in German but I'll try my best to decipher your issue. Thanks for the report!

**Comment by DocPaintfull** [comment]
oh i am sorry, it's basically just the german version for a nullpointer exception (object reference was not instantiated)

**Comment by DocPaintfull** [comment]
it always happens when i press fetch while the overlay is already opened.

**Comment by xrande** [comment]
> it always happens when i press fetch while the overlay is already opened.

I am experiencing the same thing. If I on the item overlay, then press fetch, that error will constantly pop up.

**Comment by Yvreska** [comment]
![POE](https://user-images.githubusercontent.com/105715986/168792790-44798839-263e-4a03-a475-3cf7a5a6e253.jpg)

i have the same problem, what should i do? my ver 1.5.3

**Comment by HiMarioLopez** [comment]
I am closing this issue as it is a dupe and already being tracked at #381 

> ![POE](https://user-images.githubusercontent.com/105715986/168792790-44798839-263e-4a03-a475-3cf7a5a6e253.jpg)
> 
> i have the same problem, what should i do? my ver 1.5.3

I have created a new issue to highlight this issue at #382. Please add comments to that issue if there is anything to add, thanks!
