### ISSUE TITLE
Setup Problems / Visual Problems

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#374]
Hello,

I just found your tool and wanted to give it a try because I am way to lazy to check all those items myself and keep track of them.
So after fiddling around I still have 2 problems.

First is a visual one:
![image](https://user-images.githubusercontent.com/627469/168670250-06437a17-8d3f-478b-94fd-752cf755f43a.png)
For me it's extreme hard to read the tabnames (which also was my first problem in finding out how to select the correct tabs). Would be nice if the font might be switched a bit and in the edit a toggle for players that use just normal tabs to have their default size, because no matter how I move the sliders they are always very off.

My second problem is the tab-setup. I don't know if it is because of the amount of tabs I have but I have had this problem already with a few other tools where you had to manually give the ID of a tab. It would be extremely convinient if we could get a list of our tabs to select them by clicking. This also helps when you move your tabs around and lose absolute oversight of the ids behind the tabs.
Also listing them in the settings as NAME (ID: xx) would be great with a smal indicator if the tab has been loaded, problems or anything. As the API (thanks tranding bots) is currently molested again it can happen that the stash tabs can not be read properly and for me, setting up the tool, its hard to determine if I made a boo boo on configuration or if the API just blocked the tab fetching, as currently all tabs are marked as if there is no item in, while I put a few items into the tabs.

thanks and keep up the good work

**Comment by HiMarioLopez** [comment]
Howdy! Thanks for opening this issue

> For me it's extreme hard to read the tabnames (which also was my first problem in finding out how to select the correct tabs). Would be nice if the font might be switched a bit and in the edit a toggle for players that use just normal tabs to have their default size, because no matter how I move the sliders they are always very off.

There are definitely plans to add more UI customization options for the stash tab overlay. The priority is not high, to be completely honest with you, but it is something that is on my mind as I continue to work on the app.

https://github.com/kosace/EnhancePoEApp/issues/309

For the font color, I feel like generally speaking we could simply default it to something more readable, maybe a bolder white text with a black border, which is generally quite readable in all circumstances.

![image](https://user-images.githubusercontent.com/23390842/168879729-f9c05c37-c4cd-4e16-a4ad-32305da11a73.png)

> My second problem is the tab-setup. I don't know if it is because of the amount of tabs I have but I have had this problem already with a few other tools where you had to manually give the ID of a tab. It would be extremely convinient if we could get a list of our tabs to select them by clicking. This also helps when you move your tabs around and lose absolute oversight of the ids behind the tabs. 

This is a good feature. Exilence Next does something like this. I'll draft a new issue to track it. This one will definitely be a ways out.

> Also listing them in the settings as NAME (ID: xx) would be great with a smal indicator if the tab has been loaded, problems or anything. As the API (thanks tranding bots) is currently molested again it can happen that the stash tabs can not be read properly and for me, setting up the tool, its hard to determine if I made a boo boo on configuration or if the API just blocked the tab fetching, as currently all tabs are marked as if there is no item in, while I put a few items into the tabs.

This would pair well with the expanded stash tab overlay customizations. Give users the settings to display their tabs how they want. Formats could include: "Name", "ID", "Name (ID)" or something like that.

> thanks and keep up the good work

Thank you for using the tool and for the general support! Let me know if you have any other questions at all.

I will close this thread up, and follow-up with creating the new issues as stated. Thanks again, cheers.
