### ISSUE TITLE
acces denied

### ISSUE THREAD

**Issue by br0cha** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#375]
[](url
![chaos](https://user-images.githubusercontent.com/105683933/168701338-44099bd2-4091-4060-b08c-6bede526981b.png)
)

HALP
everytime that i click filter manipulation...

**Comment by HiMarioLopez** [comment]
Looks like... your access is denied. See if you can run the app in admin mode, or if you're running an anti-virus try adding it to the list of exceptions. Thanks

My takeaway: Improve error handling for access issues (e.g. Display "Access Denied: Try re-running in admin mode?")
