### ISSUE TITLE
Filter not respecting number of items stored

### ISSUE THREAD

**Issue by bezhadeath** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#377]
I have noticed that the filter doesn't always respect when the maximum number of items are stored already. For example, in this scenario I have configured set threshhold as 4:
![image](https://user-images.githubusercontent.com/18376675/168799650-733fd4d0-b639-44ba-8a5c-bffcc0123dcd.png)

I already have -1 chests, meaning I have stored 5 chests already, however the filter is still telling me to pickup the chest from the ground when it drops:

![image](https://user-images.githubusercontent.com/18376675/168799733-125d5698-efe6-4802-9fbe-c2b17d24af16.png)

**Comment by HiMarioLopez** [comment]
Did you reload the filter after fetching? It doesn't auto-reload. You have to click the "R" button.

**Comment by HiMarioLopez** [comment]
If the above works, awesome! If it doesn't, we can re-open this issue and troubleshoot some more.
