### ISSUE TITLE
Suggestion: Add possibility to recognise stash tabs by suffix.

### ISSUE THREAD

**Issue by tamaroth** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#38]
Currently, you're providing an ability to recognise the stash tabs by either an ID (index) or by a prefix. It would be great if it was possible to recognise tabs by suffix. In game it is possible to have priced tabs with a custom suffix, for instance: `~price 10 chaos - 01`, `~price 10 chaos - 02` - both tabs will be listed for 10c and it makes easier for you to recognise which tab the buyer wants an item from. Adding an ability to recognise tabs by suffix, allows us to have multiple dump tabs listed for different prices which would be taken into consideration for chaos recipe, but would exclude other, unwanted, tabs from being included (like a fixed sell tab).

Currently, it is only possible by listing all ID's, which is a tad tiring.

**Comment by thebeast792** [comment]
Or even add the ability to use regular expressions

**Comment by george-delchev** [comment]
Hello @HiMarioLopez , I saw you assigned this to yourself, but I decided to take it just to get more familiar with the code, hope that's ok. If you haven't started it yet, I can do a Pull Request tomorrow.

**Comment by HiMarioLopez** [comment]
> Hello @HiMarioLopez , I saw you assigned this to yourself, but I decided to take it just to get more familiar with the code, hope that's ok. If you haven't started it yet, I can do a Pull Request tomorrow.

Perfect! I just assigned myself to some stuff I 100% wanted to include in the next release. Thanks for doing this! I have not started on this so you are free to take this one up. Let me know if you have any questions at all

**Comment by george-delchev** [comment]
Sorry for the delay, haven't used github much so I thought I would receive notifications here, and didn't check my mail.
