### ISSUE TITLE
[Bug] [Overlay] Item amounts are inaccurate when "Do Not Preserve" setting is not checked

### ISSUE THREAD

**Issue by C3ntraX** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#384]
**Problem:**
The app has problems with combinations of items:
Belts and maybe other combinations are not considered with:
Do Not Preserve Low Item Level Gear: Off

In the screenshots you see, that I need -20 Boots with 0 combinations found..
But acutally, there are at least one combination see the screenshot.

Additonal, the "-" indicatior is confusing. 
Its calculated by the number of items in the stash: I have 20 belts in range  ilvl  < 75 and it shows "-" 20 and is not greyed out what it shoud be, but I think this is related to the bug.

**What is should be:**
In the screenshould below, you see that belts are not used as item in range 60 to 74 and the others in range >= 75.
With at least one item should be below 75 and the others >= 75. There should be many combinations possible, but the ui isn´t updating and does not register this combinations. With the screenshots below, you see that I have found one combinations.

**Settings:**
Do Not Preserve Low Item Level Gear: Off
Items Missing: Off
Full Set Threshold: 1

**Screenshots:**
Sorted stash:
above: Items with ilvl  < 75
below: Items with ilvl >= 75
![image](https://user-images.githubusercontent.com/44802503/168894729-fa9f2450-b87e-41d4-b635-67b62398d3fc.png)
![image](https://user-images.githubusercontent.com/44802503/168895004-cfdf4171-afae-4e5d-baea-67c92f82b87a.png)
![image](https://user-images.githubusercontent.com/44802503/168895489-4d78dc64-721f-40d4-b971-32216c284b06.png)

**Edit:**
Show Item Amounts: Items Missing - This was previously enabled too (forgot sry)

**Comment by HiMarioLopez** [comment]
Literally discussing with another dev about the confusion "Do Not Preserve Low Item Level Gear" causes at this very moment. If you disable it, does it work as intended for you? Visually and when handing in sets?

**Comment by C3ntraX** [comment]
"Do Not Preserve Low Item Level Gear" is disabled and causes this problem.

**Comment by C3ntraX** [comment]
If I enable this, the app will find the combination. But I think the idea with only 1 item below 75 is really good, but don´t work as expected.

**Comment by C3ntraX** [comment]
Ok I adjusted the Settings:

**Settings:**
Do Not Preserve Low Item Level Gear: Off
Items Missing: Off
**Full Set Threshold: 2**
Show Item Amounts: Items Missing - This was previously enabled too (forgot sry)

![image](https://user-images.githubusercontent.com/44802503/168898408-0e36ea40-73a3-498b-8142-cbbf13fae821.png)


What it should be:
Sets: 1
Missing Boots: 1

**Comment by HiMarioLopez** [comment]
Understood, I agree. I'll have to do a deep dive on the feature and ensure it's working as intended.

In general, I'm thinking of moving / hiding it from users until I can work on fixing the visual confusion it causes (since it's buggy).

**Comment by HiMarioLopez** [comment]
I am changing the title of this issue to generalize it and point users to this when they run into similar troubles. I will keep in mind the constraint you provided me with of the ilvl 75+ items causing the issue.

**Comment by C3ntraX** [comment]
Ok, thank you. Very nice tool, good job.

**Comment by C3ntraX** [comment]
Hi @HiMarioLopez,

I it helps:

![image](https://user-images.githubusercontent.com/44802503/168902137-2a5fbe67-5691-4400-a1a2-040c202e7356.png)

- Same settings

Added:
+1 boot ilvl: 82.  Currently 2 boots both ilvl 82

![image](https://user-images.githubusercontent.com/44802503/168902154-db7a923e-f96f-405f-8a21-3c966ce73ee4.png)

Now the tool found one set.

Its wreid, it seems, the tool doen´t register the first boot. But it checks now, that it can use one belt below ilvl 75. Wreid.

**Comment by HiMarioLopez** [comment]
The internal rule when the setting is **off** is to allow only ONE iLvl 60-74 item per set

The real bug is how the visuals are completely off cuz it's counting all items it finds above ilvl 60 in the visual UI component

**Comment by C3ntraX** [comment]
Yes, I understand it, but it should list 2 sets or not? Because the tool can take 2 boots ilvl < 75 and 2 belts from the right ilvl < 75?

EDIT: "2 boots ilvl < 75"

**Comment by HiMarioLopez** [comment]
Yes! Apologies, that's definitely a bug

**Comment by HiMarioLopez** [comment]
.

edited cuz i'm dumb

**Comment by C3ntraX** [comment]
above: Items with ilvl  < 75 -> Chaos receipe valid
below: Items with ilvl >= 75

**Comment by HiMarioLopez** [comment]
My brain is fried after a full work day.

This further confirms this is bugged, but provides me with better context for where the code may be incorrect, thank you for clarifying everything here

**Comment by C3ntraX** [comment]
Sry yes I edited my comment. "2 boots ilvl < 75" Haha I think my brain is exhausted too xD

**Comment by C3ntraX** [comment]
![image](https://user-images.githubusercontent.com/44802503/168911322-a28fc69c-3f95-4ba2-9887-86d6ee0d8363.png)

![image](https://user-images.githubusercontent.com/44802503/168911408-d2a8d3c9-5655-4859-ab08-9fffdd0afbd8.png)

**Comment by HiMarioLopez** [comment]
Good title edit 😅

**Comment by HiMarioLopez** [comment]
So here's the scenario recreated, but made simpler:

![image](https://user-images.githubusercontent.com/23390842/168912261-3fbfdb07-35e2-4397-8338-f6e043c1207b.png)

![image](https://user-images.githubusercontent.com/23390842/168912288-d56def50-b26e-4430-a1a3-d72a865de8b3.png)

So we have a set that contains 6/ 8 items that are higher ilvl, and the 2 remaining items at 60-74.

Everything is 0'd out in terms of items missing, but 0 full sets. So yeah, that needs to change.

Doesn't add much to the issue, but just letting you know I now have the proper testing environment for this and I'll be working to fix it soon. Thanks again for all of your information.

**Comment by C3ntraX** [comment]
HI @HiMarioLopez,

do you think there is good way to display the information if items below ilvl < 75 are missing? 

There could be a problem too, because if you have all items >= 75 and you don´t have any items <75 I don´t know, if there is a proper way to show this information.

Maybe the lootfilter should only show the missing items < 75 and there should be a counter for missing <75 items.

This way you are able to pick <75 items up and the counter decreases. The item type you picked up decreases the item for the specific type for >= 75 counter. 

What do you think?

**Comment by ccppprogrammer** [comment]
It still incorrectly counts items in my 3 chest tabs.
As you can see I have a bunch of amulets available but the tool shows 72 is required.
I am using the latest version 1.5.5.

![image](https://user-images.githubusercontent.com/7936874/169337651-608c43b2-7b12-44de-a044-f8828ed834b7.png)
the same for rings.
![image](https://user-images.githubusercontent.com/7936874/169337930-034e90bf-6a3d-4c6e-a0c0-0e5a85085806.png)

**Comment by HiMarioLopez** [comment]
> It still incorrectly counts items in my 3 chest tabs. As you can see I have a bunch of amulets available but the tool shows 72 is required. I am using the latest version 1.5.5.
> 
> ![image](https://user-images.githubusercontent.com/7936874/169337651-608c43b2-7b12-44de-a044-f8828ed834b7.png) the same for rings. ![image](https://user-images.githubusercontent.com/7936874/169337930-034e90bf-6a3d-4c6e-a0c0-0e5a85085806.png)

Since the creation of this issue I have made 0 code changes to that bit of code… I’m not sure why you’d expect it to magically work today 🫠🫠🫠

when the code is updated / fixed I will close this issue and post a new release 

my suggestion is to keep the setting checked until further notice

**Comment by ccppprogrammer** [comment]
Any news on this? It's like the most critical bug out there. I thought it would be fixed at the start of the league.

**Comment by HiMarioLopez** [comment]
No news yet! I just haven't had the time to look more deeply into the root cause of this issue.

It's clear to me that most users prefer to play with the "Do Not Preserve Low Item Level Gear" setting toggled on, as (we make it the default).

The main use case for the tool is the first 1-3 days of league start. After that, the preservation of items becomes a non-factor since most folks into the higher-tier red maps will earn more from their atlas strategies than they would for the chaos recipe.

All that to say, it's a lower priority but still very much an issue that needs to be resolved. As always, I welcome any community member to take a look at the code on and I'm always happy to discuss any findings with them.

**Comment by kamilrogo** [comment]
I think I have the same issue. I disabled "Do not preserve..." (I wan't to do recipes with only 1 low ilvl item) and program can't find set (but I can see there is a set). I made a copy of my stash tab json to help you debug this: https://pastebin.com/tsXqLJpY 
![image](https://user-images.githubusercontent.com/27273043/186890556-d46721ae-56d8-42cd-a36a-e819461bcf89.png)

**Comment by pmcthor777** [comment]
I really would like this issue be resolved as I play SSF so chaos recipe is really important to me throughout the entire league. I'm currently have my low level gear in a separate tab and I add those into the tracked tab manually for each batch. It's a bit of a pain to do.....

**Comment by HiMarioLopez** [comment]
This should be fixed (didn't realize I had this duplicate issue still up)

From https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/495:

> I have re-enabled the setting after patching the conservative set composition algorithm It will be released with the latest release.
> 
> Both Greedy and Conservative algorithms are integrated with the new "Turn In Sets Early" option. This will be released early next week. Thanks for your patience!
> 
> related changes:
> https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/2159a96a3f9008d172da017c941983a249f0bb2f
> https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/dd06391a1aedc7ec431433952b60137e48f74fc3
> https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/e0043b2b4887311c57174587d1d0cb6e9dbeb79a
