### ISSUE TITLE
Chaos Recipe grabbing items that are lvl 75 instead of lvl 60-74

### ISSUE THREAD

**Issue by Moregaze** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#385]
Even if you have the Regal recipe uncheck, it is grabbing and loot filtering items that are lvl 75.  Which can not be used in the chaos recipe for the vendor.  I don't see a setting to change it so if this is something I can edit in the ini just let me know and I will.  If not thanks for the hard work and any help on this issue.

**Comment by HiMarioLopez** [comment]
So you only need a single 'chaos' item to get the recipe to work. The rest can be either chaos or regal (any i60+).

This is done intentionally to not force you to do low-level maps, and allow you to fill as many sets as you have chaos items.

**Comment by HiMarioLopez** [comment]
In the case of needing more low-level items to fill your recipes, we take that that into account, as well.

![image](https://user-images.githubusercontent.com/23390842/168955951-2c043589-6572-46df-a250-79bfd97732a4.png)

Above you'll a message a user gets when you are missing those lower level items.

On my branch https://github.com/kosace/EnhancePoEApp/tree/feature/data-refactor I actually have an improved message that tells you exactly how many lower level items you need to complete your desired sets. It should be merged into the main branch soon enough.
