### ISSUE TITLE
Critical error and some commentary

### ISSUE THREAD

**Issue by Moximus** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#388]
First off great tool - a couple critques

the link below is to an error that occurs when fetching or something
[https://imgur.com/a/nVps0oy](url)

The other is that once ive made 2 sets of the recepie in my inventory and then sell to the vendor - the tool wants me to click the empty spaces again before moving to the next recepie.

Anyhow - best league start ive ever had thanks to this tool - starting to learn crafting and feel like my build is coming alive finally.
Thanks to all involved

**Comment by HiMarioLopez** [comment]
Was this before or after updating to 1.5.5? We pushed a patch to fix this issue I think right as you reported another instance of it.

Can you provide some more context to your 2nd issue? Any steps you could provide me with to re-produce it

See: https://github.com/kosace/EnhancePoEApp/issues/381
