### ISSUE TITLE
Filter manipulation not hiding items. Overlay fails. 1.5.4

### ISSUE THREAD

**Issue by sclient** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#389]
Got full on 2 item types so far. Using unmodified NS Azurite SC Econ Standard (not online). It changes some colors and will put the map markers, but is happy to go into -items, reloaded many times and restarted. Tried putting both game and tool in admin, no luck.

Im in a PL if it matters (but it seems like the league and some filter manip works along with possesid). Checked windowed fullscreen. Vulkan (tried dx11, no luck). Have my 1st tab as quad, ID mode 0,1,2 (tried moving it, no luck).

Edit: testing new version (1.5.5), was using yesterdays update. Noticed it doesn't seem to save my settings between updates, though. 

Ok, got to a new zone in the new version and the overlay works again (showing item sets). Cant fully test the filter hiding right now, but at least the overlay seems to notice they should be invisible. Tried it on GG filter, but will have to mess with NS again tomorrow and report back.

Edit Again: Reverted back to having issue again (1.5.5). Stash overlay broken, item sets that are in negative not turning invisible on mini overlay, item filter manipulation broken.

Just noticed that turning off filter manipulation doesn't restore your filter to default, it just puts the highlighting on everything.

**Comment by HiMarioLopez** [comment]
Can you drop screenshots of all your settings screen, please?

If you have "Do Not Preserve Low Item Level Items" setting checked off, try turning it back on and re-fetching.

For any changes to the stash state (and in turn, filter state) to be refreshed, you need to re-zone. It's an inconvenience we cannot work around as it's how GGG's API is designed.

**Comment by sclient** [comment]
Ill grab those for you later, have tried playing with that setting.

(Disregard following, realized the fetching is fine, it is the rest that is broken) Now that I think about it, I have seen an increasing outcry about the trade API. Perhaps the tool working corresponds to non peak hours?
![1st setting](https://user-images.githubusercontent.com/32541/169411140-ae0f081c-9dba-4a3a-8b15-33bb8f4a52d8.jpg)
![2nd setting](https://user-images.githubusercontent.com/32541/169411225-bb21b78f-8263-4af5-a7da-8bd76a74c755.jpg)
![3rd setting](https://user-images.githubusercontent.com/32541/169411241-f4830ed9-8944-4df5-964f-9e18e713cee3.jpg)

**Comment by sclient** [comment]
Ok, so tried the low level item gear setting again, and that, indeed, does make the stash overlay work.

The hiding and such is still broken (notice the screenshot with boots-weps in -numbers, and still highlighted).

**Comment by HiMarioLopez** [comment]
Please download the latest version of our app and re-open a new issue if you run into any other problems. Thanks!

https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/1.6.0
