### ISSUE TITLE
Support 2x2 size shield as part of chaos recipe

### ISSUE THREAD

**Issue by szabokacsa** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#39]
Hi,
great work, but it would be even better, if the tool recognizes shield as part of the chaos recipe.
I think it is a huge addon. Thanks!

**Comment by szabokacsa** [comment]
Also support claws if possible.

**Comment by benOesing** [comment]
![image](https://user-images.githubusercontent.com/70664484/104112921-b0677480-52f4-11eb-82bb-8670361b1cb6.png)
This is in general a bad idea. The inventory has 12 * 5 = 60 spaces.
A single set for the recipe takes 59 spaces. You can see in the image, that the weapons take 3 spaces each. Shields and claws take 4 spaces each (2x2) so it would increase the needed space to 60/61, which makes it impossible to have 2 sets in the inventory if you are unlucky.

And the chaos recipe is rarely limited by the number of weapons.

**Comment by szabokacsa** [comment]
I see your point and understood it.
But at league start this take less time to trade sets one by one intead of finding the certain amount of weapon.
Maybe you can make a checkbox on GUI with a warning and the users can choose this option if they want.

It is just a suggestion. If you think is not a good idea, please close this issue. Thanks your time!

**Comment by jjepaah** [comment]
I understand your point but it shouldn't matter because jewelry is going to be the rarest of drops so you'll get the correct weapons way before you have enough jewelry to make the trade.
