### ISSUE TITLE
How to fetch automatically?

### ISSUE THREAD

**Issue by Booblord** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#391]
How do I fetch (update item amounts) automatically. I can only update by manually clicking on fetch, otherwise the items won't refresh at all. 
I can't seem to find the "refresh rate" option either

**Comment by dovry** [comment]
![image](https://user-images.githubusercontent.com/15201298/169708267-7c0fefdb-3e36-4e43-86aa-8670d9ae7419.png)

**Comment by HiMarioLopez** [comment]
Hoping the response provided by @dovry answered your question. Please check out the community Discord if you have any more questions:

https://discord.gg/H9vjmShY
