### ISSUE TITLE
1.5.0.0 using six socket weapons/armours in chaos recipe

### ISSUE THREAD

**Issue by dovry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#392]
![image](https://user-images.githubusercontent.com/15201298/169878780-3a9db3bf-32bf-43c1-80a8-e1db47bb86fd.png)

**Comment by HiMarioLopez** [comment]
Fixed in v1.5.4

> introduced more limited filtering on items to ensure we don't overwrite any of your loot filter's rules (e.g. 6-socket items, 5-link items, 6-link items, etc.)

Would recommend installing the latest version, v1.5.5

Thank you for your issue report, nonetheless.
