### ISSUE TITLE
Application settings not shared on upgrade

### ISSUE THREAD

**Issue by message** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#393]
After upgrading from 1.4 to 1.5, everything is blank.  I was expecting it to pick up the old settings from 1.4.

p.s. thank you for your work

**Comment by HiMarioLopez** [comment]
Yeah, sorry about that. It’s a known “issue”

I had to change the settings schema during that update and it basically would crash on startup if it attempted to load up your old settings. They are still there, technically, if you really wanted to manually import some of those settings.

See: https://github.com/kosace/EnhancePoEApp/issues/343

Thanks for your support!
