### ISSUE TITLE
Not detecting sets

### ISSUE THREAD

**Issue by GaryCommander** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#396]
The tool says I have 0 sets even though i have enough items in my stash to make one. It detects the individual items just fine but it isnt outputting the overlay to show them in a set in the stash tab overlay.

**Comment by HiMarioLopez** [comment]
Can you send a quick screenshot of your settings for the tool? Thanks

**Comment by GaryCommander** [comment]
![image](https://user-images.githubusercontent.com/108105868/175461466-4d118ea0-e13c-4793-b3c3-5299d4fa87d8.png)
![image](https://user-images.githubusercontent.com/108105868/175461502-6ed1f859-6804-470a-974e-024dfea01c6a.png)
![image](https://user-images.githubusercontent.com/108105868/175461560-a5fe2342-942f-4bac-a13d-52e37d1b5388.png)

**Comment by GaryCommander** [comment]
![image](https://user-images.githubusercontent.com/108105868/175461640-bbc40438-5b2f-49c3-a12b-f49c0e944a88.png)

**Comment by HiMarioLopez** [comment]
Do me a favor and check the setting box that says "Do Not Preserve Low Item Level Gear" and see if that shows the sets as expected.

**Comment by GaryCommander** [comment]
It now shows the set number but still no highlighting on the items with the overlay
![image](https://user-images.githubusercontent.com/108105868/175461780-e3664cde-653a-48f8-8ffe-2f6e2e0f84c9.png)

**Comment by HiMarioLopez** [comment]
Try setting your set threshold to 18 as opposed to 0

**Comment by GaryCommander** [comment]
Doesnt seem to change much apart from lowering my sets counter to 17

**Comment by HiMarioLopez** [comment]
Hmm, can you try the 'Item by Item' selection option? As opposed to 'Set by Set'

**Comment by GaryCommander** [comment]
Nope, no changes

**Comment by GaryCommander** [comment]
It randomly resolved itself! I didnt change anything but it started working again, thanks for the help tho!
