### ISSUE TITLE
Set useful defaults

### ISSUE THREAD

**Issue by bjbeare** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#4]
Good user interface design suggests that you should set useful defaults... for example for the highlight colors (whatever they are) as well as for the function keys. I suggest F3/shift-F3/Control-F3 for the function keys.

**Comment by kosace** [comment]
Will add defaults except for the keys. I dont want the tool to interfer with any other program.

**Comment by kosace** [comment]
defaults added

**Comment by bjbeare** [comment]
ok. i see what the highlight colors are about. I had to restart for the color change to take effect.
