### ISSUE TITLE
[💥] [Bug] [General] "error fetching data not found"

### ISSUE THREAD

**Issue by blackmorekwb** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#400]
was using it, all was fine for weeks. no changes at all, came back few hours late to this error.
was on 1.5.2.x  then upgraded to 1.5.5, still same.

account name, again hadnt changed, yes its the same as when im logged in.
double checked poe ses id, same, reset the poe ses id and put in he new one. 
even double checked the config file to make sure the save settings btn worked.

**Comment by Cllyde** [comment]
I'm getting the same error, "Error fetching data", with an error icon and 'Not found" in the message box.
I reset settings and re-entered everything, but still getting the issue after restarting PoE and the Enhancer app.

Built the solution, ran it and I see this URI might be the problem: 
https://www.pathofexile.com/character-window/get-stash-items?accountName={accName}&tabs=1&league={league}

I changed it to this, and am able to pull data from my 0-index tab:
https://www.pathofexile.com/character-window/get-stash-items?league={league}&tabs=1&tabIndex=0&accountName={accName}

Not sure if the API actually changed or what.

**Comment by Akaiyu** [comment]
I'm having the same issue as well. I noticed that it started directly after the recent poe update (3.18.1c)

**Comment by HiMarioLopez** [comment]
Gonna take a look at this and will hopefully have a fix up in the next hour or two (no later than tonight). Thanks for the report!

**Comment by HiMarioLopez** [comment]
Fixed and merged into master #402 

Checkout our latest release v.1.5.6 https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/1.5.6

Install that latest version and let me know if you run into any other issues.

I thought this had something to do with our repo migration, but it had nothing to do with it at all.

**Comment by blackmorekwb** [comment]
yes, 1.5.6 hotfix is working instantly for me. thank you very much!

**Comment by javelin10** [comment]
That fixed it thanks!
