### ISSUE TITLE
How to turn off?

### ISSUE THREAD

**Issue by OivindAlvestad** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#406]
Hi, I'm trying to turn it off, because it bugged, so it wasn't able to fetch, so it was stuck.
tried uninstalling it, didn't work, tried reinstalling, to then turn off, but it won't let me.
Tried refreshing my item filter, doesn't help..
How do I remove this?

**Comment by HiMarioLopez** [comment]
You should be able to exit the app by right clicking on the icon in the task bar. 
![image](https://user-images.githubusercontent.com/23390842/177059227-1c4b7a79-da06-436c-b6e8-d4775670d788.png)

If that doesn't work, you can try force closing the app.
https://www.howtogeek.com/680236/how-to-force-quit-an-app-on-windows-10/

If you want to completely remove the app, the standard windows uninstall process will work all the same.
https://www.theverge.com/23053353/windows-11-uninstall-apps-how-to

Let me know if you have any other questions and we can re-open this issue. Cheers
