### ISSUE TITLE
[Enhancement] [Overlays] Increase range of "Tab Header Margin"

### ISSUE THREAD

**Issue by corosou** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#41]
Hi,

Thanks for the program!

Could you please increase the possible range of the "Tab Header Margin"?

Using a tab folder I can't quite line up things:

![image](https://user-images.githubusercontent.com/28074748/104112562-4df38180-52be-11eb-9125-216ff97fc856.png)

Or maybe just add the option to type in a custom number.

**Comment by HiMarioLopez** [comment]
https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/485
