### ISSUE TITLE
[Bug] [Settings Window] [1.6.0] Interface does not redraw on resize

### ISSUE THREAD

**Issue by dovry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#416]
Result from resizing the window
![image](https://user-images.githubusercontent.com/15201298/184826905-c3bcfe6f-14d0-4609-b44c-cc1a07dbcb29.png)

To restore I have to stretch the window ~700 pixels (from default 1100 to 1800+) to restore the right side of the UI, or reopen an instance.

Close to tray, and reopening does not fix.

**Comment by HiMarioLopez** [comment]
Great find! I remember toggling the flag on for the UI to make it resizable. Must have forgotten to turn it off 🤦‍♂️

This should be fixed later today!

**Comment by HiMarioLopez** [comment]
What I'm going to see is if I can keep the resizability of the window enabled, since it's been a pretty well requested feature.

Hoping it doesn't take much.

**Comment by HiMarioLopez** [comment]
Fixed by #417 

Supporting resizing of settings window will be looked into in the future.
