### ISSUE TITLE
[Enhancement] [Overlays] Add "Only Buttons minified" display mode for Set Tracker Overlay

### ISSUE THREAD

**Issue by GlowingShadow** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#418]
I like the minified buttons, saldy when choosing "Only Buttons" we're back with the normal buttons. I would love a  "Only Buttons minified" option.

**Comment by HiMarioLopez** [comment]
This feature has been completed and pushed to https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/tree/feature/overlay-only-minified-buttons

It will be merged into master soon, and included in the Pre-3.20 release later this week. Thanks for your feature request!
