### ISSUE TITLE
Hotkeys don't work

### ISSUE THREAD

**Issue by MrChile** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#42]
No matter what I set my hotkey keybinds to, they won't work in game. If I manually click on the "Stash" Button, the overlay will appear, however I can not click on the edit button to resize the window(My resolution is 2560x1440).

**Comment by kosace** [comment]
Hello,

do you have display scaling in windows at 100%?

**Comment by doudouLapin** [comment]
Hello Kosace,

I've got the same issue, when I'm outside of the game hotkeys work very well (fetch, run / stop, stash), in game they don't.


Display scaling in windows at 100%, also using poe overlay which is very fine

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
