### ISSUE TITLE
[Bug] [Unsorted] Unable to Select POE Client.txt file Location

### ISSUE THREAD

**Issue by Aerospace91** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#423]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest release (not a beta / pre-release)
- [ x] I checked the FAQ and found no common resolution for my issue
- [x ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

When navigating to the Poe client.txt location being able to select the Client.txt file or the folder it's located in

# Current Behavior

When navigating through Explorer I reach C:/Program Files (x86)/Grinding Gear Games/Path of Exile, When I select the logs folder it opens it and the list is empty. But when I navigate it to normally the client.txt file exists

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Chaos Recipe Enhancer
2. Try to set Client.txt file location by clicking input field
3. navigate to client.txt location

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: v.1.6.0.2
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

![image](https://user-images.githubusercontent.com/8888948/185681856-e6866675-bc00-4044-8f82-a03d060420b0.png)

## Additional Attachments (e.g. Screenshots, Videos)

The Window on the right is me navigating directly, the window on the bottom is navigating through the app

**Comment by Aerospace91** [comment]
Running as Admin does not resolve the issue
Able to select Loot Filter location/file without issues

**Comment by Sarkaztikworlok** [comment]
Same issue.

**Comment by HiMarioLopez** [comment]
This is a stupid question for me to ask, but are you guys running the stand-alone client? Or the Steam client?

I'm aware the file path shouldn't exist if the latter is true, but I do have to ask.

**Comment by Aerospace91** [comment]
I'm running the Steam Client @HiMarioLopez

**Comment by Aerospace91** [comment]
So I'm an idiot. I downloaded the standalone a couple leagues ago to test it out. The Path I was goign to was for the standalone. I navigated to the Steam Path and it worked as intended.

C:\Program Files (x86)\Steam\steamapps\common\Path Of Exile\logs

Sorry for wasting time, and thanks @HiMarioLopez for pointing out my mistake

**Comment by HiMarioLopez** [comment]
> So I'm an idiot. I downloaded the standalone a couple leagues ago to test it out. The Path I was goign to was for the standalone. I navigated to the Steam Path and it worked as intended.
> 
> C:\Program Files (x86)\Steam\steamapps\common\Path Of Exile\logs
> 
> Sorry for wasting time, and thanks @HiMarioLopez for pointing out my mistake

You're not an idiot, it's a harmless mistake. I'm glad it's working for you.

@Aerospace91 can you confirm that if you navigate to the log file in the Steam client folder it works, too?

**Comment by Aerospace91** [comment]
@HiMarioLopez Yea I exclusively use the steam client so when navigating to the Steam folder it works

**Comment by HiMarioLopez** [comment]
Woops, meant to @Sarkaztikworlok ! Either way, I'm going to close this issue. Cheers and enjoy the league, y'all!

**Comment by Sarkaztikworlok** [comment]
> Woops, meant to @Sarkaztikworlok ! Either way, I'm going to close this issue. Cheers and enjoy the league, y'all!

@HiMarioLopez sorry for the delay in my reply i missed the notifications. my game files weren't in the steam folder. so i moved them and it worked. so yes its resolved thank you for the help!
