### ISSUE TITLE
[Bug] [General] Auto-update feature is not functional

### ISSUE THREAD

**Issue by S1lverone** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#424]
__Blank bug report form; user didn't bother filling it out__

Developer's Comment: In the future, if you're going to select an issue template, please make at least the bare minimum effort to fill it out. Thanks.

**Comment by S1lverone** [comment]
Auto updater still does not work.
when right-clicking and choosing check for new updates. nothing comes up.
my version is now 1.5.6.0 but latest version is 1.6.0.2.
besides this the feature under "Recipes" >>Do Not Preserve Low item Level Gear<< is missing in the 1.6.0.2.
this software has been out there for more than a year. Please be so kind and ask me for help, so i can help you makle this work. it is eassy

**Comment by HiMarioLopez** [comment]
Couple of things.

>  feature under "Recipes" >>Do Not Preserve Low item Level Gear<< is missing in the 1.6.0.2. 

This has been moved to an 'Advanced' settings tab. This was mentioned in the release changelog.

> this software has been out there for more than a year. Please be so kind and ask me for help, so i can help you makle this work. it is eassy

I welcome any code contributions, and help to review any PRs that come in. If you'd like to discuss your change before pushing the PR in you can hop on the discord and talk to me, as I'm always on it.

Thanks for your comments.

**Comment by HiMarioLopez** [comment]
Removing broken auto-update feature while I work on an alternative (will be released in v1.7.1)

https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/edd3f6aa2d31285159810e9b9e2872d6b56eabe6
