### ISSUE TITLE
[Bug] [Overlays] Stash Tab Overlay is not updating as I pick items out of my stash

### ISSUE THREAD

**Issue by toddy1b21** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#425]
I am running the latest release v.1.6.0.2

[https://youtu.be/j2eOFuGQTvA](url)

**Comment by HiMarioLopez** [comment]
Is your PoE running in admin mode? If so, you may need to run our application in admin mode as well. Let me know if this fixes it.

**Comment by HiMarioLopez** [comment]
Closing this as the issue has become stale, and we're cleaning up our issue board ahead of the 3.20 league launch. Please open a new issue if you would like us to take a look at this again.

Thanks!
