### ISSUE TITLE
[Bug] [Overlay] Minified overlay doubles in vertical size upon stash fetch

### ISSUE THREAD

**Issue by TheveninRDM** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#426]
# Expected Behavior
The minified overlay normally has a static height commensurate with the size of the mini buttons.

# Current Behavior
The minified overlay now appears to roughly double in height (adding white space above the buttons) after a stash fetch occurs. I  cannot verify when the behavior changed as I have not used CRE since late May 2022. 

- Changing the interface style to another option and back to minified does not resolve the issue. 
- Closing and opening the app *does* restore the expected functionality until the fetch button is pressed again. 
- The issue does not occur with the newer vertical minified mode.

## Steps to Reproduce
1. Run the overlay in minified mode
2. Click the F (fetch stash) button or enter a map with the "fetch on new map" option checked.

## Context
* Chaos Recipe Enhancer Version: 1.6.0.2
* Operating System: Win10 Pro
* Chaos Recipe Enhancer Settings: user.config file attached below

## Failure Logs
The log file messages all appear to indicate a normal initialization. No message corresponds to the clicking of the fetch button or the undesired behavior.

minified_normal.png is the expected behavior and the behavior prior to pressing the fetch button
minified_expanded.png is the resulting bad behavior

![minified_expanded](https://user-images.githubusercontent.com/5208178/185806756-0259d4fd-e19b-418d-89af-600434ae12b7.png)
![minified_normal](https://user-images.githubusercontent.com/5208178/185806757-d294cb93-088b-4868-ae6b-215652e50a9d.png)
[user.config.txt](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/files/9389790/user.config.txt)

**Comment by HiMarioLopez** [comment]
Fixed in #436 

Thanks for your detailed report! Folks like yourself help me make the app better.

Cheers and hopefully I'll see you in 3.20!
