### ISSUE TITLE
[Bug] [Overlay] Overlay doesn't stay on top of game client

### ISSUE THREAD

**Issue by sushibagel** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#428]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest release (not a beta / pre-release) **Running v1.6.0.2**
- [x ] I checked the FAQ and found no common resolution for my issue **Yes**
- [ x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker]   **Yes**(https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

On both my computer the overlay window does not stay on top of the POE Client. This has been consistent for me on two different computers.  This for sure happens when alt tabbing but also seems to happen randomly for no apparent reason. 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: **Running v1.6.0.2**
* Operating System: **Window 10**

**Comment by HiMarioLopez** [comment]
Are you running the game in Windowed ~~Borderless~~ Fullscreen mode?

**Comment by sushibagel** [comment]
> Are you running the game in Windowed Borderless mode?

windowed full screen

**Comment by HiMarioLopez** [comment]
Any way at all you can include a gif or video or something to help me reproduce this?

**Comment by sushibagel** [comment]
My client happened to get stuck in the loading screen here but I clicked something on my second monitor and clicked back in POE and the overlay was gone. It seems to happen most often when POE loses focus and then regains it but it does seem to periodically happen without the game losing focus. 

Probably relevant this did also happen it seems to happen even if the overlay at the bottom of the screan is not being used. 

https://user-images.githubusercontent.com/2222713/185989601-84a14d3b-d5a0-430d-a56f-97f160caf283.mp4

**Comment by Paragon78x** [comment]
> Any way at all you can include a gif or video or something to help me reproduce this?

I am also having this same issue, I have Ultra wide screen and play in windowed fullscreen. 3440x1440 Resolution, Ultra Wide , not sure if this matters... I have even tried always on top Autohotkey script and no luck, it just will not stay on top.

**Comment by 80sreplicant** [comment]
I'm on windows 11, using windows full screen, and the overlay can never stay on top. Whenever I click in the game, the overlay is minimized.

**Comment by HiMarioLopez** [comment]
Haven't been able to replicate this at all. Here are my settings:

![image](https://user-images.githubusercontent.com/23390842/195494349-98627f04-9ee8-4cfb-a8d4-67ba87c0e8a6.png)

Tried clicking away from the game on one of my 3 other monitors, no luck

If someone else is able to replicate this if you could screenshot me your settings and potentially send a gif / video so we can get this fixed before 3.20 that would be awesome!

**Comment by HiMarioLopez** [comment]
Is your PoE running in admin mode? If so, you may need to run our application in admin mode as well. Let me know if this fixes it.

This may be related to https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/425

**Comment by HiMarioLopez** [comment]
Closing this as the issue has become stale, and we're cleaning up our issue board ahead of the 3.20 league launch. Please open a new issue if you would like us to take a look at this again.

Thanks!

**Comment by sushibagel** [comment]
Unfortunately, even with it being run as admin still seems to have issues staying on top.
