### ISSUE TITLE
[Bug] [Overlay] Unable to highlight the next item to pick up in stash

### ISSUE THREAD

**Issue by ccc7321** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#429]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [No] I am running the latest release (not a beta / pre-release)
- [Yes] I checked the FAQ and found no common resolution for my issue
- [Yes] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

I expected the chaos recipe enhancer to automatically pick up the next item in stash that I need to pick up.

# Current Behavior

After selecting the first item highlighted in the red box, it does not automatically go to the next item that I need to pick up.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 1.6.0.3
* Operating System: Windows 11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

![image](https://user-images.githubusercontent.com/111797664/186008160-18682fd4-79d0-488b-b82a-6501398035d2.png)

![image](https://user-images.githubusercontent.com/111797664/186008521-22a9e180-30e0-4746-84c3-5ca5eeae5471.png)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by LaggyLiL** [comment]
The same thing happens with quad tabs too. I have found that if you spam left click it will eventually update, it may take 10 clicks, it may take 40

**Comment by ccc7321** [comment]
Thanks for the solution @lil90 , unfortunately spamming left click didn't work out for me.

**Comment by RocketPop** [comment]
Try clicking in the "upper left" highlighted square of the item.

**Comment by HiMarioLopez** [comment]
This is related to some changes I made leading up to the PoE  3.19 league launch. Will be prioritizing the fix for this as I look to prep for PoE 3.20

I will say that the fewer tabs you have in use the lower chance you'll run into this issue.

**Comment by HiMarioLopez** [comment]
Anybody running into this issue running the PoE client in Admin mode? If so, can you try CRE in Admin mode as well?

**Comment by HiMarioLopez** [comment]
Closing this as the issue has become stale, and we're cleaning up our issue board ahead of the 3.20 league launch. Please open a new issue if you would like us to take a look at this again.

Thanks!
