### ISSUE TITLE
[Bug] [General] Seemingly random exception related to an "Invalid visual tree" causing fatal crash

### ISSUE THREAD

**Issue by nomis51** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#430]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Current Behavior

The app just randomly stop working, all the counters goes to zero and no way to make it work again. It's been already 3 times in less then 2 days that I have to reset my settings to fix it, quiote annoying. 

I can't really tell what's wrong since I don't know where are the logs (looked at the usual locations : in app folder, in documents, in appdata, etc.) and no error message or nothing except for the first time.

The first time I had an error saying "Invalid visual tree", followed by a WPF callstack, but the message box was just duplicating itself non-stop no matter where clicked... so I had to kill the app through taskmgr.

The other times, no visual error, it just stop working after, I believe, fetching tabs.

**Where are the log files so I can provide them?**

## Steps to Reproduce

No real steps, it's seems random. I had the app opened 4 hours straight, before an issue appeared. The other time 5 minutes and it broke.

## Context

* Chaos Recipe Enhancer Version: 1.6.0.2
* Operating System: Win 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):
[user - Copy.zip](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/files/9411221/user.-.Copy.zip)

## Failure Logs

I would like to know where those files are.

**Comment by HiMarioLopez** [comment]
Interesting issue! A screenshot of the error or of the call stack would definitely help out in figuring out what the root cause may be. 

Nothing jumps out at me, based on what I can see in your user settings. 

Maybe an reinstall/update to your .NET Framework installation may help? 

Appreciate your bug report, regardless

**Comment by HiMarioLopez** [comment]
Closing this as the issue has become stale, and we're cleaning up our issue board ahead of the 3.20 league launch. Please open a new issue if you would like us to take a look at this again. 

Thanks!
