### ISSUE TITLE
[Bug] [Overlay] Stash Tab Overlay not saving or showing which Tab

### ISSUE THREAD

**Issue by Faldrim** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#431]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest release (not a beta / pre-release)
- [ x ] I checked the FAQ and found no common resolution for my issue
- [ x ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

When re opening the completed item sets the position of overlay would remain the same.

The tab indicator would change colour to show which tab I should open.

# Current Behavior

What is the current behavior?

After closing game and coming back the stash overlay resets to default position.

The tab indicator never activates.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

issues one
1. Edit the stash tab overlay
2. save
3. close
4. close game

issues two
1. never worked
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: v.1.6.0.2
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by HiMarioLopez** [comment]
Howdy, any way you could provide me with a couple screenshots of your CRE settings? Trying to see if I could replicate the issue to find the root cause.

**Comment by HiMarioLopez** [comment]
Closing this as the issue has become stale, and we're cleaning up our issue board ahead of the 3.20 league launch. Please open a new issue if you would like us to take a look at this again. 

Thanks!
