### ISSUE TITLE
[Bug] [Filter Manipulation] Regal Recipe filter manipulation not working on items of ilvl=75

### ISSUE THREAD

**Issue by BananaFlambe** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#434]
# Expected Behavior

Filter should highlight regal recipe items when "Regal Recipe" option is selected

# Current Behavior

The filter is not being modified when "Regal Recipe" is selected

## Steps to Reproduce

1. Enable Regal Recipe option.
2. Select loot filter.
3. Choose any custom color for your filter.
4. Enable loot filter manipulation.
5. Items are not Highlighted.

## Context

* Chaos Recipe Enhancer Version: Latest version

![image](https://user-images.githubusercontent.com/1457461/189520611-639d30b5-70a4-4241-bfb5-8fece2e49b49.png)
![image](https://user-images.githubusercontent.com/1457461/189520633-b3b52d26-931d-4e7a-aed8-8b0f0f9a0b94.png)
![image](https://user-images.githubusercontent.com/1457461/189520652-dfd8a650-efb1-4f29-a3ea-7afb31953b3d.png)

**Comment by BananaFlambe** [comment]
I've noticed that only items with lvl 75 are not being highlighted.

**Comment by HiMarioLopez** [comment]
Fixed in #437 

Thanks a ton for your bug report! You've helped make this app better for everyone. Cheers, and hopefully I'll see you in 3.20 :D
