### ISSUE TITLE
it just dont install, it dont open the installer

### ISSUE THREAD

**Issue by kovauskilol** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#44]
ir just dont install in my pc, idk why, antivirus off even, and dont install, do u have an .exe file ready?

**Comment by kosace** [comment]
I could upload it but the tool requires some folders at different locations. I will probably add a .zip file later on which works without installer. 

Did you try to install with admin rights?

**Comment by kovauskilol** [comment]
my windows dont allow me to do admin rights, it says that is used by another computer.

**Comment by Monteirolnx** [comment]
Confirming. Installer does not open. After receiving the warnings that the file may damage the system, and clicking to save / maintain anyway, installer does not open.

Troubleshoot compatibility was performed without result.

Menu to run in administrator mode appears disabled

OS Name:	Microsoft Windows 10 Pro
Version:	 10.0.19041 Build 19041

**Comment by kosace** [comment]
Hmm

I dont know how to fix that atm. I will work on a standalone exe when i have time. Need to change some things first though.

**Comment by alfredoherculano** [comment]
I'm having the same issue as OP.

**Comment by Poesurv** [comment]
I'm also having the same issue. The installer just don't run. Hoping for a fix or .exe file.

**Comment by FelipeAD07** [comment]
I found a fix for this. I moved the installer file from the Downloads folder to a new folder on my (C:) drive.

**Comment by kovauskilol** [comment]
I did what felipe said, it worked, just moved to a random folder, and it installed, i dont know why it works this way, but it works now.

**Comment by alfredoherculano** [comment]
> I found a fix for this. I moved the installer file from the Downloads folder to a new folder on my (C:) drive.

For some reason this worked! Thanks  lot!

**Comment by Poesurv** [comment]
It worked here too! Thanks!
