### ISSUE TITLE
[Bug] [Unsorted] Prefix stash tab name change to invalid after valid fetch throws exception

### ISSUE THREAD

**Issue by yenbounger** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#444]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

No repeated exception to be thrown

# Current Behavior

Repeated exception thrown:
![image](https://user-images.githubusercontent.com/44820756/206715954-f29d810d-6e23-49a4-bbdd-6d16e277c896.png)
I did also have a full system crash on one attempt of reproduction - however have not been able to cause this since.

## Steps to Reproduce

1. Set up application as expected (with correct stash tab prefix)
2. Open overlay 
3. Fetch 
4. Open Stash overlay
5. Change stash tab prefix to something with no matches
6. Save settings
7. Fetch Again.
8. Click
9. More clicks will spawn more exceptions

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: Most recent
* Operating System: Windows 11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):
General (this is with the incorrect string in prefix - correct would be chaosR)
![image](https://user-images.githubusercontent.com/44820756/206718489-d5016f68-1053-471d-8570-ce24c321c2d6.png)
Overlays
![image](https://user-images.githubusercontent.com/44820756/206718603-cb06f2cc-cc9b-49b8-a43b-bda2ed0cec24.png)
Loot Filter
![image](https://user-images.githubusercontent.com/44820756/206718655-17e9083b-915e-46d6-980c-afa7569c51e3.png)
Advanced
![image](https://user-images.githubusercontent.com/44820756/206718830-34bc51f4-5bfe-47dc-8334-b5d7614c7793.png)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by HiMarioLopez** [comment]
Closed via https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/445

Thanks for your contribution!
