### ISSUE TITLE
[Bug] [Overlay] "X" Overlay Not Updating or Moving to Next Item when Removing Item From Stash 

### ISSUE THREAD

**Issue by Vociferate** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#447]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest release (not a beta / pre-release) 
**Yes**
- [ ] I checked the FAQ and found no common resolution for my issue
I saw one post mentioning running the game in admin + CRE in admin, which I am doing. Stated to reopen the issue, if the problem arose.
- [ ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))
https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/429

# Expected Behavior
Click on the 'X' get the next item.
Please describe the behavior you are expecting
'X' overlay is not moving to the next item.

# Current Behavior

What is the current behavior?
![image](https://user-images.githubusercontent.com/10530013/207092405-a746e127-f126-4250-85b2-8ed6303debac.png)

I have changed admin settings on all programs.
Clicked on upper left, as well as all over the rest.
Clicked hundreds of times to no avail.

**Comment by dquimby** [comment]
I don't see a vote option so leaving a comment here to say I'm experiencing the same issue.

**Comment by esvban** [comment]
I am tryin the new version in crucible and the overlay is very flakey or slow or something. I have to click dozens of times for the red highlight to move to the next item. Does this overlay have a problem with high resolution monitors? Only thing I can think of that changed on my side but been a long time since i used this app / used the old version previously.

**Comment by Irfy** [comment]
I've just experienced this in a reproducible way. Whenever I enter a map portal and go back out while in the middle of clicking through marked slots on the grid, the grid stops responding. Restarting the grid solves the issue for me.

**Comment by HiMarioLopez** [comment]
Removed the x marking for highlight I latest versions

set by set is now the default (and only) option

https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/485
