### ISSUE TITLE
0 sets available displayed, even if there are enough items for a set

### ISSUE THREAD

**Issue by Syll22** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#449]
Even though I have enough items for a set, the overlay shows 0 sets and the items are not highlighted.

All items are iLvl 60-69 and unidentified. There are no corrupted items.
I am using version 1.7.0.0.
I tried with Preserve On and OFF
I am in Windowed-full screen 1920x1080
Window scaling is 100% 
![0sets](https://user-images.githubusercontent.com/18739234/207471531-d4bb746d-5a4f-43e8-9382-7292d0224f30.JPG)

**Comment by danplaseg** [comment]
This is happening to me as well. I was in 1.5 and thought this was the problem, but after updating to 1.7.0 the problem persists.

**Comment by Lukeghost** [comment]
go to adavanced and check the box do not preserve low level item gear, this option fixed mine.

**Comment by Syll22** [comment]
@Lukeghost I tried but it didn't fix the issue.
