### ISSUE TITLE
Getting Bad Request Error while trying to fetch.

### ISSUE THREAD

**Issue by Pedro-Rosas** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#45]
Hi,
I already downloaded 2 times. 
I am using account name and used the right SessionId.

This is the settings im using.
![ChaosOverlay](https://user-images.githubusercontent.com/48049522/104123174-6ce72780-5341-11eb-8c8c-37fbb5649313.png)

When i try to fetch i get this error.
![image](https://user-images.githubusercontent.com/48049522/104123163-5e990b80-5341-11eb-9875-5906ebd36637.png)

I dont want lootfilter update. I dont think its necessary for the tool to work right?

Sorry for boring but i did not find the same problem on issues. Thanks in advance.

**Comment by Imakatsu** [comment]
Standard spell wrong?

**Comment by Pedro-Rosas** [comment]
Thanks ... im so embaressed :(

**Comment by kosace** [comment]
i spell it wrong every single time too 👍
