### ISSUE TITLE
Option to automatically reload filter after fetch

### ISSUE THREAD

**Issue by Fryyyyy** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#451]
A fetch can change what items are highlighted on the filter. It would be nice to automatically reload the filter if it has changed, so you don't keep picking up items that you don't need.

**Comment by HiMarioLopez** [comment]
To make sure we stay aligned with GGG's [Third Party Developer policy](https://www.pathofexile.com/developer/docs#policy) we have to limit our app interactions. Specifically this set of rules:

>   Macros must be invoked manually by the user (automated invocations such as but not limited to: timers, reacting to file changes, or from reading the screen are not allowed).
    Each macro invocation must have one set function (it cannot cycle between actions).
    The resulting function must only perform one action that interacts with the game (sending a single chat message or command counts as one action).

Appreciate the issue, can't take any action on, though.
