### ISSUE TITLE
[Enhancement] [Filter Manipulation] Filter customization (including font size)

### ISSUE THREAD

**Issue by SunofWisdom** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#452]
or maybe just make it so it matches the font size used in filterblade when you manipulate it.

**Comment by SunofWisdom** [comment]
or maybe just make it so it matches the font size used in filterblade when you manipulate it.

**Comment by HiMarioLopez** [comment]
dupe: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/253

i will work on this (just tracking it on the issue linked)
will add font size as an option as a part of this enhancement. thanks for your suggestion
