### ISSUE TITLE
[Enhancement] [General] Adding support for "Fetch on New Map" for Korean (Kakao) Client | HAVE FIX - NEED TESTER! (See comments)

### ISSUE THREAD

**Issue by tuf1992** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#455]
In the "Effect on New Maps" feature,

kakao korea korea

It also wants to work.

Log Files

Could you update the program?
![image](https://user-images.githubusercontent.com/125190714/218308521-6bc14134-d9fb-4ffa-a6f7-ddc3510a2e82.png)

kakao client...

**Comment by HiMarioLopez** [comment]
Hi, is it possible to get a sample of the content of the KakaoClient.txt file? I want to make sure I get the correct check in the program for switching zones.

Thank you

**Comment by HcS9** [comment]
> Hi, is it possible to get a sample of the content of the KakaoClient.txt file? I want to make sure I get the correct check in the program for switching zones.
> 
> Thank you

here's some samples of "kakaoclient.txt'
I think the word "진입했습니다." could be key.

thx for your effort, in advance.

2023/05/01 03:48:41 51946171 cffb071e [INFO Client 27816] : 바알 사원에 진입했습니다.
2023/05/01 03:48:41 51946390 32759a9f [INFO Client 27816] [SHADER] Delay: ON
2023/05/01 03:49:22 51987468 cffb071e [INFO Client 27816] : Svaha_TR 님이 사망했습니다.
2023/05/01 03:49:25 51990500 88a904cb [DEBUG Client 27816] Got Instance Details from login server
2023/05/01 03:49:25 51990500 32759a9f [INFO Client 27816] [SHADER] Delay: OFF
2023/05/01 03:49:25 51990500 ca3a6a71 [INFO Client 27816] Connecting to instance server at 43.133.242.178:6112
2023/05/01 03:49:25 51990515 ca3a4dbb [DEBUG Client 27816] Connect time to instance server was 15ms
2023/05/01 03:49:25 51990515 1186a0e5 [DEBUG Client 27816] Generating level 20 area "HideoutTemplarLab" with seed 1
2023/05/01 03:49:25 51990531 f22b6987 [INFO Client 27816] Tile hash: 3713433821
2023/05/01 03:49:25 51990531 f22b6986 [INFO Client 27816] Doodad hash: 0
2023/05/01 03:49:26 51991390 11870f49 [DEBUG Client 27816] Joined guild named Soliste with 11 members 
2023/05/01 03:49:26 51991406 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:49:26 51991468 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:49:26 51991468 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:49:26 51991468 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:49:26 51991468 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:49:26 51991468 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:49:26 51991468 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:49:26 51991625 cffb071e [INFO Client 27816] : 지도제작자의 은신처에 진입했습니다.
2023/05/01 03:49:27 51992093 32759a9f [INFO Client 27816] [SHADER] Delay: ON
2023/05/01 03:49:53 52018671 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:54 52018765 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:54 52018968 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:54 52019093 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:54 52019296 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:54 52019421 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:54 52019515 cffb071e [INFO Client 27816] : 아이템 적용 실패: 대상이 타락했습니다.
2023/05/01 03:49:54 52019625 cffb071e [INFO Client 27816] : 아이템 적용 실패: 대상이 타락했습니다.
2023/05/01 03:49:55 52020187 cffb071e [INFO Client 27816] : 아이템 적용 실패: 대상이 타락했습니다.
2023/05/01 03:49:55 52020375 cffb071e [INFO Client 27816] : 아이템 적용 실패: 대상이 타락했습니다.
2023/05/01 03:49:56 52020843 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:56 52020953 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:56 52021046 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:56 52021265 cffb071e [INFO Client 27816] : 아이템 적용 실패: 이미 식별된 대상입니다.
2023/05/01 03:49:56 52021609 cffb071e [INFO Client 27816] : 아이템 적용 실패: 아이템을 식별할 수 없습니다.
2023/05/01 03:49:57 52021812 cffb071e [INFO Client 27816] : 아이템 적용 실패: 대상이 타락했습니다.
2023/05/01 03:49:57 52021890 cffb071e [INFO Client 27816] : 아이템 적용 실패: 대상이 타락했습니다.
2023/05/01 03:50:03 52027718 cffb071e [INFO Client 27816] : 고유 속성의 보관함 탭에 이 아이템을 넣을 공간이 부족합니다.
2023/05/01 03:50:03 52027718 cffb071e [INFO Client 27816] : 고유 속성의 보관함 탭에 이 아이템을 넣을 공간이 부족합니다.
2023/05/01 03:50:22 52046984 cffb071e [INFO Client 27816] : 거래를 수락했습니다.
2023/05/01 03:50:30 52054859 cffb071e [INFO Client 27816] : 고유 속성의 보관함 탭에 이 아이템을 넣을 공간이 부족합니다.
2023/05/01 03:50:30 52054859 cffb071e [INFO Client 27816] : 고유 속성의 보관함 탭에 이 아이템을 넣을 공간이 부족합니다.
2023/05/01 03:50:34 52058765 cffb071e [INFO Client 27816] : 거래를 수락했습니다.
2023/05/01 03:50:44 52069031 88a904cb [DEBUG Client 27816] Got Instance Details from login server
2023/05/01 03:50:44 52069031 32759a9f [INFO Client 27816] [SHADER] Delay: OFF
2023/05/01 03:50:44 52069031 ca3a6a71 [INFO Client 27816] Connecting to instance server at 43.133.231.145:6112
2023/05/01 03:50:44 52069031 ca3a4dbb [DEBUG Client 27816] Connect time to instance server was 0ms
2023/05/01 03:50:44 52069046 1186a0e5 [DEBUG Client 27816] Generating level 80 area "CrucibleLeagueArea" with seed 860620438
2023/05/01 03:50:44 52069312 f22b6987 [INFO Client 27816] Tile hash: 1538577041
2023/05/01 03:50:44 52069312 f22b6986 [INFO Client 27816] Doodad hash: 3144404009
2023/05/01 03:50:45 52069968 11870f49 [DEBUG Client 27816] Joined guild named Soliste with 11 members 
2023/05/01 03:50:45 52069968 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:50:45 52069984 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:50:45 52069984 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:50:45 52069984 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:50:45 52069984 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:50:45 52069984 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:50:45 52069984 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:50:45 52070281 cffb071e [INFO Client 27816] : 거신의 대장간에 진입했습니다.
2023/05/01 03:50:46 52070765 32759a9f [INFO Client 27816] [SHADER] Delay: ON
2023/05/01 03:50:47 52072031 cffb071e [INFO Client 27816] 녹아내린 신: 반갑다, 지표인. 여긴 시간조차 거의 잊어버린 곳이지... 이곳에서 네 힘을 증명해라.
2023/05/01 03:52:48 52193593 cffb071e [INFO Client 27816] : Svaha_TR 님이 사망했습니다.
2023/05/01 03:52:52 52197015 88a904cb [DEBUG Client 27816] Got Instance Details from login server
2023/05/01 03:52:52 52197015 32759a9f [INFO Client 27816] [SHADER] Delay: OFF
2023/05/01 03:52:52 52197015 ca3a6a71 [INFO Client 27816] Connecting to instance server at 43.133.226.59:6112
2023/05/01 03:52:52 52197031 ca3a4dbb [DEBUG Client 27816] Connect time to instance server was 0ms
2023/05/01 03:52:52 52197046 1186a0e5 [DEBUG Client 27816] Generating level 20 area "HideoutTemplarLab" with seed 1
2023/05/01 03:52:52 52197062 f22b6987 [INFO Client 27816] Tile hash: 3713433821
2023/05/01 03:52:52 52197062 f22b6986 [INFO Client 27816] Doodad hash: 0
2023/05/01 03:52:53 52197828 11870f49 [DEBUG Client 27816] Joined guild named Soliste with 11 members 
2023/05/01 03:52:53 52197828 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:52:53 52197890 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:52:53 52197890 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:52:53 52197906 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:52:53 52197906 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1
2023/05/01 03:52:53 52197906 6ad7c4b4 [DEBUG Client 27816] ALTERNATE TREE JEWEL: Applying modifications for jewel with alternate tree version = 5, seed = 2407, and keystone selection = 1

**Comment by HiMarioLopez** [comment]
hello i will try to update this right now for you. could you help me test if it works since i don't have access to korea client?

**Comment by HiMarioLopez** [comment]
@HcS9  hi bro how can i contact you to test out a new installer ffor kakao support? need to test it with u before release

i have new .msi installer file but can't attach here in this thread. can you join discord so i can send it to you there?

**Comment by HiMarioLopez** [comment]
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/c52fe006-e5eb-4131-b14d-57a7bc867e79)
