### ISSUE TITLE
Corrupted items are always hidden

### ISSUE THREAD

**Issue by Odynis** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#46]
First of, thank you very much for making such an awesome tool for the community.

I just installed the tool and went for a test drive. Just to see how things work in preparation for next league. As I was running it with the sextant "Unique Monsters drop Corrupted Items" I found that the boss didn't drop anything at all (on an empty stash). After looking at the hidden items all of them were corrupted.
Since the rest of the loot seems to be integrated seamlessly with my current filter (heavily modified strict from filterblade), I fret this is an issue with the program rather than my filter. After which I've also checked it with the regular unmodified filter. Unfortunately with the same result.

Now this sextant might not be on everyone's map yet when using this tool. Other sources of corrupted items tend to be very good for the chaos recipe. For example corrupted strongboxes, vaal side area's and breaches.

I hoop you can find some time to look into this.

edit: I'm stupid... those are identified and therefor useless...

**Comment by kosace** [comment]
i may add the function to show identified items later. not sure yet :)
