### ISSUE TITLE
[Bug] [Unsorted] *Getting Not found in Crucible*

### ISSUE THREAD

**Issue by hghammoud** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#464]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

I am using the program as usual. I am gettin Not Found. That's all. not sure what is happening.

**Comment by LootLary** [comment]
Hello, I have the same Problem. Last league it works fine but now it does just say : Not Found

**Comment by hghammoud** [comment]
we lost so much money :(

**Comment by HiMarioLopez** [comment]
There were many instances of (API) server instability last night as apart of yesterday's league launch. At one point, GGG went as far as force-relogging users (including myself) which mean needing to go in and retrieve a new session ID to get things working again.

I apologize that these issues seemed to have affected your experience with our tool. I was able to get things running last night without a hitch, so I am confident that it remains fully functional!

If you'd like for us to help you please reach out on Discord for help. https://discord.gg/ryss9jnRkZ @hghammoud @LootLary

**Comment by LootLary** [comment]
I re logged, reinstalled and revert alls ettings but it still dont work. also i discovered that the error just occurs on the current league if i tryed it in standart it just do nothing.

**Comment by LootLary** [comment]
Ok i fixed it idk why but the tool selected ruthles and thats why it cant find any stash

**Comment by hghammoud** [comment]
can you please send a capture of your settings. I tried all of the above!

**Comment by LootLary** [comment]
sure  thats my settings hope you can fix it too gl
![image](https://user-images.githubusercontent.com/59345859/230742332-2716389f-7e4a-4822-a149-e149b5b0af43.png)

**Comment by hghammoud** [comment]
Thank you. My windows was running an old version when i type chaos in search!!

**Comment by ybong** [comment]
I have this same issue; fetching works fine if I set it to standard, but as soon as I select Crucible it comes up with stash tabs not found.
