### ISSUE TITLE
[Bug] [Overlays] "Cannot set Visibility [...] after a Window has closed" InvalidOperationException For Overlay After Force Closing It

### ISSUE THREAD

**Issue by Irfy** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#465]
A very easy to reproduce bug causes this exception:

    ---------------------------
    Unexpected Error Occurred: Dispatcher.UnhandledException
    ---------------------------
    The following exception occurred:
    System.InvalidOperationException: Cannot set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after a Window has closed.
       at void System.Windows.Window.VerifyCanShow()
       at void System.Windows.Window.VerifyCanShow()
       at void System.Windows.Window.Show()
       at void ChaosRecipeEnhancer.UI.View.SetTrackerOverlayView.Show()
       ...

1. Make sure the overlay is in focus by clicking on it
    * Alternatively, when you click `Run Overlay` it is automatically in focus without clicking it
2. Press Alt+F4
    * Overlay disappears, but main app is none the wiser
4. Click `Stop Overlay`
    * Nothing happens, but the app is already broken at this point, cannot be exited, has to be killed
6. Click `Run Overlay`
    * Shows the exception window

Only killing the app manually helps. Some sort of listener for closing the overlay should handle the closing by external means correctly, updating internal state etc. *or* Alt+F4 itself could be prevented to fix the problem.

Note that closing apps with Alt+F4 is a common thing, and due to the nature of this app, Alt-Tabbing between apps often catches the overlay and puts it in focus unintentionally, priming it for the exception when one tries to close another app with Alt+F4.

Perhaps [removing the overlay from the taskbar and Alt-Tab list](https://stackoverflow.com/questions/357076/best-way-to-hide-a-window-from-the-alt-tab-program-switcher) is the way to go.

**Comment by HiMarioLopez** [comment]
Thank you for bringing this to my attention. It is on my radar, though as a lower priority bug.

**Comment by HiMarioLopez** [comment]
fix: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/711736edddf7dbf8ec690d80e226616ebbd51d48
