### ISSUE TITLE
"Unexpected error Occured: ispatcher.UnhandledException"

### ISSUE THREAD

**Issue by Titoxine** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#47]
I have a message when I start fetching 
https://cdn.discordapp.com/attachments/759833315602726944/797869629015195698/Capture.PNG
I don't know what does that means. Do I have to make an exception on my anti virus ?

Also it doesn't work with my lootfilter, I'm still testing  the tools so I may  not using correctly this.

**Comment by Titoxine** [comment]
The tool can see my item in my stashtab when I start it, but then 3-4s after, I got the error scren as said previsouly.
It continually fetchnig, I can't stop fetching, the button is stuck on "start fetch", I see the blue bar permanantly. I can go on antoher zone, reload my lootfilter, same and don't refresh informations on the overlay (I mean, the items amount).

**Comment by kosace** [comment]
Hello,

there seems to be a problem with writing to the itemfilter. Do you have admin rights and did try starting the tool with admin rights?

**Comment by Titoxine** [comment]
Yeah I run the tools with admin right, I also done an exception on my
anti-virus and check the lootfilter, but seems ok. I can send you more
details, what dyou need ?

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
