### ISSUE TITLE
Rares showing up to 84 ilvl as chaos recipe item's

### ISSUE THREAD

**Issue by LaptorGH** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#48]
i found one problem with lootfilter manipulation, it's showing item's up to 84 ilvl as chaos recipe items and i think its not right, it's ruins my filter because i can't turn it back and i have to download one more filter that's not broken, i don't need to see rares at high tier maps really

**Comment by kosace** [comment]
Hello,

this is intended since you only need 1 item which is ilvl <75. Just copy your itemfilter before using it for this tool.

An exalted recipe only mode will come though.

**Comment by LaptorGH** [comment]
> Hello,
> 
> this is intended since you only need 1 item which is ilvl <75. Just copy your itemfilter before using it for this tool.
> 
> An exalted recipe only mode will come though.

ye maybe it's fine, thanks
