### ISSUE TITLE
[Bug] [Unsorted] Overlay stretches right across all monitors (Beta)

### ISSUE THREAD

**Issue by ImVexed** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#481]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Not to do the following

# Current Behavior

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/10090878/39da81c2-f14b-456a-bf04-9b2e8f6d7dc4)

## Steps to Reproduce

Click the overlay once in a map

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version:
* Operating System: Windows 11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/10090878/d530ab1e-d891-4bfb-89f5-3fc40134f12a)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/10090878/1e03719c-77e0-40d4-9653-d1d6da6cfab2)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/10090878/97ee909c-78eb-4a81-9b70-be8475a356f1)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by ImVexed** [comment]
I notice this happens specifically when I open a new map and it reloads. I see the blue progress bar go to the right then it just streeeeeetches

**Comment by HiMarioLopez** [comment]
fixed in https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/474

will be release later tonight / early tomorrow morning thx for your patience my friend
