### ISSUE TITLE
[Bug] Need lower level items for recepie

### ISSUE THREAD

**Issue by cirf** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#486]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Please describe the behavior you are expecting
tool should show number of items in stash

# Current Behavior

What is the current behavior?
Tool shows "Need lower level items for recepie"
https://i.imgur.com/x0nloZg.png

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
stash tabs are recognized as they are shown in the overlay and show the correct size
stash tabs contain items ilvl 60-75
https://i.imgur.com/a7KrZyU.png

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 2.0
* Operating System: Win11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):
* https://i.imgur.com/WocCUl1.png

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by cirf** [comment]
ok, the prefix thingy is the solution to get it work. despite showing the right tabs in the overlay it seems to fetch some other tabs for the recipe. After changing it to select specific tabs it works.

**Comment by combatwars** [comment]
This should not have been closed since it seems like it's still a bug. The workaround seems to be to use the ID but prefix is not working.
