### ISSUE TITLE
[Bug] [Unsorted] Sets not tallying correctly, leading to being unable to select certain items for sets.

### ISSUE THREAD

**Issue by hubbcaps** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#488]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest release (not a beta / pre-release)
- [ X ] I checked the FAQ and found no common resolution for my issue
- [ X ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Sets tally up correctly and are findable in v2 of CRE.

# Current Behavior

Sets not tallying correctly even though total number of items listed should equate to more sets.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add multiple sets to your quad tabs
2. Look at the Sets tally

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 2.0.0
* Operating System: Windows 11 latest updates
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

Setup is using two quad tabs.

## Failure Logs

Please include any relevant log snippets or files here.

## Additional Attachments (e.g. Screenshots, Videos)

Sets show 7, but I should be able to make at least 9 sets with the totals listed.
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/17379660/20d45576-0500-4f4b-92ca-a75d4e17a728)

CRE settings by tab:

General
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/17379660/a6a9e1eb-bfa5-432f-b4a6-377f0723c8aa)

Overlays
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/17379660/d08efdc7-7d3f-49f5-9a21-6d3f1941b64c)

Loot Filter
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/17379660/3eac686b-fab5-4fc6-9f2f-297756611ebd)

Advanced
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/17379660/dab80fb4-2c65-4972-9b13-7a90b5f63623)

**Comment by hubbcaps** [comment]
Debugging with my friend, what I think is occurring at a best guess is that you're using an array to store the sets, and what is being displayed as 0 is actually index 0 of the array and you're just not adding a 1 to the display number. My guess on this is based on my homies ticked from 0 to 1 sets as soon as he had 2 sets in his tabs. However, even if that's the case, it being at 0 for some reason still won't let you use the button to grab that 1 set. So it goes beyond just a visual error into something functionally wrong and I'm not sure where beyond that. I'd dig through the code, but I'm griding lol

**Comment by HiMarioLopez** [comment]
Copying and pasting my message from this issue:

> I will be releasing a patch today that will affect this. https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/8addfc1e9b581e52b20e816319513d67c872f5f9

> In general, my guidance (after this patch is release) will be to simply reduce your Set Threshold to what you actually want it to be. In your case, it seem like you want to be able to sell when you have 2 sets available. I would advise you to set your threshold to 2, and it should work as intended based on the new logic being released today in 2.0.1.

In your case, you have your threshold set to 32. I would set it to whatever your _actual_ desired threshold, say, 7 (what you have pictured here.

The threshold affects our set composition algorithm.
