### ISSUE TITLE
[Enhancements] [General] Re-Implement Global Hotkeys

### ISSUE THREAD

**Issue by jacho981** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#489]
**Is your feature request related to a problem? Please describe.**
in old version there was an option to customize the hotkeys for the overlays. please give them back. using the old version meanwhile.

**Describe the solution you'd like**
just add the option back.

**Describe alternatives you've considered**
using the old version meanwhile

**Additional context**
why remove? xD

**Comment by Davst** [comment]
I second this! need the keybinds back

**Comment by HiMarioLopez** [comment]
This is a high priority request for 3.23. Thanks for your issue report!

**Comment by HiMarioLopez** [comment]
added in latest release: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/3.23.1000-rc

final release for 3.23.1000 out later today
