### ISSUE TITLE
Itemfilter hiding items instead of removing the rule.

### ISSUE THREAD

**Issue by benOesing** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#49]
Hello,

the current behaviour hides items from the filter if they are not needed for the chaos recipe. For example: 
> Hide
	HasInfluence None
	Rarity Rare
	Identified False
	ItemLevel >= 60
	Sockets <= 5
	LinkedSockets <= 5
	Class Body Armours
	
I suggest to instead remove those lines completely, so the default filter kicks back in.

Advantages: 
- Nobody misses rares that might be high value, but not needed for the chaos recipe.
- When the user is done with the chaos recipe, he can just turn the options off and after the update the original filter is useable again.

Another quickfix would be to include the following lines to not lose on otherwise great items:
> SynthesisedItem False
FracturedItem False
?AnyEnchantment False?

**Comment by profindi** [comment]
that´s a very important issue. especially at league start . I want to see ALL Wands , but when you are finished with weapons it literally hides EVERY weapon. so i can´t use this tool for now, till it´s fixed. 
Just get rid of the lines instead of hiding , so my loot filter works like i want it!
THX

**Comment by kosace** [comment]
i will change that soon. i try to update the tool before league start but cant promise that

**Comment by kosace** [comment]
Fixed in 1.1.5
