### ISSUE TITLE
[Bug] [Unsorted] Stash view should remove highlights based on mouse click release

### ISSUE THREAD

**Issue by Listerw** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#490]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest release (not a beta / pre-release)
- [X] I checked the FAQ and found no common resolution for my issue
- [X] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

When push down my left click on an item, but move the mouse off it before releasing, the item shouldn't unhighlight.

# Current Behavior

The item unhighlights.

## Steps to Reproduce

1. Get a full set
2. Open Stash view
3. Push down the mouse button on a highlighted item
4. Move the mouse to a different item
5. release the mouse button

You'll end up with the wrong item in your inventory, but with the highlight removed so it appears you clicked correctly.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 2.0.0
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): idk where this xml is

## Failure Logs

N/A

## Additional Attachments (e.g. Screenshots, Videos)

N/A

**Comment by esvban** [comment]
the highlight tracking is very buggy. I have to click multiple times in different boxes for it to register the highlight. I think the box detection is wrong / off by 1 or something

**Comment by HiMarioLopez** [comment]
I mentioned this in https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/491 and I'll mention it here. I'm looking to expand the highlight mode options to increase visual clarity to the user's liking. I'm going to be working to first add back Item-By-Item mode, then look at other solutions to increase item visibility. Here's the issue where I'm tracking some of this work: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/503

With that being said, this is going to be marked as a duplicate - know it's a top priority, though.

Thank you for your issue report.
