### ISSUE TITLE
Outline items in stash

### ISSUE THREAD

**Issue by Listerw** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#491]
**Is your feature request related to a problem? Please describe.**
When I go to grab all items from my stash, it can be unclear where I'll need to click based on highlights. Sometimes I'll have 2 rings side-by-side and click one assuming it's a belt and only realize after I've clicked and moved to the next item that I need to go back.

**Describe the solution you'd like**
I'd like a faint outline of items to better show the areas to click.

**Describe alternatives you've considered**
Making the overlay more see-through might help but it's less obvious.

**Additional context**
N/A

**Comment by HiMarioLopez** [comment]
I'm going to be adding a few more highlight modes to the Stash Tab Overlay, this should help folks better see what items to pick from their stash. I will mark this as a duplicate but know I'm working on this improvement. Thanks for your issue report.

For further updates, check out this issue: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/503
