### ISSUE TITLE
Wiki links to EULA-breaking website?

### ISSUE THREAD

**Issue by Minithra** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#492]
Specifically the sessionID guide.

**Comment by HiMarioLopez** [comment]
Howdy hey, can you point me those links? I haven’t updated the wiki in ages. Thanks

**Comment by Minithra** [comment]
The link in the POE Session ID section of the User Guide - https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/wiki/User-Guide#poe-session-id

While vhpg doesn't seem to be directly RMT-ing, they have plain text and top banner links to RMT websites.

**Comment by HiMarioLopez** [comment]
I have retired the Session ID auth mode in favor of OAuth - a much safer authentication mechanism that will allow users to directly connect Chaos Recipe Enhancer with their PoE account without needing to use any of these work-arounds. The wiki entry has been removed. Thanks for your issue report.
