### ISSUE TITLE
[Bug] [Unsorted] Amount of sets calculated incorrectly

### ISSUE THREAD

**Issue by grallbring** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#493]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest release (not a beta / pre-release)
- [X] I checked the FAQ and found no common resolution for my issue
- [X] I checked to make sure that this issue has not already been filed (by doing a quick search in the issue tracker)

# Expected Behavior

The application is correctly detecting how many of each individual item I have.
The sets should show "4" instead of "2".
The application should not stop highlighting after I've taken out 2 sets of the stash tab.

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/134601573/13239209-83a9-455c-aba1-f923b1ac0d51)

# Current Behavior

The application only shows "2" sets instead of "4".
After taking out 2 sets of items the application no longer highlights new sets and I have to press "Fetch" again or restart the application.

# Context

I've "Fill Greedy Mode" checked and am using a quad stash tab to store my items.

* Chaos Recipe Enhancer Version: 2.0.0
* Operating System: Windows 11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/134601573/77287c9a-322e-4b62-843c-2eb1b0603615)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/134601573/78e40de2-2f25-4ae0-9b62-49792b0a7143)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/134601573/813925ce-c455-4a2e-a302-9248a9f655bc)

**Comment by HiMarioLopez** [comment]
I will be releasing a patch today that will affect this. https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/8addfc1e9b581e52b20e816319513d67c872f5f9

In general, my guidance (after this patch is release) will be to simply reduce your Set Threshold to what you actually want it to be. In your case, it seem like you want to be able to sell when you have 2 sets available. I would advise you to set your threshold to 2, and it should work as intended based on the new logic being released today in 2.0.1.
