### ISSUE TITLE
[Bug] [Overlays] Stash Tab Overlay Unresponsive (e.g. 'Edit' Button)

### ISSUE THREAD

**Issue by vircoh** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#494]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

When pressing on Edit button to resize for quad tab, it should work

# Current Behavior

When pressing on edit button, it does nothing, cant resize quad tab.

## Steps to Reproduce

Opening stash button and then pressing on edit does nothing.

## Context

* Chaos Recipe Enhancer Version: 2.0.0
* Operating System: win 10 64bit
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): 
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/84406460/eeb502d6-9d11-4bb7-9c3b-cc343b62238a)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/84406460/8502da2a-ab34-44cc-b30e-87ecd84bf187)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/84406460/2bee4d88-9f9c-4b12-9459-deed4eb8e1c1)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/84406460/0ac0b9dc-c213-43a2-a388-733e9b07f375)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/84406460/24f5188d-96a1-437c-a0d1-e51e5c8024f9)

## Failure Logs

Please include any relevant log snippets or files here.

## Additional Attachments (e.g. Screenshots, Videos)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/84406460/c60e2ee8-0478-46f8-a512-aafcb36bca87)

**Comment by LeonChadwick** [comment]
I also find the edit button doesn't allow me to edit.
It did at first, I edited and moved by overlay and resized for quad.
It reset itself back to the wrong position and non-quad (guess thats another bug), but now I can't edit it again to the right position - plus I would get sick real quick if I have to do the resize often anyway.

**Comment by zsmith009** [comment]
Same. This tool used to be usable for years. Now it's un-workable.

**Comment by zsmith009** [comment]
Also, where is now the shortcut button to pop up the overlay and make it go away?

**Comment by HiMarioLopez** [comment]
I've experienced this myself a few times, quite a nasty bug. Very hard to reproduce as it's quite random, it seems. I will be looking at this with a higher priority. Thank you for your report.

**Comment by HiMarioLopez** [comment]
Similar experience reported here: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/496
Potential reproduction steps?

**Comment by HiMarioLopez** [comment]
Some additional context from discord:

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/3e0494ea-b239-4080-ac93-e863d4d79aec)


Linked video: https://www.youtube.com/watch?v=Gn_v4qRTxXc

**Comment by HiMarioLopez** [comment]
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/76c2c966-70f4-4f55-b29c-531cd209d68e)

**Comment by HiMarioLopez** [comment]
fix: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/6852ced9fb038c90613e11d15b38e799c69624d2

**Comment by custompro12** [comment]
I don't think this is fixed yet.  I'm not able to click Edit or advance the recipe turn in.

PoE and CRE are displayed on my secondary monitor.  My monitor configuration:

Primary 24"
- 2560x1440
- 125% scaling

Secondary 27"
- 2560x1440
- No (100%) scaling

*CRE v3.23.1005

Thanks!

**Comment by HiMarioLopez** [comment]
@custompro12 can you help me by providing any screen recordings of this happening, with some reproduction steps? I haven’t been able to replicate this since my fix.

**Comment by Peachmann** [comment]
Same issue happening, 2nd monitor messed CRE up.
Both monitors have 240Hz refresh rate.
2560x1440 primary, 125% scaling.
1920x1080 secondary (game screen), 100% scaling.

I could move the stash tab overlay and edit/resize on the second screen but once I locked it it's completely unresponsive. No edit, no clicks on items, nothing. The item counter overlay is still movable tho, as shown in the video. Reinstalling/restarting didn't help.

Potential steps to reproduce:
1. Have POE on non-primary screen.
2. Start CRE, it starts on primary screen.
3. Move item count overlay.
4. Start stash overlay, edit move it to 2nd screen.
5. Lock it.
6. Save settings, close and restart CRE.
7. Stash overlay not responsive anymore.

Version: latest, v3.23.1005
Video: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/2094551/56555294-f3d9-441d-a90f-37588fccf8eb

**Comment by HiMarioLopez** [comment]
> I don't think this is fixed yet. I'm not able to click Edit or advance the recipe turn in.
> 
> PoE and CRE are displayed on my secondary monitor. My monitor configuration:
> 
> Primary 24"
> 
> * 2560x1440
> * 125% scaling
> 
> Secondary 27"
> 
> * 2560x1440
> * No (100%) scaling
> 
> *CRE v3.23.1005
> 
> Thanks!



> Same issue happening, 2nd monitor messed CRE up. Both monitors have 240Hz refresh rate. 2560x1440 primary, 125% scaling. 1920x1080 secondary (game screen), 100% scaling.
> 
> I could move the stash tab overlay and edit/resize on the second screen but once I locked it it's completely unresponsive. No edit, no clicks on items, nothing. The item counter overlay is still movable tho, as shown in the video. Reinstalling/restarting didn't help.
> 
> Potential steps to reproduce:
> 
> 1. Have POE on non-primary screen.
> 2. Start CRE, it starts on primary screen.
> 3. Move item count overlay.
> 4. Start stash overlay, edit move it to 2nd screen.
> 5. Lock it.
> 6. Save settings, close and restart CRE.
> 7. Stash overlay not responsive anymore.
> 
> Version: latest, v3.23.1005 Video: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/2094551/56555294-f3d9-441d-a90f-37588fccf8eb

in these 2 cases, the app currently does not support scaling above 100%. i will look to add the functionality in the future.. but for it now it's unfortunately not something i can fix (at least not in time for 3.24 launch on friday)

re-closing this for now.

**Comment by HiMarioLopez** [comment]
btw the wontfix tab only for right now, i'll make a new issue that highlights the new functionality that will support scaling later
