### ISSUE TITLE
[Bug] [General] "Do Not Preserve Low Item Level Gear" Setting Doesn't Work

### ISSUE THREAD

**Issue by olsev** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#495]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

"Do not preserve low item level gear" flag works correctly when not set

# Current Behavior

"Do not preserve low item level gear" flag does not work correctly when not set

## Steps to Reproduce

1. Fetch data with flag "Do not preserve low item level gear" set.
2. Unset flag
3. Save
4. Fetch data (after waiting 1min; I believe this is the waiting time for next fetch) => number of item sets is the same, although all sets have more than 1 item with item lvl 60-74. In earlier releases this feature worked correctly.

## Context
* Chaos Recipe Enhancer Version: 2.0.0
* Operating System: Win 11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Additional Attachments (e.g. Screenshots, Videos)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/66786722/ef711628-fe31-4074-a9c1-c2bb946e0cc3)

**Comment by sopsop** [comment]
I'd say in my case the flag works but it counts items on both of tabs i listed, but it doesnt try making recipes from items of both tabs. Only uses items from 1st one

**Comment by HiMarioLopez** [comment]
This is going down as a lower priority bug. This feature wasn't used much, and is currently disabled for the past 2 versions due to the bugginess. I'd like to re-introduce it at some point, but would rather revisit some nastier bugs first. Thanks for your bug report.

**Comment by HiMarioLopez** [comment]
I have re-enabled the setting after patching the conservative set composition algorithm It will be released with the latest release.

Both Greedy and Conservative algorithms are integrated with the new "Turn In Sets Early" option. This will be released early next week. Thanks for your patience!

related changes:
https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/2159a96a3f9008d172da017c941983a249f0bb2f
https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/dd06391a1aedc7ec431433952b60137e48f74fc3
https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/e0043b2b4887311c57174587d1d0cb6e9dbeb79a
