### ISSUE TITLE
[Bug] [Unsorted] Unable to Edit Stash tab overlay on the second monitor

### ISSUE THREAD

**Issue by Crvsade** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#496]
# Prerequisites

- [Yes ] I am running the latest release (not a beta / pre-release)
- [Yes ] I checked the FAQ and found no common resolution for my issue
- [Yes ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

After dragging the Stash tabs transparent overlay to the second monitor during editing, I should be able to edit it again. 

# Current Behavior

Somehow for me, after I stop editing it stops my ability to press edit button or press any tabs on the overlay.
Resetting all of the settings to default only reset the item count bar to its default position, the stash tabs overlay just changes
it's size to default one and stays at the same position. Resetting does not make me able to edit it or change it's size.
The item count bar somehow works properly.

In v1.7.2 resetting the settings resets position of the stash overlay too, but overall issue is the same

## Steps to Reproduce

1. Open stash tab overlay
2. Press edit
3. Drag it to the second monitor
4. Press edit button again
5. Now the button or any other buttons should not be pressable

## Context

I'm running it on a laptop with a second monitor

* Chaos Recipe Enhancer Version: v2.0.0, v1.72 (I checked both)
* Operating System: Windows 11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): Settings are default, apart from changing the position

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by HiMarioLopez** [comment]
This is a high priority issue. I will, however, mark this issue as a duplicate and track the progress of this bug here: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/494

Thanks for your report and support.
