### ISSUE TITLE
[Bug] [Unsorted] Set by Set option higlights every valid item

### ISSUE THREAD

**Issue by dovry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#497]
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/15201298/4fe16b01-40be-41bd-abca-32ddbad31ff7)

**Comment by HiMarioLopez** [comment]
What version is your CRE? I thought this was fixed in the final release for 2.0

**Comment by dovry** [comment]
> What version is your CRE? I thought this was fixed in the final release for 2.0

v2.0.0-beta-3

**Comment by HiMarioLopez** [comment]
> > What version is your CRE? I thought this was fixed in the final release for 2.0
> 
> v2.0.0-beta-3

This has been fixed in the latest release. Please download https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/2.0.0
