### ISSUE TITLE
Combined list of Enhancements / Bugfixes

### ISSUE THREAD

**Issue by belziere** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#498]
Before starting, I'd like to say that I'm not a native English speaker and am not that good at writing concise and clear reports, so forgive me if I sound aggressive, do some frenglish (I am french), sound confused or outright write something completely incomprehensible.
I assure you that this is not on purpose, I come from a scientific background and have never needed to write anything more than “sounds good” or “here's the raw data” in english OR french.
Also I swear a lot, I tried to remove any overtly rude stuff from this, but it was 4 am when I wrote it and I might have forgotten a fuck or two.

**Is your feature request related to a problem? Please describe.**

Yes, the last update pretty much broke everything and turned the BEST/most efficient/ un-clunkiest tool in all of PoE history and turned it into its worst version yet. Most of the issues are bugs, so I have hope that you'll iron them out quite fast/easily, but I have less hope for the features that were removed and not mentioned in the changelog and for the weird design choices that made it through the beta and will probably stay forever, making me abandon this tool.
I know I sound defeated, but I have seen so many pieces of software that just “worked” and were ruined by totally unnecessary redesigns.

Let me get into the issues I've encountered so far :

The new account tab is useless and worse than what we had before, why ? It conflicts with “fetch on new map”, if you enable this option every time you clear too fast/ change zone too often/ ggg breaks the server, CRE  crashes (which already happened before when you exeeded api limit, so it's all good) but now FORGETS your session ID under cover of “your Id was reset” (no it was not, I generated it 2 hours ago and the one I just put in that you accepted was the same as the old one).
I can see why you did that, probably because people were filing bug reports saying “tOoL nO wOrK” because they forgot to update their session ID from last league. I don't think this is the way to go.

Removing the sound that played when you take out a full set from your stash, a minor annoyance because the tool that was spoonfeeding me, letting my rot filled brain rest between 8 hours of mapping, now requires me to actually pay attention and focus.
Don't fix that first, that's, as I said, a very minor annoyance (or don't fix at all, it's really not that bad, just a small step backwards IMHO).

Removing the ability to bind showing/hiding the overlay to a key. I don't want to alt-tab, go to system tray, click CRE, stop overlay close CRE to tray, alt-tab back in every time I want to hide the overlay while I could do that with the press of one button before. This one is also, like the removed alert sound issue, a minor annoyance.

Removing decimal increments for the tab header size settings, this makes it basically IMPOSSIBLE to properly line up the tabs to my dump tab setup, leading to many missed clicks and wrong item picked up (and many missed chaos orbs) My sweet spot lies between the new “allowed values” meaning that I'm never actually spot on. Old version basically aligned perfectly with no problems.
Also, you can edit the number shown in the square next to the slider but doing that does nothing, I don't know if it's intended or not.

Now, the biggest gripe I have with this update, bugs, loads of them, making the tool basically unusable, the most notable ones being:

- Stash overlay triggers windows aero snap (you know, the thing that maximizes a window on one half of your monitor when you smash it to the side), forcing me to disable it to set up my alignment. This is not that bad, but didn't happen before, so… Yeah…

- Taking stuff out of my stash (thus removing the highlighted square-s) sometimes crashes the application.

- Changing stash tab sometimes crashes the application.

- Editing settings sometimes crashes the application.

- Saving settings sometimes crashes the application.

- Running overlay sometimes crashes the application.

- Refreshing filter sometimes crashes the application.

- Fetching stash data sometimes crashes the application.

- Application sometimes just crashes without any interaction or reason.

Basically the tool crashes constantly (every hour or so when just mapping, but more like every 10 minutes when preparing sets), for no reason, all the time. Old version would rarely crash (once a day maybe) and the only crash that would happen for me was reproducible (spamming fetch). New version crashes can't be reproduced consistently and seem to be more random than not.

**Describe the solution you'd like**

Go back to 1.7.2 and maintain that for now, it worked, it was ugly sure, but it worked, this release was very obviously rushed (to launch with 3.22 probably) and doesn't work, at all. Continue to update 2.0 to a standard where it's at least usable, and then push it. This is not a release, this is a beta at best and an alpha at worst.

Now, those problems I'm encountering might be only on my side, but I doubt it, PC is from 2022 so recent but not bleeding edge. Never had any weird issues with anything before.
Windows install is fresh from last week.
Nothing is running in the background (well, your tool is, but nothing else is).
I have a reasonable amount of tabs totals (around 40).
I have a reasonable amount of selected tabs for CRE (exactly 10).
CRE 1.7 works fine.
Same problems arise on semi old other PC and very old laptop running win 11 and 10 respectively. 

All in all, I want to assure you that I'm very serious with all that I've said so far. I really liked the tool and its “no bullshit, just does the job” approach to… everything ? I will stay on v1.7.2 until it inevitably becomes unusable because of GGG changing something or you guys figure out how to fix 2.0, I'm not being a drama queen, I really can't use it, or rather I lose so much time and orbs to the bugs/ misalignment that I'd prefer going back to the old, manual way. I really want to join the 2.0 gang, but can't.

I'm here if you need anything from me, more descriptions, screenshots, recordings, hell I'll even let you guys remote into my pc if needed, I can't live without this tool at leaguestart.

Sorry for the text dump.

Thanks.

**Comment by HiMarioLopez** [comment]
I want to start by saying thank you for your passion for the tool. It's brough a lot of people some great convenience over the years, including myself. I will take all these points back to my development and plan accordingly. A lot of these things are already on the board for fixing soon.

I will be sure to ask more questions to clarify any of your points as needed. Once again, thanks for your notes.

Over the next few days/weeks I will likely split these points out into individual issues on our board here and track them separately.

**Comment by HiMarioLopez** [comment]
> Taking stuff out of my stash (thus removing the highlighted square-s) sometimes crashes the application.
> 
> Changing stash tab sometimes crashes the application.
> 
> Editing settings sometimes crashes the application.
> 
> Saving settings sometimes crashes the application.
> 
> Running overlay sometimes crashes the application.
> 
> Refreshing filter sometimes crashes the application.
> 
> Fetching stash data sometimes crashes the application.
> 
> Application sometimes just crashes without any interaction or reason.

I also want to point out that this is true with v1.7.2 as well. We answered many of the same exact support questions on our Discord hundreds of times. Things worked on many of the happy paths, but if a user misconfigured a single setting or did something in the wrong order, it would cause any of these issues to arise.

The solution to this is to build a better app that can help guide users during the configuration, and handle these crashes more effectively.

The biggest achievement with v2+ is how quickly we're able to receive bug reports, identify a fix, and roll it out. [Seen in our latest patch for v2.0.1](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/2.0.1) Again, we will very openly accept the criticism but we want to be sure we are productive in how we act on that criticism. For technical reasons, we will not be going back to v1.7.2. We will work hard to attain the feature-parity from v1.7.2 and move from there.

edit: To clarify, v1.7.2 is still very much open for users to download and use, but we will not be updating v1.X.X moving forward. Only v2+

**Comment by belziere** [comment]
Thanks a lot for not taking my criticism badly, I'm really fond of this tool, and didn't want to come out too harsh.

As said before, I am here to help in any way I can. I will check this page daily to see if you need any clarification on what I meant if I was too vague or anything else. 

I will also install the new v2 version alongside v1 and test stuff on my spare time to see if I can find other bugs/suggestions. If I do find one or more, I will open separate issues for each to follow proper GitHub etiquette (unlike this post).

Feel free to close/split this one at your convenience, I should have opened multiple bug reports alongside one single suggestion thread, but I figured that a very wordy essay like thread was better to group everything.
Sorry again for the text dump.

Thanks for your time ! Keep it up 👍

**Comment by HiMarioLopez** [comment]
Of what I could come up with, all issues have been documented or split out accordingly (albeit, some higher priority than others).

After releasing OAuth integration, which will alleviate a _ton_ of issues related to user error and bugs with the hacky Session ID's, my main focus is on stability with the overlays (which covers a lot of your higher priority issues)

I will keep this at the forefront of thought and once again want to thank you for your impassioned feedback. I encourage you and others to continue as I put out more releases and continue to work on the app.
