### ISSUE TITLE
[Bug] [Unsorted] Run Overlay without tabs selected kills CRE

### ISSUE THREAD

**Issue by dovry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#499]
`Run overlay` without any tabs selected times out the application, stretches the overlay (in fetch mode) across the screen, and crashes eventually.

I couldn't figure out why the application wasn't working. It couldn't find any tabs, and I hadn't selected them because I was rushing acts. As soon as I selected a tab it worked.

**Comment by HiMarioLopez** [comment]
This has been fixed in the latest release, please download https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/2.0.0

**Comment by dovry** [comment]
sorry I keep forgetting to include the version number. I'm using 2.0.0 

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/15201298/fbed893c-6778-418e-9d7f-5c6808e4206f)

**Comment by HiMarioLopez** [comment]
Check out that latest release above I linked. You can download and install the update for the fixes to the two issues you've posted.

Thanks
