### ISSUE TITLE
Automatic adjustment of highlight colors based on need...

### ISSUE THREAD

**Issue by bjbeare** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#5]
Rather than having a different highlight color for each item... consider just two highlight colors.
1. item is useful for the recipe.
2. item is in short supply with respect to other items already in the tab.

The loot filter should be dynamically changed to reflect the current state for these. If you are concerned about breaking rules with a dynamic loot filter... you could have a function key to refresh the filter settings. Is there also some way to get the game to refresh it's use of the filter when the fkey is pressed?

**Comment by kosace** [comment]
The thing with the colors is, that people want to fully customize these. They want rings and belts and amulets extra too, which I will probably add soon. 

And with the refresh: atm there is no good way. You could potentially do 2 things:
1. inject game client (100% illegal and will get you banned)
2. write some kind of macro, which presses "o" and then determines the position of the reload button and clicks it. But that is also illegal and will maybe get you banned. 

So, sadly there is no good way atm.

**Comment by bjbeare** [comment]
I suppose that enhancepoeapp could notify that it has updated the filter automatically... then the user could drop into options and force a refresh. you would want to limit updates to every 10 minutes (or so) and immediately after a turn-in.

**Comment by kosace** [comment]
you can set the refreshrate yourself. and the app notifies users with a sound when the lootfilter has updated. i will add some visual clarification in a later update probably
