### ISSUE TITLE
[Bug] [Unsorted] *Unexpected Error Occurred: AppDomain.CurrentDomain.Unhandled...*

### ISSUE THREAD

**Issue by Loftaris** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#502]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest release (not a beta / pre-release)
- [ ] I checked the FAQ and found no common resolution for my issue
- [ ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

App keeps crashing.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. I haven't figured out how to replicate it, it just happens when it wants to.  I ~THINK~ it happens when switching between tabs when pulling out items for the chaos recipe.

https://prnt.sc/hvzq6ByUHmCe   <-- screenshot of the error, it's too long to type out

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version:  Latest (2.something)
* Operating System: Windows 11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by HiMarioLopez** [comment]
Duplicate with https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/509

This is on my radar, thanks for your issue report.
