### ISSUE TITLE
[Enhancement] [Overlays] Re-Implement 'Item by Item' Highlight Mode for Stash Tab Overlay

### ISSUE THREAD

**Issue by sclient** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#503]
**Is your feature request related to a problem? Please describe.**
Used to be able to get 2 sets at a time more easily.

**Describe the solution you'd like**
For the old feature to return.

**Describe alternatives you've considered**

**Additional context**

**Comment by HiMarioLopez** [comment]
Looking to prioritize this for 3.23. Thanks for your post.

**Comment by HiMarioLopez** [comment]
we're BACK baybeeee! added it back in time for 3.24

closing after merging in latest updates #585
