### ISSUE TITLE
[Bug] [Unsorted] Cannot Connect

### ISSUE THREAD

**Issue by RRadziejewski** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#505]
# Prerequisites

- [X ] I am running the latest release (not a beta / pre-release)
- [X ] I checked the FAQ and found no common resolution for my issue
- [X ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

Just trying to test connection

## Steps to Reproduce

1. Just trying to test connection

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 2.0.1
* Operating System: Win 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.

## Additional Attachments (e.g. Screenshots, Videos)

![y9fL4VPKIr](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/32438378/638a80f9-b2e2-4ea8-ac77-87ffb9595aab)

**Comment by Smoothglobal** [comment]
I am getting this exact error. Just installed for first time

**Comment by LokiReborn** [comment]
I just debugged this error, from what i can see the initial check tries to poll the inventory of the first character found in Standard. As the league and other options are currently blocked by the initial check the only simple fix with the current implementation is to login to your account, create a character in Standard, then rerun the check.

**Comment by HiMarioLopez** [comment]
I'm going to close this and refer anyone who runs into issues to update to the latest beta, and in a few days we'll have the final release of CRE v3.23.X available for download. 

https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/releases/tag/3.23.0002
