### ISSUE TITLE
[Bug] [Unsorted] *Brief synopsis of your issue*

### ISSUE THREAD

**Issue by KudlatePortki** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#508]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest release (not a beta / pre-release)
- [X ] I checked the FAQ and found no common resolution for my issue
- [X ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Can't connect my PoE account with CRE

Please describe the behavior you are expecting

A solution to this problem?

# Current Behavior

What is the current behavior?

When I fill Account Name and SessionID in CRE window and click "test connection" button then an error occurs.

## Steps to Reproduce

1. Run the CRE application (for the first time)
2. Get ur Account name from PoE main website. (I am playing the game on Steam)
3. Get ur SessionID from cookies on PoE main website (logged with Steam and by e-mail and the IDs are different but anyway can't connect)
4. Fill Account Name and SessionID boxes in CRE app with informations obtained by following step 2. and 3.
5. Click " test connection " button in CRE app.

Please provide detailed steps for reproducing the issue.

1. step 1
6. step 2
7. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 2.0.1
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs
![Issue settingsSS](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/144839495/504039bb-16fe-487c-a5d3-b16989e29cda)

Please include any relevant log snippets or files here.

**Comment by HiMarioLopez** [comment]
OAuth is now the default Authentication mechanism for the app. Our beta is now out with it, and a full release coming in the next few days. I will close this up as we retire Session ID based auth.
