### ISSUE TITLE
[Enhancement] [Genera] Additional Safeguards for Reduced Chance of Rate Limiting (e.g. Limits for Stash Tab Selections, Set Threshold)

### ISSUE THREAD

**Issue by n1ob** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#510]
Hi,

Windows 11, 2560 x 1600, scale 150%, core i9

1. adding to many tabs did hit the api transaction limit, got notified, but also got an exception. Maybe you need to slow down the fetching. 
2. It took me some time to find how to move the grid. Maybe you should change the cursor to signal when it´s possible to move the thing.
3. It is very hard  to to find the right spot for to enable edit mode in the overlay. I still don´t understand the systematic.

**Comment by HiMarioLopez** [comment]
I will be wanting to add a few limits to:
- Full Set Threshold (i.e. Number of sets to gather)
- Tab Selections
  - Aside from some pretty dicey challenges that will come with some dynamic implicit rate limiting done on our part, it also causes some very unfortunate visual bugs once you break the number of tabs you have past 5 or so.

How many tabs did you attempt to add when it bugged out for you?

As for your ~~2nd~~ 3rd issue, I have seen this reported a few times and will be sure to continue to be on the look out. If you have any reproduction steps for it, that would be of much use. Thanks

**Comment by HiMarioLopez** [comment]
I missed your 2nd point. I will take a look at the visuals for the resizer. It's been pointed out a few times, that's a great suggestion. Thank you

**Comment by HiMarioLopez** [comment]
I have added a new minimum for set thresholds at 1, and a new maximum of 100. Ref: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/2159a96a3f9008d172da017c941983a249f0bb2f#diff-8a044bc5c209622b18ad5c883031f120999f53f09b2d5f3f43af9a5ca1a4c97b

I will keep this issue open as I still want to take a look at the stash selection rate limiting that happens from time to time. This is a rare case, but it does exist. I will, however, move this to a lower priority.

**Comment by HiMarioLopez** [comment]
After continuing to develop for 3.25 I feel like the safeguards we have in place are doing a good job. I will close this issue for now.
