### ISSUE TITLE
[Enhancement] [General] Re-Implement Sounds

### ISSUE THREAD

**Issue by HiMarioLopez** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#515]
This is a lot harder than I thought it would be. Couldn't get it in time for 3.22. Maybe we can get it in by 3.23? Definitely lower priority than other things, though.

**Comment by Davst** [comment]
I so miss the notification sound for when it is time to reload loot filter.

**Comment by HiMarioLopez** [comment]
closing after merging in latest updates #585

sounds are back, baybe!!! will add new ones i'm sure later down the line
