### ISSUE TITLE
Overlay not updating set number and only hiding body armour

### ISSUE THREAD

**Issue by lkitn** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#52]
Sets always stay 0 and only Body Armour gets removed from the filter everythng else stays no matter how many pieces.
Sound plays when 2 sets are in the chest.
![chaosenhancer](https://user-images.githubusercontent.com/66185528/104338837-3b17c180-54f7-11eb-9cff-2be0162f0ae9.PNG)

**Comment by kosace** [comment]
activate fill greedy
