### ISSUE TITLE
[Bug] [Unsorted] Loot filter highlight not removed on set threshold

### ISSUE THREAD

**Issue by 4leite** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#520]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

Using v3.23.0003-beta-3

- [ ] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Item class should not highlighted once the full set threshold for that item is met.

# Current Behavior

Item class still show.

## Steps to Reproduce

I did a fresh install and removed all previous settings (this is not my first rodeo)
Log in with new oauth feature
Choose offline filter (chaos.filter)
Select league and
Select stash tab [index 0]
Chose minified
Show overlay and enter map

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: v3.23.0003-beta-3
* Operating System: Windows
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.

## Additional Attachments (e.g. Screenshots, Videos)

nb removed oauth tokens from below config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <ChaosRecipeEnhancer.UI.Properties.Settings>
            <setting name="PathOfExileAccountName" serializeAs="String">
                <value>4Pai</value>
            </setting>
            <setting name="PoEAccountConnectionStatus" serializeAs="String">
                <value>1</value>
            </setting>
            <setting name="FullSetThreshold" serializeAs="String">
                <value>2</value>
            </setting>
            <setting name="LeagueName" serializeAs="String">
                <value>SSF Ancestor</value>
            </setting>
            <setting name="StashTabIndices" serializeAs="String">
                <value>0</value>
            </setting>
            <setting name="SetTrackerOverlayDisplayMode" serializeAs="String">
                <value>2</value>
            </setting>
            <setting name="LootFilterManipulationEnabled" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="LootFilterFileLocation" serializeAs="String">
                <value>C:\Users\jon\Documents\My Games\Path of Exile\chaos.filter</value>
            </setting>
            <setting name="SetTrackerOverlayTopPosition" serializeAs="String">
                <value>0</value>
            </setting>
            <setting name="SetTrackerOverlayLeftPosition" serializeAs="String">
                <value>0</value>
            </setting>
            <setting name="StashTabOverlayTopPosition" serializeAs="String">
                <value>74</value>
            </setting>
            <setting name="StashTabOverlayLeftPosition" serializeAs="String">
                <value>12</value>
            </setting>
            <setting name="StashTabOverlayHeight" serializeAs="String">
                <value>690</value>
            </setting>
            <setting name="StashTabOverlayWidth" serializeAs="String">
                <value>641</value>
            </setting>
            <setting name="UpgradeSettingsAfterUpdate" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="PathOfExileApiAuthTokenExpiration" serializeAs="String">
                <value>12/31/2023 09:22:20</value>
            </setting>
        </ChaosRecipeEnhancer.UI.Properties.Settings>
    </userSettings>
</configuration>
```

**Comment by HiMarioLopez** [comment]
I will take a look at this today. Thanks for your bug report and detailed overview

**Comment by HiMarioLopez** [comment]
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/4b1b461e-822c-44ac-bc70-f462b22f0309)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/d877a8b0-2713-40ac-be8b-5b634522d3f5)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/7643de08-bdd7-4703-a5c6-a12aa84832c7)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/3a602fb4-e8f0-4b82-8a74-98f41b11ba16)
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/4feadfae-cb82-4150-b71b-5b94db7d0d31)

Attaching images from Discord

**Comment by HiMarioLopez** [comment]
fixed in https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/0c59c74a88905f0739ddae483cd0b58571269c95

thanks for your error report!
