### ISSUE TITLE
Error fetching data - Forbidden

### ISSUE THREAD

**Issue by olsev** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#53]
Settings:
![image](https://user-images.githubusercontent.com/66786722/104480075-72a06f80-55c4-11eb-8d2d-f646c51e8d44.png)

Error message when pressing "Fetch Start" button:
![image](https://user-images.githubusercontent.com/66786722/104480337-c3b06380-55c4-11eb-99d1-cc45f1e81159.png)

Running program as administrator (WIndows popup to confirm comes up), rechecked POSESSID value...any ideas what could be the issue?

**Comment by myriad-sloths** [comment]
Same issue here

**Comment by kosace** [comment]
this is because of a wrong session id probably. relog at poe website and test with new one.

**Comment by olsev** [comment]
Thank you, that worked for me. How often is it necessary to renew the POSSESSID?

Side note: when working with synchronized filters, the local filter can not be updated. I had only one lootfilter with an individual name for testing, yet it did not update this filter until I deleted all my synchronized filters and restarted PoE.

**Comment by ahmedgaafer** [comment]
Same issue and I tried to get a new poe id and it didn't work... ?

**Comment by Xdoctor4** [comment]
Also seeing this issue and updating possessid did not resolve it. Possibly related to the server issues?

**Comment by IceyLEvell** [comment]
Same issue, tried relogging and changing the SSID, issue still not resolved

**Comment by jazz3601** [comment]
getting same error was working fine then suddenly forbidden

**Comment by wakasm** [comment]
Just reporting - same here.   I would have just chalked it up to server issues, but other that looks at our stash tabs (like Exilence Next) still works. so not sure what's up.

**Comment by Aketuan** [comment]
Not working for me now either

**Comment by mw-stanley** [comment]
Same issue here - even after resetting my session ID, I get "forbidden". Other tools using the session ID like Exilence Next do work with this ID. I don't run them at the same time so it's not a rate limit problem.

**Comment by olsev** [comment]
I logged out from the PoE website, logged in again and got a new POSSESSID which did the job. Had to do it again (after server restart IIRC) and it keeps working (version 1.1.4 now).
