### ISSUE TITLE
[Bug] [General] Prefix Query Mode does not work unless tabs are selected in Select Query Mode

### ISSUE THREAD

**Issue by HeffU** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#537]
# Prerequisites

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the [issue tracker](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues))

# Expected Behavior

When you select the `Tab Name Prefix` query mode, I would expect it to look through all available tabs and use the specified prefix to filter them.

# Current Behavior

The name prefix seems to require that you have the specific tabs you want also selected in `Select Tabs From List` mode. If no tabs are selected in this mode, then an error is thrown:
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/1904613/79e4cc5b-7f71-402d-b018-65d9240a43bb)

Further, if you have selected other tabs but none that match the prefix, or if you have ALL tabs selected, the following error is thrown:
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/1904613/858e2f24-f0b4-4cc4-bbad-1d9762e2e92f)

## Steps to Reproduce

1. Start the app up from a fresh install with no prior settings, login to your account and input your desired League in the options
2. (optional, if using existing settings) Set the `Stash Tab Query Mode` to `Select Tabs From List`, Fetch tabs, and then ensure that no tabs are selected.
3. Change `Stash Tab Query Mode` to `Tab Name Prefix`
4. Set a prefix that matches some of your tab names in the league that you picked
5. Run the overlay and try to Fetch

## Context

* Chaos Recipe Enhancer Version: v3.23.1001
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): [CRE_bugreport_config.txt](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/files/13557638/CRE_bugreport_config.txt) (github does not like xml files)

**Comment by HeffU** [comment]
I went back and took a peek at the code and it looks like `FetchDataAsync` does not consider prefixes at all: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/blob/a5292b18d1f4276d990375960af0b405e6d1a409/src/App/ChaosRecipeEnhancer.UI/Windows/SetTrackerOverlayViewModel.cs#L75

I'm guessing some operations in there make assumptions based on selected tab indices, and would need a method to convert from prefix filter to stash tab indices if the prefix setting is on instead.

**Comment by HiMarioLopez** [comment]
This will be looked at today! Thanks for bringing it to my attention.

**Comment by HiMarioLopez** [comment]
fix: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/a92c441e1d2cd4b82e5248e8ac328ae809dace9e

should be release by tonight or tomorrow
