### ISSUE TITLE
[Enhancement] Hotkey support for re-loading filter

### ISSUE THREAD

**Issue by ficocelliguy** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#551]
**Is your feature request related to a problem? Please describe.**
Per the user guide video (https://www.youtube.com/watch?v=ChC3GNYJpl8) you must click on the screen on each map to update your loot filter. This is impractical for people using a controller on PC. 

**Describe the solution you'd like**
In the app "hotkeys" section, add a configurable one for re-loading the loot filter

**Describe alternatives you've considered**
 It can be worked around with adding a steam controller binding or AHK script to move the cursor and click in the appropriate location, but this workaround is clunky

**Comment by HiMarioLopez** [comment]
feat: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/6174d00aca514a4c9c323ed8f97eb5a65a0520b2
