### ISSUE TITLE
[Bug] [Unsorted] Credentials are still lost after rate limiting

### ISSUE THREAD

**Issue by belziere** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#559]
- [X] I am running the latest release (not a beta / pre-release)
- [X] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Not losing credentials when rate limited.

# Current Behavior

Every time I get rate limited (so like every 10 minutes) I will get a pop-up that tells me that I got rate limited (cool) when I click on OK it will close then another pop up saying that my credentials expired appears (then app closes, and I have to open it again)

## Steps to Reproduce
1 Get rate limited (easy, just run maps fast)
2 Done, no other step

Suggestions : This seems to be quite the tenacious bug so how about getting rid of this feature entirely, I fail to see its use, and it seems to be more of a bother than anything (I don't remember what the old version (pre 2.0) did with rate limiting, but it never failed like that). 
Replacing it by a red warning on top of the overlay (in the same style of your warning that ilvl 60-74 items are needed), this would fix the problem and would remove a feature that seems unnecessary and very harsh.

I suggest doing the same with the error box that says that you are rate limited (it's annoying since it pops every 5 minutes and forces me to play in windowed mode unless I want to get randomly sent to the desktop).

**Comment by HiMarioLopez** [comment]
i will be taking a good look at this before 3.24 so it won't happen again. i've already made a few fixees to issues related to this but i do wanna make sure i'm not invalidating tokens if they're still good.

**Comment by HiMarioLopez** [comment]
i put out #585 which should fix a lot of bugs related to this issue. if yous till run into it lmk happy to revisit this
