### ISSUE TITLE
Windows scaling causes issues with item selection/transfer.

### ISSUE THREAD

**Issue by bjbeare** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#56]
Clicking anywhere in the red should advance to the next item. Shouldn't have to click on the "x" to do so.

**Comment by kosace** [comment]
you dont have to. its just a visual helper.

**Comment by bjbeare** [comment]
Beg to differ.
When I control-click but not on the "x", the transfer doesn't advance and I have to go back and click it again.
Need a video?

**Comment by kosace** [comment]
would be nice yes. that is not intended and some bug

**Comment by bjbeare** [comment]
I'm having some difficulty getting a video of this... the video capture wants to pause (thinks i am alt-tab) when I click on the overlay and doesn't show the grid.

Try clicking "just in" the red area on the lower right corner. Can you reproduce?

... i'll try to get geforce video capture working to get a good grab of the isue

**Comment by kosace** [comment]
that works for me. do you have display scaling in windows at 100%?

**Comment by bjbeare** [comment]
Good catch.
I had 'make everything bigger' set to 125%.
Changing it to 100% fixes the issue.
<nod> you did mention that in the readme!

**Comment by kosace** [comment]
yeah i dont know how to fix that atm. maybe i will look into it, but have to find out how windows scales that exactly

**Comment by bjbeare** [comment]
I'll edit the subject of the issue
