### ISSUE TITLE
Logging in issue

### ISSUE THREAD

**Issue by MarkusDober** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#561]
![Chaos](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/148053560/c5287cd1-778d-43f3-a072-d192cf33ca16)

Hi, when i be redirected to the Authorize page i give the authorisation and then the "Logging in" doesnt work.  Anyone else had the problem?

**Comment by MarkusDober** [comment]
20 times later it still works....dont know what the issue was

**Comment by oceanseth** [comment]
I'm having this problem now

**Comment by MarkusDober** [comment]
I tried a lot with starting as admin. Starting the game as admin...... Tryed it with another browser and then it worked. But now i have the problem that i cant't click the "Edit" button in the game to lay it over my stash.

**Comment by HiMarioLopez** [comment]
try our latest version coming out today

closing after merging in latest updates #585

**Comment by oceanseth** [comment]
looking forward to it, thank you!
