### ISSUE TITLE
[Question] Hidden icons and wrong set count

### ISSUE THREAD

**Issue by message** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#562]
Hey, quick question, why with latest version I have some of the icons with low opacity, and icon on top shows that I have only one set, when clearly I have more than one? 

v3.23.10005

![Screenshot 2023-12-10 191941](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/492026/1b8f6a2b-db1a-480c-a319-d7fb54acdbc7)

V.1.7.0.0

![Screenshot 2023-12-10 192547](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/492026/0db62b42-2917-4f4b-9f8c-157eca525f7f)

How can I get the behaviour of old version back?

**Comment by AnthonyChew** [comment]
@message Did you set the Set Threshold correctly? 
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/22069235/afae382c-c609-4c2a-8666-833cbb244332)

**Comment by message** [comment]
It still wasn't working correctly. Resetting settings and then setting up the threshold helped.
