### ISSUE TITLE
[Enhancement] [Overlays] Scaling Settings to Increase/Decrease Size of Overlays

### ISSUE THREAD

**Issue by pmcthor777** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#563]
Can a overlay scaling feature be added? I love the minified overlay, but the numbers on the item icons are a bit too small for me to read. It would be great if a scaling slider can be added to adjust the overall size of the overlay.

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/20137399/a30a5280-34fb-4146-be23-a65968690cd3)

**Comment by HiMarioLopez** [comment]
Done. Coming in 3.25 release.

https://github.com/user-attachments/assets/a4746a15-2c5c-44cf-8fc9-a07c70f088c1
