### ISSUE TITLE
[Bug] Mouse clicks not registering consistently on stash mode

### ISSUE THREAD

**Issue by esvban** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#564]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- I am running the latest release (not a beta / pre-release)
- I checked the FAQ and found no common resolution for my issue
- I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Clicking a single time in the red highlighted box, removes the highlight and goes to the next item.

# Current Behavior

Clicking highlighted items in the stash doesn't often remove the highlight on the first try. I have to spam click multiple times inside the red box for it to register a click. It is also hard to click the edit button. This was an issue in the previous league / older version of CRE as well.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click stash button
2. Click highlighted items
3. Highlight is not removed on first try

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 3.23.1005
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): Default
* I am playing on a 4K monitor, don't know if that has anything to do with it.

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by esvban** [comment]
having used it a bit more, it seems like clicking near the top left corner is a little more reliable, but i still have to click at least twice usually.

**Comment by HiMarioLopez** [comment]
try our latest version coming out today

closing after merging in latest updates #585

**Comment by esvban** [comment]
The click detection on the boxes is still broken. I think it is misaligned somehow. Some of the red boxes require you to click in a very specific spot for it to go away.

**Comment by esvban** [comment]
for example, rings and amulets. The click detection for the box only works in the upper left quadrant for the box.

**Comment by HiMarioLopez** [comment]
@esvban What's your display scaling set to on Windows? If it isn't 100% unfortunately it will be off like you describe.

**Comment by esvban** [comment]
it's at 200% since im on a 4k monitor. text too small at 100% :(
