### ISSUE TITLE
[Bug] [Unsorted] *Overlay disappears and CRE setting window crashes to desktop every 1-2 maps*

### ISSUE THREAD

**Issue by SkiaAoP** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#566]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest release (not a beta / pre-release)
- [ x] I checked the FAQ and found no common resolution for my issue
- [x ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

App to not crash

# Current Behavior

App crashes every 1-2 maps or sometimes during an instance change inside a map (vaal side area etc.)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. running maps/instance changes while overlap is running
2. app/overlay will crash
3. Happens in administrator mode and non administrator mode

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: v3.23.1005
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.
https://i.imgur.com/TySsSpf.jpg screenshot of settings

**Comment by SkiaAoP** [comment]
Temporary work around; manual fetching does not crash the app. When set to auto fetch between maps is when the crash happens. Disabling auto fetch allows app to be used crash free.

**Comment by HiMarioLopez** [comment]
try our latest version coming out today

closing after merging in latest updates #585
