### ISSUE TITLE
[Bug] [Unsorted] It wont recognize whats in my stash

### ISSUE THREAD

**Issue by hyrenfreak** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#567]
at one point it said i had 9 sets in my stash then it crashed when it came back it says i have 10 but the count on the helm/belts/gloves etc say they all have 10 or more.

**Comment by hyrenfreak** [comment]
![error](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/75179592/8772c800-20b3-49eb-8532-eaa82fe77939)

**Comment by HiMarioLopez** [comment]
try our latest version coming out today

closing after merging in latest updates #585
