### ISSUE TITLE
Impossible to interact with stash overlay.

### ISSUE THREAD

**Issue by Nitzaplays** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#57]
Hello there, first of all thanks for your work!

I have an issue with overlay - it works fine with editing loot filter and showing amount of sets and items in my inventory. Only problem I have is the stash overlay - it's hard to click the edit/save button, as well when I want to clear my stash when I ctrl-click on red showcase with XXX on them items are moving to inventory, but the overlay does not proceed to next item. It looks like when I click on item it just clicks on POE window without interacting with overlay. Running on windowed fullscreen BTW and in windows scale is set to 100% . Any tips?

**Comment by kosace** [comment]
can you change the stashtabs or go in edit mode in the stashoverlay?

**Comment by Nitzaplays** [comment]
When I have PoE launched I cannot click "edit" in stash tab overlay - i have to log out to character selection screen or close the game to be able to change size or interact with the overlay in general. 
I have changed stash tab to a different one and while it recognize items and set a proper grid for a stash tab it still wont interact - when overlay is on edit mode I cannot ctr-click item to move it to inventory, and when it's not on edit mode the XXX on overlay will not recognize when I pick up item.

**Comment by ErueWoad** [comment]
![StashOverlayIssue](https://user-images.githubusercontent.com/57076936/104682181-53cbd700-56b1-11eb-98da-658225a10976.png)
I too am unable to interact with the stash tab overlay portion, I can interact with the other overlay and press the stash and fetch button, but when the stash overlay is up I'm unable to click the edit button to resize it, I play at 1440p.

**Comment by luka189** [comment]
I believe that happens because you are running PoE in administrator mode, but not the overlay. Run the overlay as administrator and that should solve the issue

**Comment by ErueWoad** [comment]
That did in fact fix it, thank you

**Comment by sharkthorn** [comment]
I also have this problem. I can not move my stash overlay. I tried to run the overlay as an administrator too. Unfortunately it does not work. For me it only is moveable if i go back to version 1.0.9 . All versions after that I am unable to move the stash overlay. The other overlay elements are working fine. 

For now i am using 1.0.9 but it would be nice to have the new features. Thanks. If you need any further information please let me know.

**Comment by hosaka86** [comment]
Hello, i want to bring this up. I have the same issue. Can't edit the overlay window no matter if poe is running or not. Also it does not cycle through the sets when I click the overlay. Gonna try an old version now too hoping it works. But for now the overlay does not make any sense here. I'm on nvidia, directx and win10.
