### ISSUE TITLE
[Bug] [Unsorted] *sets that have been taken out are still highlighted again and again

### ISSUE THREAD

**Issue by hosaka86** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#571]
It always just sees one set even if they are more. If i take out and sell that set it still highlights the same set that is gone over and over again. Also it does count wrong. e.g says i have 4 rings but it's 8. Sadly pretty useless right now.

Running on Win10.

**Comment by HiMarioLopez** [comment]
The counts for rings are per-set. 2 rings = 1 count towards a set.

**Comment by HiMarioLopez** [comment]
Also you provided no helpful information. I’d like to know the version you’re running, Windows display scaling, and if you’re running PoE in admin mode.

**Comment by sclient** [comment]
This happens to me when I turn off the overlay after turning in a set, and turn it on to grab a new set. The workaround is to just leave the overlay on the whole time.

**Comment by HiMarioLopez** [comment]
should be solved in #585 

solved a LOT of bugs with set highlight stuff
