### ISSUE TITLE
[Enhancement] [General] Improved Error Handling of GGG API Errors

### ISSUE THREAD

**Issue by marianoarga** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#575]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest release (not a beta / pre-release)
- [x ] I checked the FAQ and found no common resolution for my issue
- [x ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Fetchlikeusual

# Current Behavior

Crash

## Steps to Reproduce

Fetch like so

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Last version
* Windows 10

## Failure Logs

Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1005:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetAuthenticatedAsync(Uri requestUri) in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 142
   at ChaosRecipeEnhancer.UI.Services.ApiService.GetAllPersonalStashTabMetadataAsync() in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Services\ApiService.cs:line 41
   at ChaosRecipeEnhancer.UI.Windows.SetTrackerOverlayViewModel.FetchStashDataAsync() in D:\PoE Tools\ChaosRecipeEnhancer\EnhancePoEApp\src\App\ChaosRecipeEnhancer.UI\Windows\SetTrackerOverlayViewModel.cs:line 248
```

**Comment by HiMarioLopez** [comment]
Re-tagging this as an `Enhancement` as it isn't a bug with our service, rather how we handle errors returned from the GGG API (in cases of their APIs being down due to DDoS, etc.)

**Comment by HiMarioLopez** [comment]
added in #582 

basically added a ton of new edge cases and graceful error handling that better communicates what kind of error is being reported by the GGG API (503, 500, etc.) and adding a button to directly navigate the users to the poe site so they can see if there's a big "Down for Maintenance" or something

also added a new structure that allows me to report more information related to the error in the same window, with an option to collapse the info if the user doesn't want to see everything

always looking for ways to improve this but I think the UX is drastically better than where it was last time.

**Comment by HiMarioLopez** [comment]
![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/f541407c-0805-46ee-bd99-3bb4affc70c3)

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/aef7d303-df07-41b5-bc94-eb7f7b0ae9d9)

some mocks to show you right now but these will report the response errors or exceptions depending on what level of info i have on the error 

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/5163febf-1bca-4004-992b-16aa69aefefa)
