### ISSUE TITLE
[Bug] Can only fetch one set at a time

### ISSUE THREAD

**Issue by Gerben-Tx** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#578]
> [!Important]
> I'm not sure if this is possible already and missing some setting. It feels like a core feature for this tool. Please correct me if this is already a feature so i can close this issue.

**Is your feature request related to a problem? Please describe.**
I would like to be able to fetch multiple sets at once. Right now i can find 1 set using this tool but have to wait ~2 minutes until i can find the next set. I use a quad stash tab, so searching for them by hand is pretty inefficient.

**Describe the solution you'd like**
Have the tool fetch multiple sets and keep track of which sets have been vendored (probably when all the red squares in the overlay are clicked). You could show the new set immediately after all the red squares are gone.

**Describe alternatives you've considered**
Seems simple enough so i don't think this needs alternatives..

**Additional context**
Seems simple enough so i don't think this needs additional context..

**Comment by HiMarioLopez** [comment]
This is unintended. I’ll be able to help troubleshoot after the holiday. 

As a quick note there’s a few things here:

- Do not close the stash overlay when you’re vendoring sets (in the future I can do some sort of minimize feature while people vendor)
- When you put items in your stash you must re-zone to update the stash API, or wait a few minutes to update manually (likely the 2 minutes you mentioned)


I don’t think this is necessarily a bug, like you mentioned it might just be some user errors and/or misconfigured settings.

**Comment by johnyaya** [comment]
Same thing happens to me. I fire up the overlay, fetch and show my stash. It highlights one set, I take out that set, and the tool doesn't highlight the next set.

**Comment by Gerben-Tx** [comment]
> Do not close the stash overlay when you’re vendoring sets (in the future I can do some sort of minimize feature while people vendor)

I keep it open at all times but it still doesn't go to the next set. It also always shows "Sets 1" in the overlay

> When you put items in your stash you must re-zone to update the stash API, or wait a few minutes to update manually (likely the 2 minutes you mentioned)

I did not put anything in the stash and the overlay still didn't update.

So it looks like its actually a bug. Let me know if you need more information

**Comment by Gerben-Tx** [comment]
Ok so it seems that if i increase the "Full set threshold" to 2, save settings, restart the app and re-fetch it seems to work.

As i understand the setting should only have impact on the lootfilter?

For now i'll put this on a high number and see if that works as a workaround

**Comment by HiMarioLopez** [comment]
Again doesn’t seem like a bug, if you set your limit to 1 and pick 1 set that’s… working as intended

setting a higher limit allows you to turn in more sets
