### ISSUE TITLE
[Bug] [Unsorted] Reload Filter pointed to my online filter

### ISSUE THREAD

**Issue by Gerotama** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#579]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Reload filter should be on my offline filter

# Current Behavior

While pressing the reload filter it automatically go to my online filter

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. press reload filter
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version:
* Operating System:
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by HiMarioLopez** [comment]
Rename your offline filter file to something else.

**Comment by Gerotama** [comment]
Thanks bro, will check. Maybe we can include this in the installation guide since if we download the file through Filterblade, we haven't changed the filter file.
