### ISSUE TITLE
[Feature] Better Rate limiting error message

### ISSUE THREAD

**Issue by yenbounger** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#583]
**Is your feature request related to a problem? Please describe.**
When rate limited it would be nice to know how long the timeout will last (e.g. try again in 42 seconds).

**Describe the solution you'd like**
When recieving a timeout error the description of the error would contain information on how long the timeout is.

**Describe alternatives you've considered**
Longer timeouts on fetching/tab limits may be a better long term solution to ensure timeouts never happen, however this would be a nice short term enhancement for users

**Additional context**
N/A

**Comment by HiMarioLopez** [comment]
merged #584 

ty for ur contribution sir! that was the last thing to include in 3.24 :) you're awesome for this
