### ISSUE TITLE
Chromatic recipe items not hidden from filter (breaks full set recipes)

### ISSUE THREAD

**Issue by RoOoBerT** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#59]
Hello,

I think there is an error in the loot filter, it currently shows items compatible with chromatic orb recipe (RGB linked) as valid for set recipes (chaos/regal/exalted).
If you try to vendor a full set of rare items 60-74 but one of them has red, green and blue sockets linked, then this item will count as a chromatic orb instead of a part of the chaos recipe.

This might be very confusing and I think it can be fixed easily, unless I am mistaken you should probably add in the loot filter :
`SocketGroup < RGB`

Regards

**Comment by benOesing** [comment]
Can't reproduce what you said. Are you sure you didn't just miss that one of your items was to low itemlevel? 
Had to craft the helmet to be 3link RGB so its only 1 chaos. Unidentified RRGB helmet gave 2 chaos.
![image](https://user-images.githubusercontent.com/70664484/104658357-e45ee300-56c2-11eb-9e27-fa6aca854e10.png)

**Comment by RoOoBerT** [comment]
Hello,
OK I am sorry, either I made a mistake the first time I had this problem, either something changed since then. (See screenshot below).

You can close the issue.

Regards

![image](https://user-images.githubusercontent.com/7793244/104839119-76333f80-58bf-11eb-83f7-7e68cbbffc39.png)
