### ISSUE TITLE
[Enhancements] [Overlays] [Stash Tab Overlay] Item-Pick-Order Indicators for Set-by-Set Mode

### ISSUE THREAD

**Issue by karl0-dev** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#591]
**Is your feature request related to a problem? Please describe.**
Before this complete new version (months ago), there was a feature which showed not only current, but next item to click after that. It was great because you knew where the next set item will appear and it's less like whack a mole.

**Describe the solution you'd like**
Just bring back the feature it was.

**Describe alternatives you've considered**
N/A

**Additional context**
I missed it instantly after the new version was released, but I assumed it was just delayed or not finished in time.

**Comment by HiMarioLopez** [comment]
Which version are you currently on? I'm not sure I recall the feature. If it was removed it was removed a few years back.

**Comment by karl0-dev** [comment]
Hello,

Well I didn't play with today's new version yet. But i can tell you that it was available from beginning until 2.0 update. So prob last version was 1.7.2?

I might as well be misremembering how it was working exactly. Maybe it highlighted whole set.
I can dig and try older versions and make some videos/screenshots if you like.

**Comment by karl0-dev** [comment]
I found super old video of what i mean
https://youtu.be/ZcKDwRB2BR8?t=1078

![chrome_CP8Nkkx6bP](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/6505439/2a142653-bcef-467c-9da3-0c3728293857)

**Comment by HiMarioLopez** [comment]
OHHHHH. lol. i forgot about that!

i can add that back for sure. no eta but yes I want this back too :) 

i completely forgot I removed it many years back. lol

**Comment by HiMarioLopez** [comment]
Taking a look at this ahead of 3.25. Thanks for your patience with this and hoping to squeeze it back it - it was a nifty feature. Got lost when I did a monumental refactor to the code for the coordinate stuff.

**Comment by HiMarioLopez** [comment]
adding it to the next release

https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/commit/f3e12c729515e5af866031bf92c3a3db9dcaf4bd

the way it works will be a bit different. because some items have the same size, there's a bit of flex. so we basically indicate based on this order:

body armour

weapons (BOTH one hand weapons or ONE two hander)

glove OR helmet OR boots

belt

amulet OR ring

https://github.com/user-attachments/assets/79e3bcb4-3394-45cb-88f9-f3018d4a2e97
