### ISSUE TITLE
App crash if leave it "running"

### ISSUE THREAD

**Issue by IceorLator** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#6]
Hi, like the title say, I just leave the app run to auto-update while I'm doing some map and in 1 map the app will close alone. As well the auto-refresh that I select to be every 60 seconds and to make a sound, doesn't work for me, and it seems the app crash when it tries to make the first auto-refresh. If I'm doing that by my self the update for the overlay of the app is fine all the time. I'll post a screenshot of my setting for the app, hope this can help, maybe its just something I'm doing wrong/don't understand.

ps. very nice app!

![asdasdadw](https://user-images.githubusercontent.com/51930915/102361822-f0685f80-3fb3-11eb-80c9-6e7520ae36fe.png)

**Comment by kosace** [comment]
Hello,

everything seems correct in the settings. 

Is there a crash message box when the app closes?
How long did you leave the app open?
And what are these hotkeys? Maybe its related to them.
And for the sound, can you hear a sound when you change the volume?

**Comment by IceorLator** [comment]
-I don't receive any message when the app close.
-the app closes every time I leave it running for the auto-refresh, doesn't matter how long I've been using it, as soon as I leave it running alone it will crash.
-the hotkey on my keyboard are:
D0 is 0
OemOpenBrackets is '
Oem6 is ¡

-yes the sound when its working when modified

**Comment by kosace** [comment]
okay the sound only plays when you your lootfilter got changed, not everytime it fetches data from server.

and when you press nothing and just let it running it crashes?

**Comment by IceorLator** [comment]
No, the app crash only when I leave it "fetch" the data automatically from my stash for like 1/2 min, if I'm doing it by myself with the hotkey I don't encounter any problem/crash.
I tried now as well without any hotkey selected and still crash when the app "fetch" the data automatically.
If it can help I can make a small video for when the app close/crash.

**Comment by kosace** [comment]
that would be very nice indeed.

**Comment by kosace** [comment]
can you deactivate lootfilter manipulation and test it then?
and deactivate sound and test it again pls. 

want to see if its related to that

**Comment by kosace** [comment]
btw you can join the discord so we can talk a bit better

**Comment by IceorLator** [comment]
here is the video. ok, I'll join the discord, will be better for sure. I'm going to work now, I'll be back home late tonight and I'll do what you just say without any problem. if you need something more just let me know. 
[https://youtu.be/ISaRJFhmEM0](url)

**Comment by kosace** [comment]
the crash should be fixed in new version 1.0.7

pls download and install it. 
you can still join the discord if you want or when new crashes occur :)

thank you for bug reports

**Comment by IceorLator** [comment]
Ok, I just tested now with the new version and its working fine for me. See you in discord
