### ISSUE TITLE
[Bug] Incorrect set count

### ISSUE THREAD

**Issue by mohammedh123** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#600]
![image](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/2066575/998c722b-66bd-4c3d-af64-af364f6b2534)

incorrect set count, doesnt update properly

i have reset all settings multiple times, tried closing and reopening, etc. worked fine last league, but hasnt worked correctly this league yet.

**Comment by ChaosDMG** [comment]
same here, think its pulling from standard or something like that

**Comment by ChaosDMG** [comment]
@mohammedh123 uninstall and deleting the files and reinstall worked (I assume some of the dot net 8 files broke the downgrade)

**Comment by HiMarioLopez** [comment]
https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases/tag/3.24.3000

go ahead and check out our (re)released 3.24 update - which includes accuracy improvements for set tracking. thanks
