### ISSUE TITLE
[Bug] [Unsorted] Automatic fetching is blocked permanently after the first automatic fetch

### ISSUE THREAD

**Issue by Irfy** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#606]
_I am running 3.24.3000, have checked existing issues and asked on discord before reporting this bug._

The "Fetch on Rezone" option is not working properly. Specifically:

- The option triggers automatic fetching the first time we enter a map or act area after a fresh start of the app
- After this first automatic fetch, fetching is blocked permanently as long as the app is running
  - even if we disable the option and stop/re-run the overlay

The only work-around is to disable the option, restart the app and use manual fetching. The fetch-blocking timer works properly with manual fetching.

It feels as if the internal timer for re-enabling the fetching logic is not properly set up when this option is enabled.

**Comment by HiMarioLopez** [comment]
Fixing this and releasing v3.24.3001 today.

**Comment by HiMarioLopez** [comment]
i have fixed this and will be releasing this today

https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/23390842/f6dae0e6-0b68-46b4-b762-67aa0842d33b

**Comment by HiMarioLopez** [comment]
also the cooldown used to be 30 seconds, i have reduced it to 15 seconds (for both manual fetching and auto-fetching)

**Comment by HiMarioLopez** [comment]
closing  https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/pull/609
