### ISSUE TITLE
[Bug] [Overlays] [Stash Tab Overlay] Second set pick order for weapons in Item by

### ISSUE THREAD

**Issue by sclient** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#607]
**Is your feature request related to a problem? Please describe.**
The pick order for weapons in item for the second set prioritizes weapons last, causing a ring to create too little space for the last weapon. Edit: now that I look at it, it is due to the placement of my scrolls, but that wasnt an issue previously, and it works right with the full set picker.

**Describe the solution you'd like**
Prioritize the weapon pick order to immediately follow armor.

![image](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/32541/8b7a6b1b-0443-459d-bb8a-e00df99f239c)

**Comment by sclient** [comment]
![image](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/32541/b11135b4-6134-437b-af0c-3fda973184a1)

**Comment by HiMarioLopez** [comment]
Fixed in https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/commit/7a6d3ad42615dbbb64515e395171382e71060fd0

One handers will now be picked after body armors

will be released in 3.24.3001
