### ISSUE TITLE
Loot filter manipulation not working with weapons ?

### ISSUE THREAD

**Issue by zzKeyy** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#61]
Hi, 
I tried setting up everything so I don't have anything to do on league start except change the league name and the path to the updated loot filter.
I noticed when dropping items on the ground that weapons were either hidden by the regular loot filter, or visible but not colored by your tool (they had the regular colors of the loot filter) even though I didn't hit the treshold. So there's something weird going on with the override.
I tried with 3 body armors and a pair of gloves and those were visible and colored by your tool so it only seems to affect weapons ?

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
