### ISSUE TITLE
[Bug] [General] [Filter Manipulation] [Regal Recipe] Item Level 75+ Items for Regal Recipe not Showing on Manipulated Loot Filter

### ISSUE THREAD

**Issue by sclient** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#615]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ y] I am running the latest release (not a beta / pre-release) 
- [n ] I checked the FAQ and found no common resolution for my issue n, couldnt locate faq in github.
- [ y] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Ilvl 75+ items not being manipulated onto the loot filter for regal recipie.

# Current Behavior

^

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. be in ilvl 75+ zone
2. look for ilvl 75+ items to be highlighted on the loot filter selected in the tool
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 3.24.3001
* Operating System: Win 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): Couldnt find xml (json?) file  in program directories or a way to export one, hope you wont need 6 screenshots.

Edit: Plz dont let my heist dreams die for this league!

**Comment by HiMarioLopez** [comment]
Gonna try to take a look at this for 3.25 - looking to have that patch out in about a week. Thanks for your patience.

**Comment by HiMarioLopez** [comment]
https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/commit/b269c06e5d89c2721e497e74d8f68067ecdf010f

fixed - will be released with 3.25 update ty for reporting
