### ISSUE TITLE
[Bug] [General] [Overlays] Program Hangs during Regal Recipe Picking if Chaos Recipe Item Found Nearby (in Stash)

### ISSUE THREAD

**Issue by vault101** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#616]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [y ] I am running the latest release (not a beta / pre-release)
- [y ] I checked the FAQ and found no common resolution for my issue
- [y ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Regal recipe works

# Current Behavior

If check Regal recipe and there is a chao recipe item in the tab, the app hangs.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Check Regal recipe, there is a chaos item in the tab
2.  in GenerateItemSets_Greedy,  in the while true loop, closestMissingItem will be the chaos item mentioned, so it won't fill the recipe, nor will it break out of the loop
3.  the app hangs

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version:   tag: 3.24.3001
* Operating System: Windows 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): 

```
<setting name="ChaosRecipeTrackingEnabled" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="LeagueName" serializeAs="String">
                <value>Necropolis</value>
            </setting>
            <setting name="StashTabIndices" serializeAs="String">
                <value>2</value>
            </setting>
```

Still figuring out the code so can't make a pull request, sry

**Comment by HiMarioLopez** [comment]
Taking a look at this for 3.25. Thanks for your patience

**Comment by HiMarioLopez** [comment]
yeah this was a complete miss on my end. fix is completed and will be added in release for 3.25 

https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/commit/b269c06e5d89c2721e497e74d8f68067ecdf010f
https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/commit/4263f96d2534c1227652973901d2b1ebcd66d6e2
