### ISSUE TITLE
[Bug] [General] [Filter Manipulation] Loot Filter Manipulation Not Working

### ISSUE THREAD

**Issue by anujsabhlok** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#619]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes ] I am running the latest release (not a beta / pre-release)
- [ Yes ] I checked the FAQ and found no common resolution for my issue
- [ Yes ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

When certain items reach set threshold and we press reload filter the loot filter does not remove said item. Example - When my set threshold is 7 and I have more than 7 armours in tab the reload filter button should hide armours from view.

# Current Behavior

When certain items reach set threshold and we press reload filter the loot filter does not remove said item. Example - When my set threshold is 7 and I have more than 7 armours in tab the reload button DOES NOT hide armours from view. They are still shown.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set full set threshold to 7.
2. Put 8 Armours into stash tab.
3. Go into map and press drop an extra armour piece in map
4. Press Reload on the bar
5. Msg is displayed "Item Filter loaded successfully"
6. But the armour are still shown on map

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 3.24.3002
* Operating System: Windows 10 Pro 
- Version 10.0.19045 Build 19045
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):
![BugReport3](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/53266612/b3ce7734-f336-48fa-9580-4bed92fcfdc1)
![BugReport2](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/53266612/66c86712-3315-4bfe-8024-22f3b0e15f04)
![BugReport1](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/53266612/92c4bc93-28df-400c-aa59-750f6eda8c1e)

## Failure Logs

Please include any relevant log snippets or files here.

## Additional Attachments (e.g. Screenshots, Videos)
Long GIF Uploaded to my drive. Set permission to view so you should be able to download it. Approx 370 MBs. Shows the exact issue.
https://drive.google.com/file/d/1mzF-Z9DPl4u5V5nSsMc6CuZiJhNoiSxv/view?usp=sharing

Thanks for the good work :)

**Comment by HiMarioLopez** [comment]
Howdy! By chance could you screenshot the chat logs in PoE chat that get spit out when you reload your filter, please?

**Comment by anujsabhlok** [comment]
Hi,

PFA the Client Log for today to reduce the file size and a screenshot of current state where I have pressed reload multiple times. The Client Log should include the reload button press.


[Client - Copy.txt](https://github.com/user-attachments/files/16238670/Client.-.Copy.txt)
![BugReport4](https://github.com/user-attachments/assets/493c01cd-61f7-4628-a7db-1e3de01b0f38)

**Comment by HiMarioLopez** [comment]
By chance can you include the filter file in here? There might be some funny business going on where I've seen some people use an older version of our app (say 2.0 or older) and then when migrating to new versions (3.0+) get improved results

Basically, starting with a fresh filter usually fixes this (start with new filter downloaded from filterblade or some other reliable source)

I have tried to reproduce but cannot find an issue on my end after testing extensively. Let me know if the new filter doesn't fix it and we can reopen this issue

Testing done as a part of my work here: https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/commit/c6a9485958c14bdacf27f001b6e42ec98c4d4861

**Comment by anujsabhlok** [comment]
Hi,

Good shout. Downloading a fresh filter from filter blade fixed it. 
I am coming from the old old old old app the one PathOfMath had created. It suddenly stopped working so upgraded. 

Thank you so much for the help.
