### ISSUE TITLE
Hotkey assignment

### ISSUE THREAD

**Issue by pi-lasse** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#62]
When assigning a hotkey with **crtl + a** modifiers using any other hotkey combination e.g. ctrl+w to close browser tabs produces the following error:
System.ComponentModel.InvalidEnumArgumentException: The value of argument 'key' (0) is invalid for Enum type 'Key'.
Parameter name: key
at System.Windows.Input.KeyboardDevice.Validate_Key(Key key)
at EnhancePoE.HotkeysManager.CheckHotkeys()
at EnhancePoE.HotkeysManager.HookCallback(Int32 nCode, IntPtr wParam, IntPtr IParam)

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by pi-lasse** [comment]
Looks like it is fixed. Thank you!
