### ISSUE TITLE
Error fetching items

### ISSUE THREAD

**Issue by Simrien** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#635]
Reporting an exception I received while using Chaos Recipe Enhancer 3.25.0003:

Error Context:
```
You are making too many requests in a short period of time - You are rate limited. Wait at least 1 minute and try again.
```
Error Details:
```
{"error":{"code":3,"message":"Rate limit exceeded"}}
```

**Comment by HiMarioLopez** [comment]
This is not a bug, AFAIK

There is a cooldown to how many operations you can perform. I would recommend selecting fewer tabs if possible and waiting the time it's given before using the app again, thanks

**Comment by HiMarioLopez** [comment]
To add on - if you try to do the same thing on the Trade Site (e.g. too many searches at once) you will also get rate limited. This is to prevent issues like an unintended DDoS attack on GGG's API services
