### ISSUE TITLE
[Bug] [Unsorted] Chaos sets are not recognized as set detection is stuck on Regals

### ISSUE THREAD

**Issue by TripleOmega** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#638]
# Expected Behavior

"Sets" in overlay should be at 2 when all items in the required list are at 0 with full set threshold set to 2.

# Current Behavior

I have the items for 2 full unidentified chaos sets.
The items are correctly detected in the overlay. (All are at 0)
I am able to sell the items for 2 chaos, so they are of the correct ilvl.
"Sets" is stuck at 0.
The text at the top of the overlay says "Need 20 items with ilvl 75+"
(It appears that the sets part is trying to do the regal recipe while the item part is doing the chaos recipe.)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set overlay to chaos recipe
2. Set overlay to 2 sets threshold
3. Add items to tab to fill the needs.
4. Item requirements go down
5. Once a full set is added "Sets" does not go up

## Context

* Chaos Recipe Enhancer Version: 3.25.1001
* Operating System: Window 10
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): Where is the XML saved?

**Comment by Diab0lic** [comment]
same here, tried v3.25.1000 and v3.25.1001. Both acts the same. So it is basically now just counts what I have and need, and modifies my filter, but have to manually select sets to sell.

**Comment by Buhuk** [comment]
> same here, tried v3.25.1000 and v3.25.1001. Both acts the same. So it is basically now just counts what I have and need, and modifies my filter, but have to manually select sets to sell.

Same here with version v3.25.1001

**Comment by Davst** [comment]
Can confirm app is broken at the moment and just wants regal recipie items

**Comment by ThisIsTilted** [comment]
Same here with version v3.25.1001

**Comment by HiMarioLopez** [comment]
Do you all have the option "Do Not Preserve" checked OFF in the Advanced tab? It should be checked.

**Comment by ThisIsTilted** [comment]
> Do you all have the option "Do Not Preserve" checked OFF in the Advanced tab? It should be checked.

This fixed it! Thank you.

**Comment by torsoreaper** [comment]
> Do you all have the option "Do Not Preserve" checked OFF in the Advanced tab? It should be checked.

Just so I understand the logic.  Basically because we were presumably all just hitting level 60, we only had 60lvl items and the software wants to minimize the usage of 60-70 items so it's saying to go get lvl 70+ items and only use X number of 60's per set.  Is that correct?

Thank you!

**Comment by HiMarioLopez** [comment]
> > Do you all have the option "Do Not Preserve" checked OFF in the Advanced tab? It should be checked.
> 
> Just so I understand the logic. Basically because we were presumably all just hitting level 60, we only had 60lvl items and the software wants to minimize the usage of 60-70 items so it's saying to go get lvl 70+ items and only use X number of 60's per set. Is that correct?
> 
> Thank you!

This is correct and I will make sure to review the logic in the code as this tends to get a bit buggy at higher set thresholds
