### ISSUE TITLE
Tool only shows unidentified Items for chaos recepie

### ISSUE THREAD

**Issue by hiimhansi** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#64]
Hey,

installed the tool today, and sadly the tool right now only shows me items that are unidentified for the recepie
as soon as i identify them they are not longer showen in the hotbar.
Is there a fix to this?

Ty

**Comment by Imakatsu** [comment]
thats the whole idea. unid set worth 2 chaos id set worth only 1 chaos

**Comment by hiimhansi** [comment]
ok ,ty thought it will show both ^^
