### ISSUE TITLE
[Bug] [Unsorted] Cant Edit the Stash filter size and position

### ISSUE THREAD

**Issue by crido** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#642]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [✓ ] I am running the latest release (not a beta / pre-release)
- [✓ ] I checked the FAQ and found no common resolution for my issue
- [✓ ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

We are supposed to be able to change the position and size of the filter for the chest
# Current Behavior

What is the current behavior?

Cant click on the edit button. 

## Additional Attachments (e.g. Screenshots, Videos)

![Chaos](https://github.com/user-attachments/assets/031faeea-75ff-4799-b3d9-6421c62c3772)

**Comment by caerulius** [comment]
also having this issue

**Comment by HiMarioLopez** [comment]
Are you running PoE in Admin mode? If so, you will also need to run CRE in Admin mode.

**Comment by crido** [comment]
Well done ! it was indeed the admin mode . Well not a bug then ! My apologies . Have a great evening .
