### ISSUE TITLE
[Bug] [Unsorted] Nothing shows up under the "League" dropdown, pressing refresh causes a crash

### ISSUE THREAD

**Issue by mtxl3912** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#644]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest release (not a beta / pre-release)
- [x ] I checked the FAQ and found no common resolution for my issue
- [x ] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

"League" dropdown should show league options like "Settlers". 

# Current Behavior

Nothing is showing in the dropdown. Pressing refresh throws this exception:

Reporting an exception I received while using Chaos Recipe Enhancer v3.23.1001:
```
The following exception occurred: Dispatcher.UnhandledExceptionSystem.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Oauth in POE
2. Go to "General" tab
3. Click "Refresh" next to the "League" dropdown

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: v3.23.1001
* Operating System: Windows11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice): 

## Failure Logs

Please include any relevant log snippets or files here.

## Additional Attachments (e.g. Screenshots, Videos)
![Screenshot 2024-07-31 094643](https://github.com/user-attachments/assets/dbacff16-ab23-4b3f-8515-74a8e1cc532e)

**Comment by HiMarioLopez** [comment]
Update to the latest version to fix this.

**Comment by mtxl3912** [comment]
oh im an idiot, the version has 3.23 on it .. thank you!
