### ISSUE TITLE
[Bug] [Unsorted] full sets says 0 now

### ISSUE THREAD

**Issue by NaibElSayel** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#645]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

Please describe the behavior you are expecting
when I reach the full sets it tells me with a ding and full on sets for chaos recipe 
# Current Behavior

What is the current behavior?
full sets says 0 and and I have more than enough of everything to trigger the full on sets
## Steps to Reproduce
it used to work until I got above level 75 then it bugged out it always says 0 sets even though its full
Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version: 3.25.1001
* Operating System: win 10 pro
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):
can't seem to find where the log file is located sorry
## Failure Logs

Please include any relevant log snippets or files here.

## Additional Attachments (e.g. Screenshots, Videos)
![image](https://github.com/user-attachments/assets/654fb821-ed72-4ac7-ac2a-63277c3f69e5)

**Comment by HiMarioLopez** [comment]
For the chaos recipe you need 1 item to be ilvl 60-74 

It seems like you need more lower level items to complete the sets

The bug here is that the warning message seems to not be populating correctly and I will make sure to fix that for 3.26 league ty

Closing this as duplicate
