### ISSUE TITLE
Add Alchemy and Chance recipes

### ISSUE THREAD

**Issue by bjbeare** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#65]
Early in the league... it would be awesome to have recipes for alchemy and chance orbs.

**Comment by HiMarioLopez** [comment]
Howdy! Thanks for your suggestion. This is something that would require a significant amount of work to get going for little pay-off. But I'll copy and past the reply I put on the guy requesting adding the Whetstone recipe:

This is something I maaaaaaaay consider reviving when it comes to a hard mode environment (assuming it's as crazy limited with the drops as GGG states it will be). 

Until then, I will not be looking at this :(
