### ISSUE TITLE
Doesn't recognize any sets

### ISSUE THREAD

**Issue by Deurzz** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#66]
My tool doesn't recognize any sets, while it does recognize that it has every item (as shown with "Show Item Amounts" ticked):
https://i.imgur.com/5WExdSG.png

The tool does recognize the correct tab, and no errors were shown.

However, because no sets are found, it also does not highlight a recipe. (Everything is just the background color)

**Comment by sokibat** [comment]
hello, I have the same problem.
everything is working fine,  except he doesn't show finished sets.
I can do it manually I but I don't understand what is the issue here?

**Comment by Ranmaz** [comment]
![image](https://user-images.githubusercontent.com/77890976/105606409-7e272f80-5d56-11eb-87ef-3de2f1a4dc71.png)

App is not recognizing sets even though I have set my set threshold to 3.

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
