### ISSUE TITLE
item count problem

### ISSUE THREAD

**Issue by Pantera3370** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#67]
hello, some items doesn't count, the upper two counts and the buttom right dont ( upper itemlevel: 63,64 ) ( buttom right: 60,65,63 ) ah and the ring doesn't count (itemlevel: 63) and i was back to town and hideout for the updating stash...  ps: sry if it is my fault, im new to the chaos recipe 
![items](https://user-images.githubusercontent.com/63407851/104808908-84169100-57e9-11eb-9f6b-c2ec415c8f61.jpg)

**Comment by jmsMaupin1** [comment]
Im having a similar issue except its just not counting any of them except one of each for some reason:

![image](https://user-images.githubusercontent.com/14814506/104809685-fc1a9200-57bc-11eb-97c8-804f643300f9.png)

Also to add to this, maybe I'm just setting it up wrong, but when I choose prefix and my prefix is "c" it only picks up my c-chaos tab.

I uninstalled 1.1.3 and installed 1.1.2 and it seems to have fixed both issues.

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by HiMarioLopez** [comment]
Closing this as it's a stale issue. Please open a new issue if you still have problems after updating to the latest version of our app. Thanks!
