### ISSUE TITLE
Armor is counting correctly, but accessories aren't

### ISSUE THREAD

**Issue by razorlums** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#68]
I have 4 rings in my tab, but only 2 show. I have 3 amulets, but zero show. And I have 9 belts, but only 5 show.

**Comment by fenume** [comment]
You need 2 rings for recipe, so program count them as 1 piece of set.

**Comment by kosace** [comment]
Update to 1.1.5 to Show actual numbers ör identified items
