### ISSUE TITLE
No stashtabs available / can't fetch start / loot filter not working

### ISSUE THREAD

**Issue by Rekelv** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#69]
Idk what i am doing wrong and that piss me off xD (i wrote Ritual doesn't change anything)
![image](https://user-images.githubusercontent.com/77536103/104812656-1592fc80-5804-11eb-9bec-f77260173a22.png)

**Comment by kharom1** [comment]
Current league is "Ritual" not "Rituel"

**Comment by TBroderick99** [comment]
i think i have the same issue, i run the overlay and the ring necklace and belt are highlighted in the overlay bar as if i'd picked them up but nothing else is. i drop a chestpiece and it doesn't highlight it, nor does it recognise i have items for the set in my stash tab.

**Comment by kosace** [comment]
What happens when you fetch? Did you refresh your Filter ingame?

**Comment by Atlantisarch** [comment]
Same issue. even wondered if firewall blocked it. Seems to not work at all (fetching, lootfilter, whatever). ASH is properly doing it (even though manually because not maintained), even telling me when I'm logged in with POESESSID.
http://prntscr.com/xdovr3

**Comment by Atlantisarch** [comment]
> Same issue. even wondered if firewall blocked it. Seems to not work at all (fetching, lootfilter, whatever). ASH is properly doing it (even though manually because not maintained), even telling me when I'm logged in with POESESSID.
> http://prntscr.com/xdovr3

> {"n":"Chaos","i":1,"id":
chaos stash number is ok (and checked remove only hidding option on OFF).

Fetching does nothing.

**Comment by jsbake2** [comment]
Same issue, with the additional details that my overlay says "Sets Full!" but the tab is empty.... And all of the counts are zero.

Version 1.1.9

**Comment by adrianmak** [comment]
no stashtabs available! Fetch before opening overlay

I did a fetch before opening the overlay

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by HiMarioLopez** [comment]
Closing as we've since released a few fixes to the filter features, as well as sunsetting online filter manipulation (which may or may not have been causing this bug). If you have any other issues with our new v1.4.0 release please open a new issue. Thanks!

**Comment by TBroderick99** [comment]
Hi, you can close it out, I haven't been playing POE so I haven't tried it.

Thanks.
