### ISSUE TITLE
Forbidden fetching

### ISSUE THREAD

**Issue by lordigor181** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#7]
I have installed the tool, set my POESSID and whatnot, run the overlay... an error pops up whent i hit the fetch button and every 60s =S

**Comment by kosace** [comment]
Hello,

that means something went wrong fetching and settings. 
Can you make a screen of your settings?
Also double check your SessionID or try to refresh the id (relog on poe website).

Thanks for reports

**Comment by CBNinja** [comment]
Hello I am having the same issue. 
> I downloaded the program from the read me setup the filter and everything.
> It is detecting loot but not updating the loot I pick up. 
> I signed in and out of the poe website twice to try different POSSID's 
![image](https://user-images.githubusercontent.com/76411117/102726454-0005e200-42ed-11eb-91b3-4d68e985c66a.png)
![image](https://user-images.githubusercontent.com/76411117/102726456-07c58680-42ed-11eb-82b8-5a3829830110.png)

_ Help

**Comment by kosace** [comment]
Hello,

the league for flashback should be: "Flashback (DRE007)"

Also if you are a steam user make sure that your steam account is linked to poe website.

**Comment by CBNinja** [comment]
Wow great man works now. ~ Thank you. Happy holidays.

**Comment by zombodotcom** [comment]
not working for me
