### ISSUE TITLE
EnhancerPoE.exe is detected as a Virus by Avast leading to cryptic error message

### ISSUE THREAD

**Issue by Wasabi375** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#70]
Avast simply kills this program and removes the executable leading to some cryptic error message when trying to start it.
The thread is identified as IDP.Generic.
Not sure if you guys can do something about this. Anyways I hope you can fix this. Right now I just added an exception for this executable.

**Comment by kosace** [comment]
Cant change that unfortunately since the App is Not trusted. The solution would be to buy certificates but that is a Bit Overkill for a Hobby project
