### ISSUE TITLE
App doesn't seem to advance to the next set

### ISSUE THREAD

**Issue by bjbeare** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#74]
I control-click the items in the set (i do not do it in the xxx order). when finished, I hear the ding.

If I close and re-open the grid, the consumed items again have red over their (empty) slots.

**Comment by Ranmaz** [comment]
I had this issue too.  And then the app just doesn't recognize sets anymore:

![image](https://user-images.githubusercontent.com/77890976/105606991-859c0800-5d59-11eb-9ac3-d9a187f1ca50.png)

**Comment by joseluisgarcia** [comment]
> 
> 
> I had this issue too. And then the app just doesn't recognize sets anymore:
> 
> ![image](https://user-images.githubusercontent.com/77890976/105606991-859c0800-5d59-11eb-9ac3-d9a187f1ca50.png)

Same here.

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Gonna close this one due to age.

Please re-open a new issue if you need anything else! Thanks for your report.
