### ISSUE TITLE
When I try to toogle fetching stash a popup error appear

### ISSUE THREAD

**Issue by zuri1337** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#75]
![Error chaos recipe enhancer](https://user-images.githubusercontent.com/77568108/104835993-a02e3700-58aa-11eb-832a-856fccfe699d.png)

How can I solve this issue?

Ty

**Comment by 415DomSmith** [comment]
The Spanish throws it off for me, but I think I had a similar error...

I was targeting an old loot filter that was no longer present in the folder. 
Maybe make sure the loot filter you're selecting in the lootfilter location path is correct?

**Comment by kosace** [comment]
did you install with the installer? or build yourself? 

if you built yourself you have to make this file yourself.
if you installed then you should try to install with admin rights.
