### ISSUE TITLE
Forbidden when fetching

### ISSUE THREAD

**Issue by kartelusm** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#76]
The app was working fine, and then, for some reason, when I start it up and run fetching, the popup shows just saying forbidden.
I tried updating the session id, but the result was the same.

**Comment by cposk** [comment]
Same, just started doing it a few minutes ago for me.

**Comment by Pantera3370** [comment]
me to

**Comment by TrueEdge** [comment]
My brother and me having the same issue

**Comment by jsbake2** [comment]
Same thing here, can't seem to find any logs to help deduce the issue.

**Comment by maksutovic** [comment]
Happening to me too, my only guess is that whatever is happening with the API (yesterday it was completely down) is affecting 3rd party apps as well

**Comment by Pantera3370** [comment]
hope the tool is not blocked or so :/

**Comment by BDrizz307** [comment]
Having the same issue.  Worked fine one minute, scuffed the next.  Please fix!

**Comment by nrennstimpy** [comment]
Am having the same issue... also just got this error trying to restart the overlay

![chaos enhancer error](https://user-images.githubusercontent.com/51141673/104852754-95c36b80-58b1-11eb-9ee5-a51627b8fc1f.png)

**Comment by Rohatej** [comment]
Same issue here. Even after logout/login with new POESESSID

**Comment by ParzivalOne** [comment]
same

**Comment by Armeos** [comment]
I am having the same issue, the program was working fine yesterday

**Comment by Denothor** [comment]
Same issue here.

**Comment by Mixhal** [comment]
same, got a "Forbidden" error when attempting to fetch

**Comment by Nitzaplays** [comment]
Same here

**Comment by Karvin127** [comment]
Same

**Comment by scottmudge** [comment]
They may have blocked the API due to database server issues.

**Comment by fefo32br** [comment]
Same here =/

**Comment by razorlums** [comment]
Has the be API issues, GGG has been having problems since last night. Trade still down half the time or laggy as hell when it isn't. That or GGG has done something to stop the use of the program.

**Comment by CBNinja** [comment]
I'm assuming this is caused by the server issues we have been having since league start.

**Comment by jazz3601** [comment]
> They may have blocked the API due to database server issues.

I hope not we might see a ban wave if this is the cause

**Comment by Wasabi375** [comment]
I doubt that. This tool has been promoted by several big streamers. If they were to ban because of this tool they would at least first ask poeple to stop using it because it causes issues. I can also see them blocking the API but I don't think they will just start banning people

**Comment by zackdave** [comment]
Same issue persist here, I hope the API issue is temporary.

**Comment by ygordanniel** [comment]
Same issue here. Probably something to do with PoE DB instability.

**Comment by scarsick** [comment]
> > They may have blocked the API due to database server issues.
> 
> I hope not we might see a ban wave if this is the cause

No. If tools like this were the issue they would've told us, blacklist and warn people to not use them anymore.

**Comment by schovan** [comment]
same here

**Comment by WhiteFang5** [comment]
@kosace This issue can be fixed by adding a `User-Agent` to the request header for each and every request your perform.  
GGG (actually it's CloudFlare though) blocks requests that have no appropriate user-agent set.  
GGG Developer Novynn posted about this in the tooldev-general in Discord (See: https://discord.com/channels/174993814845521922/175290321695932416/705190546670616586) and kindly asks to add the tool name/contact info in the User-Agent/request header.  
  
[edit]
Every `HttpClient` has to have it added. I've tested it using the following line of code (and it works fine in debug):
`client.DefaultRequestHeaders.Add("User-Agent", $"EnhancePoEApp/v{Assembly.GetExecutingAssembly().GetName().Version}");`

**Comment by SavestateJolt** [comment]
Or even nicer, 

`                client.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("EnhancePoEApp", "1.0"));
`

same result tho, and it gets the app working.

**Comment by garlicbread44** [comment]
Where do I change that folks, do I have to compile the soft myself, perhaps a little change in my browser configuration ?

**Comment by SavestateJolt** [comment]
It's in the code, so yea, compile.

**Comment by ranarn** [comment]
can someone compile and host the bin somewhere?

**Comment by jakobwarrer** [comment]
Is anyone making a PR for this?

**Comment by kosace** [comment]
@WhiteFang5 i cant join the link you provided.

**Comment by zackdave** [comment]
Guys I am not a developer can someone make a release or tell the steps what we need to do?

**Comment by scarsick** [comment]
Well, I have no idea what you guys are talking about, but it's nice to know there's a fix. I'll just do it manually until it's fixed.

**Comment by TrueEdge** [comment]
Can aynone post a compiled version of the fix please?

**Comment by kosace** [comment]
Im working on a hotfix rn

**Comment by kosace** [comment]
should be fixed in 1.1.4

**Comment by jakobwarrer** [comment]
> should be fixed in 1.1.4

Seems to be working again, awesome job!

**Comment by fefo32br** [comment]
Working here...
THANKS DUDE!!!

**Comment by Armeos** [comment]
well im getting this issue after updating to 1.1.4
![image](https://user-images.githubusercontent.com/62191336/104857562-63ccfc00-58e7-11eb-8789-da7308662d7c.png)


ok so if i put 60 it works

**Comment by rsyabuta** [comment]
> well im getting this issue after updating to 1.1.4
> ![image](https://user-images.githubusercontent.com/62191336/104857562-63ccfc00-58e7-11eb-8789-da7308662d7c.png)

From the release notes:
>changed minimum refreshrate to 45 seconds (this will change soon when I rework the fetching algorithm)

**Comment by LoneVoices** [comment]
I have the same issue that @Armeos

**Comment by kosace** [comment]
it is now 45 seconds at least. thats because of poe servers having issues. i will rework that soon

**Comment by LoneVoices** [comment]
> it is now 45 seconds at least. thats because of poe servers having issues. i will rework that soon

Thanks a lot, working fine now :D!!

edit: spoke too soon
![image](https://user-images.githubusercontent.com/77591460/104857679-e6aa8280-58f8-11eb-91e9-95bbbc6b020e.png)

**Comment by kosace** [comment]
check your session id if its still not working

**Comment by LoneVoices** [comment]
> check your session id if its still not working

Hi, i just uninstall, restart my laptop and reinstalled, all working, thanks a lot for this tool :D!! ... just having trouble adjusting the stash window XD kinda tricky to get it :P

**Comment by maksutovic** [comment]
Thank you so much for your quick turnaround! If you are open to tips, would love to support you for this amazing tool!

**Comment by DarioJahnel** [comment]
> > check your session id if its still not working
> 
> Hi, i just uninstall, restart my laptop and reinstalled, all working, thanks a lot for this tool :D!! ... just having trouble adjusting the stash window XD kinda tricky to get it :P

This worked for me, had to uninstall and install again (even after installing new version)

**Comment by BDrizz307** [comment]
All fixed on my end!! Thanks for the quick support on this!

**Comment by dodgegrim** [comment]
same problem in 1.1.4

**Comment by nihilisticGoliath** [comment]
> Hi, i just uninstall, restart my laptop and reinstalled, all working,

I was getting the Forbidden error, too, until I uninstalled and re-installed.

**Comment by drgimpfen** [comment]
They have disabled the API temporarly for everything thats not a browser due their database problems
