### ISSUE TITLE
Incorrect stashtab overlay

### ISSUE THREAD

**Issue by masonk** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#79]
Thank you for this neat tool.

One question I have is that the overlay appears to be smaller than my actual stash:

<img width="1422" alt="IncorrectStashTabOverlay" src="https://user-images.githubusercontent.com/449998/104857594-75ee7080-58ce-11eb-8e08-5ede67b32662.png">

I'm on 3840x2160 reso. Anyway I can fix this?

**Comment by rsyabuta** [comment]
Click on the edit button on the stash overlay and resize the overlay to match your stash

**Comment by masonk** [comment]
Thanks!
