### ISSUE TITLE
Run Overlay button being bumped out

### ISSUE THREAD

**Issue by Sibru1920** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#8]
Hi,
Am not sure if I installed it wrong or something but every time I add a new tab it bumps down the save setting and run overlay button out of screen which wont let me save or run the tool. Doesn't matter if it is minimized or in full screen I cant seem to press the run button. Am I just stupid or missing something cause so far I only checked the installer, my scroll button, and screen resolution to try and find run the tool with at least 1 stash tab

**Comment by kosace** [comment]
hello, 

how did you download the app?

did you download the whole github repo or did you click the download link?

**Comment by Sibru1920** [comment]
> did you download the whole github repo

Green Code button -> Download Zip -> the installer from the extracted files

**Comment by kosace** [comment]
i suppose it it is because i uploaded the half of a new update already, which alters basically everything.

pls press the download link under Installation in the readme. there should be the correct installer

**Comment by kosace** [comment]
i changed the order of the readme sections a bit, the installation is at the top now :)

**Comment by Sibru1920** [comment]
Re dl-ed it thru the read-me "download it here instead" link 

It improved a bit where when it adds a new tab I can see up to Tab header width now. but for some reason still can't reach save settings and run overlay

**Comment by kosace** [comment]
well that is odd indeed.

i dont have a good answer for that atm, but can tell you that my new version will not need this part anyways. i will upload then new version probably today evening. that should fix your problem if you can wait.

i can message you here, when the new version is available.

**Comment by Sibru1920** [comment]
Thank you for the replies,
Probly just a problem on my end so will check things out till your new version

**Comment by kosace** [comment]
the bumping is intended, but it should not cut anything, the window should just extend. 

in the new version the window is just a firm size, will not change. so that problem should be solved :D

**Comment by kosace** [comment]
Hey,

new version is available.

**Comment by Sibru1920** [comment]
Yea just finished the download now and its running fine
Thanks for the updates and the comments and great tool btw.
