### ISSUE TITLE
Threshold not working

### ISSUE THREAD

**Issue by killerkidxb** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#80]
I have my threshold set to 3 and i have 8+ of everything but ammys and rings but the only greyed out tab is the plates.

**Comment by zerger3** [comment]
did u try version 1.1.4?

**Comment by killerkidxb** [comment]
yes have the new one

**Comment by masonk** [comment]
I have the new one too, and in fact I think upgrading to 1.1.4 is what broke this.

**Comment by kosace** [comment]
activate Fill Greedy mode. thats probably it

**Comment by jjepaah** [comment]
Also have the same issue, fill greedy is enabled and threshold is at 6 but it doesn't grey out

**Comment by masonk** [comment]
<img width="502" alt="threshhold" src="https://user-images.githubusercontent.com/449998/104941621-29577380-5968-11eb-9fc1-e888d4d40701.PNG">

My threshold is set to 15. The chest slot is grayed out because it reached past 15 before I upgraded to 1.1.4 and 1.1.4 honored that. But the other ones went past their threshold and were never recognized as needing to deactivate.

**Comment by TechTrooper** [comment]
Same issue here. Versions affected 1.1.4 and 1.1.5.
I have threshold set at 12:

![image](https://user-images.githubusercontent.com/3955313/104958230-504d8e00-59d8-11eb-9003-9fd2e0aee827.png)

**Comment by masonk** [comment]
I think I figured it out. Turn fetch off while mapping. Fetch is just for during the time when you're redeeming sets.

**Comment by wipeoutsix** [comment]
I don't it's related to maps or fetch, I used it today for the first time after updating to 1.1.5 (previously had 1.1.3 installed) and the threshold doesn't work for me, nothing gets greyed out or hidden. I'm also not yet in maps so this happens while leveling.

**Comment by TechTrooper** [comment]
Yep, it happens even when looking at stash. Only Helmets and Bodyarmors are properly counted towards threshold and item filter is updated accordingly for only those item types.

**Comment by kosace** [comment]
check version 1.1.6.

reopen if issue persits please
