### ISSUE TITLE
Wrong version displayed in bottom right 1.1.4

### ISSUE THREAD

**Issue by snwkill** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#81]
just downloaded again for version 1.1.4 but it is still saying 1.1.3 in the bottom right, making me think I installed a second copy

![image](https://user-images.githubusercontent.com/31193671/104862313-24130e00-5901-11eb-932d-13d3ae257fb1.png)

**Comment by snwkill** [comment]
Okay it did install wrong for some reason, had to go into add remove programs to remove 1.1.3 then install 1.1.4, might suggest an update feature.

**Comment by kosace** [comment]
i would need a server for that though and that means financial investment for me (even if its small). 

what i will do though is to provide a standalone .exe.

**Comment by mscoobby** [comment]
I can suggest AWS they have a 1-year free trial for a micro instance that should be enough for hosting the application.

**Comment by snwkill** [comment]
Oh yeah that is what I meant, for the installer to recognize it is already installed and perform an update instead of installing over the top again.

**Comment by Gamewalker** [comment]
@kosace you can use github actions for free 2000 minutes a month. If you need more, you can use my private github worker, just send me a message

**Comment by kosace** [comment]
I will see what i can do. Atm i dont have much time unfortunately but an autoupdater would indeed be the best UX

**Comment by snwkill** [comment]
No problem the tool is BA though, really helped get me started this league, thanks!
