### ISSUE TITLE
Still getting "Forbidden"

### ISSUE THREAD

**Issue by eithiel777** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#82]
Uninstalled > deleted \AppData\Local\EnhancePoE > restarted > downloaded new version from git > installed > filled needed data > still forbidden.

How can i provide more info for debug? (Your tool is too good to give up ;) )

![error](https://user-images.githubusercontent.com/59960060/104890212-8b67a700-596f-11eb-8406-a2d0ad29f863.jpg)

**Comment by SerebryanskiySergei** [comment]
+, for some reason app was working ok untill yesterday.
Now I can't run it because I always get forbidden error when I'm running "Fetch Stash".
There were no manipulation from my side, SESSION ID was then same (but I tried to update it and it doesn't help).

**Comment by Prolefood** [comment]
This is probably something to do with the database problems GGG have been having since season launch. My guess is that they disabled external API access, or broke something while trying to fix something else.

**Comment by eithiel777** [comment]
After 4 more reinstals and filling data, my browser updated poesessionid in cookies, so that was the issue, sorry for spam.

**Comment by SerebryanskiySergei** [comment]
For me even with new ses id it still doesn't work.

**Comment by eithiel777** [comment]
well, after one uninstall i also deleted all entries with "kosace" from windows registry, but i don't think that was it.

**Comment by tamaroth** [comment]
Uninstall it again. Make sure the directory `C:\Program Files (x86)\kosace\Chaos Recipe Enhancer\` no longer exists. Once you asre certain, install it again and it should work.

I had similar problem and this has solved it.
