### ISSUE TITLE
lack of termination

### ISSUE THREAD

**Issue by markm812** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#83]
I don't remember exactly, but it ran out an exception error, then when I press OK, the same notification window came out again while the old one was still existing, so the more I press the more new window pops out, and eventually I have to restart my PC.

**Comment by kosace** [comment]
hey

can you tell me what you did?

I guess it has to do with the hotkeys but not sure

**Comment by markm812** [comment]
I believe so, I can't really remember, it only happened once and not anymore in these few days. Perhaps it has already been properly set-up?

**Comment by HiMarioLopez** [comment]
Closing due to age / lack of detail. Please re-open a new issue if needed! Thanks
