### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by dobrelaurentiu** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#84]
After a couple of days of using the tool with no issues I started getting this error while trying to start fetching. Any ideas ? 
![image](https://user-images.githubusercontent.com/21999697/104903755-1b661a80-5989-11eb-9ee0-ea1ef4785f22.png)

**Comment by gdarona** [comment]
Same since the last update.

**Comment by Khanatox** [comment]
Same here. Started yesterday and after even after i downloaded the latest version

Edit : Actually, i've uninstalled the application completely and redone the installation. After that it finally works.

**Comment by Gamewalker** [comment]
For reference #85

**Comment by LoneVoices** [comment]
Still with same problem, was fixed yesterday, today i uninstall and try the 1.1.5 version and got the fetching error, uninstall and went for 1.1.4 version and also having the error... did something happend to the tool or is a server problem?? or just me :(

**Comment by LoneVoices** [comment]
> Still with same problem, was fixed yesterday, today i uninstall and try the 1.1.5 version and got the fetching error, uninstall and went for 1.1.4 version and also having the error... did something happend to the tool or is a server problem?? or just me :(

Edit: fixed again XD

**Comment by dobrelaurentiu** [comment]
Just installed version 1.1.7 and seems to be working now.
