### ISSUE TITLE
Updating Application does not overwrite previous files

### ISSUE THREAD

**Issue by Gamewalker** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#85]
FYI:
Installing a newer version without uninstalling the previous version, does not overwrite old files.

Example:

Fail:
1. Install 1.1.3
2. Install 1.1.4
3. Version == 1.1.3

Working:
1. Install 1.1.3
2. Uninstall 1.1.3
3. Install 1.1.4
4. Version == 1.1.4

**Comment by kosace** [comment]
yes ikr.

i will provide a standalone .exe in the future but atm i cant change that. i will think about an auto updater but that is even farther away

**Comment by Davst** [comment]
Auto updater would indeed be nice but understandably far away.

@kosace could we see a readout fo the version number vs the current one so we could see if there was an update available, and a http link to the project in the meanwhile in the settings window? that way you could see in the overlay if you should update, and just click the link in the settings.

Regarding the installers, detecting the prescence of a installed version and automating the uninstall/install of the new one would be preferable to a standalone exe at least imo. 

Side note.. could the new versions be published with the version number in the installer name? else you end up with "(2) (3)" filenames in your download folder =)

**Comment by HiMarioLopez** [comment]
Auto-updater was added a few versions ago, hopefully that helps resolve any of these issues. If your issues persist, please open a new issue.
