### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by darkon76** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#86]
With the new league I get a bad Request popup

![image](https://user-images.githubusercontent.com/12821036/104925807-e8aa2b00-5964-11eb-8888-34a714aa6079.png)

**Comment by kosace** [comment]
wrong credentials.

check your account name and league

**Comment by Andbax** [comment]
I had the same problem with the 1.13 but it's solved in the 1.15

**Comment by darkon76** [comment]
It is odd I used the tool the first day and it worked, but it stop working, putting again the league name solved the problem. 

The popup should provide more information.
