### ISSUE TITLE
Wont recognize refresh rate

### ISSUE THREAD

**Issue by StickmonkeyGG** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#88]
![Screenshot 2021-01-18 204006](https://user-images.githubusercontent.com/77640769/104957197-f8118e80-59cd-11eb-9117-737115d93f2e.png)
it won't recognize any refresh rate under 45 sec

**Comment by kosace** [comment]
that is intended. 

i increased the minimum refreshrate because poe servers having problems

**Comment by StickmonkeyGG** [comment]
> that is intended.
> 
> i increased the minimum refreshrate because poe servers having problems

ahh ok, in that case, sorry for the inconvenience
