### ISSUE TITLE
Regal recipe

### ISSUE THREAD

**Issue by Hanndel** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#89]
Can you add regal recipe to it?

**Comment by masonk** [comment]
Yeah, currently regals are worth more than a chaos for the first time ever, so it would be awesome to have this :).

**Comment by lukezamboni** [comment]
Another vote on this request.

**Comment by jpwalsh1** [comment]
+1

**Comment by kosace** [comment]
check newest version
