### ISSUE TITLE
Clicks not registering

### ISSUE THREAD

**Issue by TaranArora** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#9]
When i ctrl click an item from my tab to my inventory, the item goes into my inventory but the red overlay still shows there where the item was, i have to click the red box again to go to the next item. This also messes up the set complete notification sound as i clicked once or twice previously in the previous step.

fetching takes a long time. i see that there are at least 4-5 more sets possible in my tab but the tool says 0 sets.

pushing the tool, i.e doing multiple things at once, crashes the tool without a warning or anything and resets everything. that is, account name, colour customizations, stash size, stash index,lootfilter location etc.

**Comment by kosace** [comment]
Hello,

which highlight mode do you have active?
Does it matter where you click the red box? For example is it better when you click it at the top?

**Comment by kosace** [comment]
The time while fetching is intended actually, I may change that in the future

How do you push the tool? Are you changing settings and stuff while fetching?

**Comment by TaranArora** [comment]
> Hello,
> 
> which highlight mode do you have active?
> Does it matter where you click the red box? For example is it better when you click it at the top?

Item by Item

The clicks are not registering when i click on the grid of the overlay, so for instance a 2x2 helmet/boot/glove, if i click in the middle,that is, not on the squares,but the exact middle where the lines intersect.

**Comment by TaranArora** [comment]
> The time while fetching is intended actually, I may change that in the future
> 
> How do you push the tool? Are you changing settings and stuff while fetching?

I can't really replicate the tool crashing,but it happens every so often. out of the blue. and all my settings are reset

**Comment by kosace** [comment]
the tool cant save the settings when it crashes. i have to investigate the crashes, can you tell me what you are doing? 

and for the registering: you do have version 1.0.8 right? can you check if you have changed your Windows display scaling? (right click desktop -> display settings -> scale and layout)

**Comment by SnuK87** [comment]
> When i ctrl click an item from my tab to my inventory, the item goes into my inventory but the red overlay still shows there where the item was, i have to click the red box again to go to the next item. 

I'm facing a similar issue but for me it's the opposite behavior. When I ctrl click the hightlighted item then the highlight box moves to the next item but the item is not moved to my inventory. I have to click again to move the item.

Using version `1.0.9` with highlight mode `Item by Item`

**Comment by kosace** [comment]
@SnuK87 can you try to open the stash overlay, then go in edit mode, leave edit mode and then try to click through?

I found a bug when you previoulsy were in edit mode.

**Comment by kosace** [comment]
should be fixed in version 1.1.0
