### ISSUE TITLE
DIspatcher.UnhandledException after PC crashed

### ISSUE THREAD

**Issue by Dane-M1191** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#90]
My PC crashed, and I have been getting this error when i run the Chaos recipe app ever since. The crash itself is unrelated to the app because my PC has been crashing for a few years now, but now the app wont start.

![Screenshot (177)](https://user-images.githubusercontent.com/74030366/104969389-ed470180-59ad-11eb-94a0-bf20d8fe2878.png)

I got it to work after installing to a different drive. I am just worried this problem will occur again since my PC will certainly crash again lol.

**Comment by kosace** [comment]
Hello,

Delete your settings and reinstall. The location can be found in the guide or in discord
