### ISSUE TITLE
Suggestion: Disable hotkeys when Path of Exile is not focused.

### ISSUE THREAD

**Issue by tamaroth** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#91]
It would be a good idea to allow for the keybinds to work only when Path of Exile is either focused or at least running. Currently, if I leave PoE but leave app working in the background, it will show up the grid/ui or update the state when pressing the chosen keybind. This is intrusive, as the chosen keybind might be used by other applications and I don't necessairly want app's grid to show up when I press 'Find Next' in the browser with the app running in the background. This forces me to exit the app and then launch it again once I'm playing the game.

**Comment by HiMarioLopez** [comment]
I think it's a good idea, but the amount of work required would outweight the gains. 99% of folks using this will only have it running during their PoE session. My suggestion would be to set a less-used keybind for this app if you want to use it while you are using many other programs. I know it's not much, but I hope this helps.
