### ISSUE TITLE
Fetch Start does not work

### ISSUE THREAD

**Issue by ikedakouji** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#92]
1.1.5
Account name/PoE Session ID/League are all correct. The Overlay for Stash tab even shows the tab name correctly. I can even set the loot filter colors. However it stops working there, as it does not seem to fetch start and count how many items I have on the (quad) tab, nor does the overlay guide me to a full set (with colors).

**Comment by rafaeljnv** [comment]
same here,, using the 1.17 and the problem dont go away

**Comment by JuGenZhang** [comment]
same here,1.1.8,Account name/PoE Session ID/League are correct,Error fetching data Forbidden

**Comment by kosace** [comment]
i think it was the servers again yesterday.

if you had version before 1.1.5 you should uninstall -> delete settings -> and install new one.

**Comment by JuGenZhang** [comment]
Thanks！It worked！
在2021年01月20日 18:54，kosace 写道:

i think it was the servers again yesterday.

if you had version before 1.1.5 you should uninstall -> delete settings -> and install new one.

**Comment by pemug** [comment]
Same for me.
I installed 1.8. i fully put all settings on : account name, POE session, League, Stashtab mod i tryed prefix and ID. Loot filter manipulation, loot filter destination but Fetch never work ( it keep loading the blue thing keep running ) 
![chaos](https://user-images.githubusercontent.com/12426760/105274432-75d7c480-5b9d-11eb-8366-f2586e564bde.png)

**Comment by pemug** [comment]
It work now 0o dont understand why

**Comment by kosace** [comment]
do what @JuGenZhang said. 

if that doesnt work check your poe session id.
if that doesnt work the servers are probably down again.
