### ISSUE TITLE
Weapons threshold calculation wrong

### ISSUE THREAD

**Issue by jrettsch** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#93]
Full Set Threshold is set to 16, but the weapons are disabled when it reaches 16 weapons, not counting that it needs 2 per chaos receipt.

My dump tab:
[https://imgur.com/a/ibbL6vn](url)

**Comment by kosace** [comment]
check version 1.1.6. 

reopen if issue persists please

**Comment by jrettsch** [comment]
Thank you for fixing it!
