### ISSUE TITLE
[Enhancement][Suggestion] Add in auto-updates

### ISSUE THREAD

**Issue by ivoryfitz** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#98]
Just throwing a suggestion out there to add in Auto-Update functionality. Very minor, low priority suggestion, but might be pretty easy to do? 

I found https://github.com/ravibpatel/AutoUpdater.NET
but I'm not a .NET dev, so I'm unsure if that would be a useful thing. It also appears that the default Windows .NET Framework has something called "ClickOnce" but from some brief googling, it seems a lot of people don't have a lot of love for that solution.

Anyways, great tool, just figured I'd throw an idea out there :)

**Comment by HiMarioLopez** [comment]
Done! Thanks.
